"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _UserRole:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _UserRoleEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_UserRole.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    USER: _UserRole.ValueType  # 0
    PRO: _UserRole.ValueType  # 1
    COMPANY: _UserRole.ValueType  # 2

class UserRole(_UserRole, metaclass=_UserRoleEnumTypeWrapper): ...

USER: UserRole.ValueType  # 0
PRO: UserRole.ValueType  # 1
COMPANY: UserRole.ValueType  # 2
Global___UserRole: _TypeAlias = UserRole  # noqa: Y015

@_typing.final
class LoginRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LOGIN_FIELD_NUMBER: _builtins.int
    PASSWORD_FIELD_NUMBER: _builtins.int
    USER_ROLE_FIELD_NUMBER: _builtins.int
    login: _builtins.str
    password: _builtins.str
    user_role: Global___UserRole.ValueType
    def __init__(
        self,
        *,
        login: _builtins.str = ...,
        password: _builtins.str = ...,
        user_role: Global___UserRole.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["login", b"login", "password", b"password", "user_role", b"user_role"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LoginRequest: _TypeAlias = LoginRequest  # noqa: Y015

@_typing.final
class LoginResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    USER_ROLE_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    FIRST_NAME_FIELD_NUMBER: _builtins.int
    LAST_NAME_FIELD_NUMBER: _builtins.int
    PHONE_NUMBER_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    user_role: Global___UserRole.ValueType
    email: _builtins.str
    first_name: _builtins.str
    last_name: _builtins.str
    phone_number: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        user_role: Global___UserRole.ValueType = ...,
        email: _builtins.str = ...,
        first_name: _builtins.str = ...,
        last_name: _builtins.str = ...,
        phone_number: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["email", b"email", "first_name", b"first_name", "last_name", b"last_name", "phone_number", b"phone_number", "user_id", b"user_id", "user_role", b"user_role"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LoginResponse: _TypeAlias = LoginResponse  # noqa: Y015
