"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from v3.mobilegwsvc.commonmodels.account import lite_account_pb2 as _lite_account_pb2
from v3.mobilegwsvc.commonmodels.response import response_pb2 as _response_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class StreamQrSessionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Success(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        INITIAL_FIELD_NUMBER: _builtins.int
        LOGIN_RESPONSE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def initial(self) -> Global___StreamQrSessionResponse.Initial: ...
        @_builtins.property
        def login_response(self) -> Global___StreamQrSessionResponse.LoginResponse: ...
        def __init__(
            self,
            *,
            initial: Global___StreamQrSessionResponse.Initial | None = ...,
            login_response: Global___StreamQrSessionResponse.LoginResponse | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["initial", b"initial", "login_response", b"login_response", "success", b"success"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["initial", b"initial", "login_response", b"login_response", "success", b"success"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_success: _TypeAlias = _typing.Literal["initial", "login_response"]  # noqa: Y015
        _WhichOneofArgType_success: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_success) -> _WhichOneofReturnType_success | None: ...

    @_typing.final
    class Initial(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        QR_SESSION_KEY_FIELD_NUMBER: _builtins.int
        qr_session_key: _builtins.bytes
        def __init__(
            self,
            *,
            qr_session_key: _builtins.bytes = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["qr_session_key", b"qr_session_key"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LoginResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SESSION_TOKEN_FIELD_NUMBER: _builtins.int
        LITE_ACCOUNT_FIELD_NUMBER: _builtins.int
        session_token: _builtins.bytes
        @_builtins.property
        def lite_account(self) -> _lite_account_pb2.LiteAccount: ...
        def __init__(
            self,
            *,
            session_token: _builtins.bytes = ...,
            lite_account: _lite_account_pb2.LiteAccount | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["lite_account", b"lite_account"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["lite_account", b"lite_account", "session_token", b"session_token"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class Failure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        BAD_REQUEST_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def bad_request(self) -> _response_pb2.Error: ...
        def __init__(
            self,
            *,
            bad_request: _response_pb2.Error | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "error", b"error"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "error", b"error"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_error: _TypeAlias = _typing.Literal["bad_request"]  # noqa: Y015
        _WhichOneofArgType_error: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_error) -> _WhichOneofReturnType_error | None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def success(self) -> Global___StreamQrSessionResponse.Success: ...
    @_builtins.property
    def failure(self) -> Global___StreamQrSessionResponse.Failure: ...
    def __init__(
        self,
        *,
        success: Global___StreamQrSessionResponse.Success | None = ...,
        failure: Global___StreamQrSessionResponse.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["success", "failure"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___StreamQrSessionResponse: _TypeAlias = StreamQrSessionResponse  # noqa: Y015
