"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AccessCardRc(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Rc:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _RcEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[AccessCardRc._Rc.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        ADDED: AccessCardRc._Rc.ValueType  # 0
        ALREADY_ADDED: AccessCardRc._Rc.ValueType  # 1
        CARD_FULL: AccessCardRc._Rc.ValueType  # 2
        TIMEOUT: AccessCardRc._Rc.ValueType  # 3
        INVALID_CARD: AccessCardRc._Rc.ValueType  # 4
        USER_TIMEOUT: AccessCardRc._Rc.ValueType  # 5
        NO_ANSWER: AccessCardRc._Rc.ValueType  # 6

    class Rc(_Rc, metaclass=_RcEnumTypeWrapper): ...
    ADDED: AccessCardRc.Rc.ValueType  # 0
    ALREADY_ADDED: AccessCardRc.Rc.ValueType  # 1
    CARD_FULL: AccessCardRc.Rc.ValueType  # 2
    TIMEOUT: AccessCardRc.Rc.ValueType  # 3
    INVALID_CARD: AccessCardRc.Rc.ValueType  # 4
    USER_TIMEOUT: AccessCardRc.Rc.ValueType  # 5
    NO_ANSWER: AccessCardRc.Rc.ValueType  # 6

    RC_FIELD_NUMBER: _builtins.int
    rc: Global___AccessCardRc.Rc.ValueType
    def __init__(
        self,
        *,
        rc: Global___AccessCardRc.Rc.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["rc", b"rc"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AccessCardRc: _TypeAlias = AccessCardRc  # noqa: Y015
