"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CompanyBinding(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _State:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[CompanyBinding._State.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_STATE_INFO: CompanyBinding._State.ValueType  # 0
        PENDING_ACCEPTANCE: CompanyBinding._State.ValueType  # 1
        ACCEPTED: CompanyBinding._State.ValueType  # 2
        PENDING_DELETION: CompanyBinding._State.ValueType  # 3

    class State(_State, metaclass=_StateEnumTypeWrapper): ...
    NO_STATE_INFO: CompanyBinding.State.ValueType  # 0
    PENDING_ACCEPTANCE: CompanyBinding.State.ValueType  # 1
    ACCEPTED: CompanyBinding.State.ValueType  # 2
    PENDING_DELETION: CompanyBinding.State.ValueType  # 3

    COMPANY_ID_FIELD_NUMBER: _builtins.int
    HUB_ID_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    BILLING_ENABLED_FIELD_NUMBER: _builtins.int
    COMPANY_LOCKED_FIELD_NUMBER: _builtins.int
    HUB_BLOCKED_BY_COMPANY_FIELD_NUMBER: _builtins.int
    BALANCE_FIELD_NUMBER: _builtins.int
    SUBSCRIPTION_FEE_FIELD_NUMBER: _builtins.int
    CURRENCY_FIELD_NUMBER: _builtins.int
    NEXT_PAYMENT_DATE_FIELD_NUMBER: _builtins.int
    COMPANY_NAME_FIELD_NUMBER: _builtins.int
    company_id: _builtins.str
    hub_id: _builtins.str
    state: Global___CompanyBinding.State.ValueType
    billing_enabled: _builtins.bool
    company_locked: _builtins.bool
    hub_blocked_by_company: _builtins.bool
    balance: _builtins.str
    subscription_fee: _builtins.str
    currency: _builtins.str
    next_payment_date: _builtins.str
    company_name: _builtins.str
    def __init__(
        self,
        *,
        company_id: _builtins.str = ...,
        hub_id: _builtins.str = ...,
        state: Global___CompanyBinding.State.ValueType = ...,
        billing_enabled: _builtins.bool = ...,
        company_locked: _builtins.bool = ...,
        hub_blocked_by_company: _builtins.bool = ...,
        balance: _builtins.str = ...,
        subscription_fee: _builtins.str = ...,
        currency: _builtins.str = ...,
        next_payment_date: _builtins.str = ...,
        company_name: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["balance", b"balance", "billing_enabled", b"billing_enabled", "company_id", b"company_id", "company_locked", b"company_locked", "company_name", b"company_name", "currency", b"currency", "hub_blocked_by_company", b"hub_blocked_by_company", "hub_id", b"hub_id", "next_payment_date", b"next_payment_date", "state", b"state", "subscription_fee", b"subscription_fee"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CompanyBinding: _TypeAlias = CompanyBinding  # noqa: Y015
