"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from v1.common import address_pb2 as _address_pb2
from v1.common import email_address_pb2 as _email_address_pb2
from v1.common import phone_number_pb2 as _phone_number_pb2
from v1.facility import facility_monitoring_status_pb2 as _facility_monitoring_status_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Facility(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _ConnectionStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ConnectionStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Facility._ConnectionStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        OFFLINE: Facility._ConnectionStatus.ValueType  # 0
        ONLINE: Facility._ConnectionStatus.ValueType  # 1

    class ConnectionStatus(_ConnectionStatus, metaclass=_ConnectionStatusEnumTypeWrapper): ...
    OFFLINE: Facility.ConnectionStatus.ValueType  # 0
    ONLINE: Facility.ConnectionStatus.ValueType  # 1

    class _Status:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Facility._Status.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        MONITORING_APPROVED: Facility._Status.ValueType  # 0
        MONITORING_REQUESTED: Facility._Status.ValueType  # 1
        IN_SLEEP_MODE: Facility._Status.ValueType  # 2
        NO_MONITORING: Facility._Status.ValueType  # 3

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    MONITORING_APPROVED: Facility.Status.ValueType  # 0
    MONITORING_REQUESTED: Facility.Status.ValueType  # 1
    IN_SLEEP_MODE: Facility.Status.ValueType  # 2
    NO_MONITORING: Facility.Status.ValueType  # 3

    class _PrivacyOverrideStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _PrivacyOverrideStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Facility._PrivacyOverrideStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        PRIVACY_OVERRIDE_STATUS_UNSPECIFIED: Facility._PrivacyOverrideStatus.ValueType  # 0
        PRIVACY_OVERRIDE_STATUS_DISABLED: Facility._PrivacyOverrideStatus.ValueType  # 1
        PRIVACY_OVERRIDE_STATUS_ENABLED: Facility._PrivacyOverrideStatus.ValueType  # 2

    class PrivacyOverrideStatus(_PrivacyOverrideStatus, metaclass=_PrivacyOverrideStatusEnumTypeWrapper): ...
    PRIVACY_OVERRIDE_STATUS_UNSPECIFIED: Facility.PrivacyOverrideStatus.ValueType  # 0
    PRIVACY_OVERRIDE_STATUS_DISABLED: Facility.PrivacyOverrideStatus.ValueType  # 1
    PRIVACY_OVERRIDE_STATUS_ENABLED: Facility.PrivacyOverrideStatus.ValueType  # 2

    @_typing.final
    class GeneralInfo(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        NAME_FIELD_NUMBER: _builtins.int
        REGISTRATION_NUMBER_FIELD_NUMBER: _builtins.int
        ADDRESS_FIELD_NUMBER: _builtins.int
        PHONE_NUMBERS_FIELD_NUMBER: _builtins.int
        EMAIL_ADDRESSES_FIELD_NUMBER: _builtins.int
        name: _builtins.str
        registration_number: _builtins.str
        @_builtins.property
        def address(self) -> _address_pb2.Address: ...
        @_builtins.property
        def phone_numbers(self) -> _containers.RepeatedCompositeFieldContainer[_phone_number_pb2.PhoneNumber]: ...
        @_builtins.property
        def email_addresses(self) -> _containers.RepeatedCompositeFieldContainer[_email_address_pb2.EmailAddress]: ...
        def __init__(
            self,
            *,
            name: _builtins.str = ...,
            registration_number: _builtins.str = ...,
            address: _address_pb2.Address | None = ...,
            phone_numbers: _abc.Iterable[_phone_number_pb2.PhoneNumber] | None = ...,
            email_addresses: _abc.Iterable[_email_address_pb2.EmailAddress] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["address", b"address"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "email_addresses", b"email_addresses", "name", b"name", "phone_numbers", b"phone_numbers", "registration_number", b"registration_number"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class Note(_message.Message):
        """Note"""

        DESCRIPTOR: _descriptor.Descriptor

        ID_FIELD_NUMBER: _builtins.int
        FACILITY_ID_FIELD_NUMBER: _builtins.int
        TEXT_FIELD_NUMBER: _builtins.int
        VERSION_FIELD_NUMBER: _builtins.int
        INDEX_FIELD_NUMBER: _builtins.int
        id: _builtins.str
        facility_id: _builtins.str
        text: _builtins.str
        """updatable"""
        version: _builtins.int
        index: _builtins.int
        def __init__(
            self,
            *,
            id: _builtins.str = ...,
            facility_id: _builtins.str = ...,
            text: _builtins.str = ...,
            version: _builtins.int = ...,
            index: _builtins.int = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["facility_id", b"facility_id", "id", b"id", "index", b"index", "text", b"text", "version", b"version"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    ID_FIELD_NUMBER: _builtins.int
    HUB_ID_FIELD_NUMBER: _builtins.int
    HUB_NAME_FIELD_NUMBER: _builtins.int
    COMPANY_ID_FIELD_NUMBER: _builtins.int
    FACILITY_GENERAL_INFO_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    CONNECTION_STATUS_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    HUB_LOCKED_BY_COMPANY_FIELD_NUMBER: _builtins.int
    SLEEP_UNTIL_FIELD_NUMBER: _builtins.int
    PRIVACY_OVERRIDE_STATUS_FIELD_NUMBER: _builtins.int
    MONITORING_STATUS_FIELD_NUMBER: _builtins.int
    SPACE_ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    hub_id: _builtins.str
    hub_name: _builtins.str
    company_id: _builtins.str
    status: Global___Facility.Status.ValueType
    connection_status: Global___Facility.ConnectionStatus.ValueType
    version: _builtins.int
    hub_locked_by_company: _builtins.bool
    privacy_override_status: Global___Facility.PrivacyOverrideStatus.ValueType
    monitoring_status: _facility_monitoring_status_pb2.MonitoringStatus.ValueType
    space_id: _builtins.str
    @_builtins.property
    def facility_general_info(self) -> Global___Facility.GeneralInfo: ...
    @_builtins.property
    def sleep_until(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        hub_id: _builtins.str | None = ...,
        hub_name: _builtins.str | None = ...,
        company_id: _builtins.str = ...,
        facility_general_info: Global___Facility.GeneralInfo | None = ...,
        status: Global___Facility.Status.ValueType = ...,
        connection_status: Global___Facility.ConnectionStatus.ValueType = ...,
        version: _builtins.int = ...,
        hub_locked_by_company: _builtins.bool | None = ...,
        sleep_until: _timestamp_pb2.Timestamp | None = ...,
        privacy_override_status: Global___Facility.PrivacyOverrideStatus.ValueType = ...,
        monitoring_status: _facility_monitoring_status_pb2.MonitoringStatus.ValueType = ...,
        space_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_hub_id", b"_hub_id", "_hub_locked_by_company", b"_hub_locked_by_company", "_hub_name", b"_hub_name", "facility_general_info", b"facility_general_info", "hub_id", b"hub_id", "hub_locked_by_company", b"hub_locked_by_company", "hub_name", b"hub_name", "sleep_until", b"sleep_until"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_hub_id", b"_hub_id", "_hub_locked_by_company", b"_hub_locked_by_company", "_hub_name", b"_hub_name", "company_id", b"company_id", "connection_status", b"connection_status", "facility_general_info", b"facility_general_info", "hub_id", b"hub_id", "hub_locked_by_company", b"hub_locked_by_company", "hub_name", b"hub_name", "id", b"id", "monitoring_status", b"monitoring_status", "privacy_override_status", b"privacy_override_status", "sleep_until", b"sleep_until", "space_id", b"space_id", "status", b"status", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__hub_id: _TypeAlias = _typing.Literal["hub_id"]  # noqa: Y015
    _WhichOneofArgType__hub_id: _TypeAlias = _typing.Literal["_hub_id", b"_hub_id"]  # noqa: Y015
    _WhichOneofReturnType__hub_locked_by_company: _TypeAlias = _typing.Literal["hub_locked_by_company"]  # noqa: Y015
    _WhichOneofArgType__hub_locked_by_company: _TypeAlias = _typing.Literal["_hub_locked_by_company", b"_hub_locked_by_company"]  # noqa: Y015
    _WhichOneofReturnType__hub_name: _TypeAlias = _typing.Literal["hub_name"]  # noqa: Y015
    _WhichOneofArgType__hub_name: _TypeAlias = _typing.Literal["_hub_name", b"_hub_name"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__hub_id) -> _WhichOneofReturnType__hub_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__hub_locked_by_company) -> _WhichOneofReturnType__hub_locked_by_company | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__hub_name) -> _WhichOneofReturnType__hub_name | None: ...

Global___Facility: _TypeAlias = Facility  # noqa: Y015
