"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class HubCommandFireZoneTestRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class StartFireZoneTest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        class _TypeOfOutputActivate:
            ValueType = _typing.NewType("ValueType", _builtins.int)
            V: _TypeAlias = ValueType  # noqa: Y015

        class _TypeOfOutputActivateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HubCommandFireZoneTestRequest.StartFireZoneTest._TypeOfOutputActivate.ValueType], _builtins.type):
            DESCRIPTOR: _descriptor.EnumDescriptor
            TYPE_OF_OUTPUT_ACTIVATE_UNSPECIFIED: HubCommandFireZoneTestRequest.StartFireZoneTest._TypeOfOutputActivate.ValueType  # 0
            TYPE_OF_OUTPUT_ACTIVATE_DO_NOT_ACTIVATE_OUTPUTS: HubCommandFireZoneTestRequest.StartFireZoneTest._TypeOfOutputActivate.ValueType  # 1
            TYPE_OF_OUTPUT_ACTIVATE_ACTIVATE_ONLY_IN_TESTED_ZONES: HubCommandFireZoneTestRequest.StartFireZoneTest._TypeOfOutputActivate.ValueType  # 2
            TYPE_OF_OUTPUT_ACTIVATE_ACTIVATE_IN_ALL_ZONES: HubCommandFireZoneTestRequest.StartFireZoneTest._TypeOfOutputActivate.ValueType  # 3

        class TypeOfOutputActivate(_TypeOfOutputActivate, metaclass=_TypeOfOutputActivateEnumTypeWrapper): ...
        TYPE_OF_OUTPUT_ACTIVATE_UNSPECIFIED: HubCommandFireZoneTestRequest.StartFireZoneTest.TypeOfOutputActivate.ValueType  # 0
        TYPE_OF_OUTPUT_ACTIVATE_DO_NOT_ACTIVATE_OUTPUTS: HubCommandFireZoneTestRequest.StartFireZoneTest.TypeOfOutputActivate.ValueType  # 1
        TYPE_OF_OUTPUT_ACTIVATE_ACTIVATE_ONLY_IN_TESTED_ZONES: HubCommandFireZoneTestRequest.StartFireZoneTest.TypeOfOutputActivate.ValueType  # 2
        TYPE_OF_OUTPUT_ACTIVATE_ACTIVATE_IN_ALL_ZONES: HubCommandFireZoneTestRequest.StartFireZoneTest.TypeOfOutputActivate.ValueType  # 3

        class _OutputDevice:
            ValueType = _typing.NewType("ValueType", _builtins.int)
            V: _TypeAlias = ValueType  # noqa: Y015

        class _OutputDeviceEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HubCommandFireZoneTestRequest.StartFireZoneTest._OutputDevice.ValueType], _builtins.type):
            DESCRIPTOR: _descriptor.EnumDescriptor
            OUTPUT_DEVICE_UNSPECIFIED: HubCommandFireZoneTestRequest.StartFireZoneTest._OutputDevice.ValueType  # 0
            OUTPUT_DEVICE_SOUNDERS: HubCommandFireZoneTestRequest.StartFireZoneTest._OutputDevice.ValueType  # 1
            OUTPUT_DEVICE_VADS: HubCommandFireZoneTestRequest.StartFireZoneTest._OutputDevice.ValueType  # 2
            OUTPUT_DEVICE_RELAYS: HubCommandFireZoneTestRequest.StartFireZoneTest._OutputDevice.ValueType  # 3

        class OutputDevice(_OutputDevice, metaclass=_OutputDeviceEnumTypeWrapper): ...
        OUTPUT_DEVICE_UNSPECIFIED: HubCommandFireZoneTestRequest.StartFireZoneTest.OutputDevice.ValueType  # 0
        OUTPUT_DEVICE_SOUNDERS: HubCommandFireZoneTestRequest.StartFireZoneTest.OutputDevice.ValueType  # 1
        OUTPUT_DEVICE_VADS: HubCommandFireZoneTestRequest.StartFireZoneTest.OutputDevice.ValueType  # 2
        OUTPUT_DEVICE_RELAYS: HubCommandFireZoneTestRequest.StartFireZoneTest.OutputDevice.ValueType  # 3

        TYPE_OF_OUTPUT_ACTIVATE_FIELD_NUMBER: _builtins.int
        OUTPUT_DEVICES_FIELD_NUMBER: _builtins.int
        type_of_output_activate: Global___HubCommandFireZoneTestRequest.StartFireZoneTest.TypeOfOutputActivate.ValueType
        @_builtins.property
        def output_devices(self) -> _containers.RepeatedScalarFieldContainer[Global___HubCommandFireZoneTestRequest.StartFireZoneTest.OutputDevice.ValueType]: ...
        def __init__(
            self,
            *,
            type_of_output_activate: Global___HubCommandFireZoneTestRequest.StartFireZoneTest.TypeOfOutputActivate.ValueType = ...,
            output_devices: _abc.Iterable[Global___HubCommandFireZoneTestRequest.StartFireZoneTest.OutputDevice.ValueType] | None = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["output_devices", b"output_devices", "type_of_output_activate", b"type_of_output_activate"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class AddFireZoneToTest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @_typing.final
    class RemoveFireZoneFromTest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    HUB_ID_FIELD_NUMBER: _builtins.int
    FIRE_ZONE_ID_FIELD_NUMBER: _builtins.int
    START_FIRE_ZONE_TEST_FIELD_NUMBER: _builtins.int
    ADD_FIRE_ZONE_TO_TEST_FIELD_NUMBER: _builtins.int
    REMOVE_FIRE_ZONE_FROM_TEST_FIELD_NUMBER: _builtins.int
    hub_id: _builtins.str
    fire_zone_id: _builtins.str
    @_builtins.property
    def start_fire_zone_test(self) -> Global___HubCommandFireZoneTestRequest.StartFireZoneTest: ...
    @_builtins.property
    def add_fire_zone_to_test(self) -> Global___HubCommandFireZoneTestRequest.AddFireZoneToTest: ...
    @_builtins.property
    def remove_fire_zone_from_test(self) -> Global___HubCommandFireZoneTestRequest.RemoveFireZoneFromTest: ...
    def __init__(
        self,
        *,
        hub_id: _builtins.str = ...,
        fire_zone_id: _builtins.str = ...,
        start_fire_zone_test: Global___HubCommandFireZoneTestRequest.StartFireZoneTest | None = ...,
        add_fire_zone_to_test: Global___HubCommandFireZoneTestRequest.AddFireZoneToTest | None = ...,
        remove_fire_zone_from_test: Global___HubCommandFireZoneTestRequest.RemoveFireZoneFromTest | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["add_fire_zone_to_test", b"add_fire_zone_to_test", "fire_zone_test_subcommand", b"fire_zone_test_subcommand", "remove_fire_zone_from_test", b"remove_fire_zone_from_test", "start_fire_zone_test", b"start_fire_zone_test"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["add_fire_zone_to_test", b"add_fire_zone_to_test", "fire_zone_id", b"fire_zone_id", "fire_zone_test_subcommand", b"fire_zone_test_subcommand", "hub_id", b"hub_id", "remove_fire_zone_from_test", b"remove_fire_zone_from_test", "start_fire_zone_test", b"start_fire_zone_test"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_fire_zone_test_subcommand: _TypeAlias = _typing.Literal["start_fire_zone_test", "add_fire_zone_to_test", "remove_fire_zone_from_test"]  # noqa: Y015
    _WhichOneofArgType_fire_zone_test_subcommand: _TypeAlias = _typing.Literal["fire_zone_test_subcommand", b"fire_zone_test_subcommand"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_fire_zone_test_subcommand) -> _WhichOneofReturnType_fire_zone_test_subcommand | None: ...

Global___HubCommandFireZoneTestRequest: _TypeAlias = HubCommandFireZoneTestRequest  # noqa: Y015
