"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _DisplayedChimeStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _DisplayedChimeStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_DisplayedChimeStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    DISPLAYED_CHIME_STATUS_UNSPECIFIED: _DisplayedChimeStatus.ValueType  # 0
    DISPLAYED_CHIME_STATUS_ENABLED: _DisplayedChimeStatus.ValueType  # 1
    DISPLAYED_CHIME_STATUS_CAN_BE_ENABLED: _DisplayedChimeStatus.ValueType  # 2
    DISPLAYED_CHIME_STATUS_MALFUNCTION: _DisplayedChimeStatus.ValueType  # 3
    DISPLAYED_CHIME_STATUS_DISABLED: _DisplayedChimeStatus.ValueType  # 4

class DisplayedChimeStatus(_DisplayedChimeStatus, metaclass=_DisplayedChimeStatusEnumTypeWrapper): ...

DISPLAYED_CHIME_STATUS_UNSPECIFIED: DisplayedChimeStatus.ValueType  # 0
DISPLAYED_CHIME_STATUS_ENABLED: DisplayedChimeStatus.ValueType  # 1
DISPLAYED_CHIME_STATUS_CAN_BE_ENABLED: DisplayedChimeStatus.ValueType  # 2
DISPLAYED_CHIME_STATUS_MALFUNCTION: DisplayedChimeStatus.ValueType  # 3
DISPLAYED_CHIME_STATUS_DISABLED: DisplayedChimeStatus.ValueType  # 4
Global___DisplayedChimeStatus: _TypeAlias = DisplayedChimeStatus  # noqa: Y015
