"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.mobile.v2.common.image import image_pb2 as _image_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SpaceProfile(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    IMAGES_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    @_builtins.property
    def images(self) -> _image_pb2.Images: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        images: _image_pb2.Images | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["images", b"images"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["images", b"images", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SpaceProfile: _TypeAlias = SpaceProfile  # noqa: Y015
