"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from systems.ajax.api.mobile.v2.common.response import response_pb2 as _response_pb2_1
from systems.ajax.api.mobile.v2.common.space.security.group import group_pb2 as _group_pb2
from v3.mobilegwsvc.commonmodels.response import response_pb2 as _response_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetAvailableFollowedGroupsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Success(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        GROUPS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def groups(self) -> _containers.RepeatedCompositeFieldContainer[_group_pb2.Group]: ...
        def __init__(
            self,
            *,
            groups: _abc.Iterable[_group_pb2.Group] | None = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["groups", b"groups"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class Failure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        BAD_REQUEST_FIELD_NUMBER: _builtins.int
        PERMISSION_DENIED_FIELD_NUMBER: _builtins.int
        SPACE_ARMED_FIELD_NUMBER: _builtins.int
        SPACE_LOCKED_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def bad_request(self) -> _response_pb2.Error: ...
        @_builtins.property
        def permission_denied(self) -> _response_pb2.Error: ...
        @_builtins.property
        def space_armed(self) -> _response_pb2.Error: ...
        @_builtins.property
        def space_locked(self) -> _response_pb2_1.SpaceLockedError: ...
        def __init__(
            self,
            *,
            bad_request: _response_pb2.Error | None = ...,
            permission_denied: _response_pb2.Error | None = ...,
            space_armed: _response_pb2.Error | None = ...,
            space_locked: _response_pb2_1.SpaceLockedError | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "error", b"error", "permission_denied", b"permission_denied", "space_armed", b"space_armed", "space_locked", b"space_locked"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "error", b"error", "permission_denied", b"permission_denied", "space_armed", b"space_armed", "space_locked", b"space_locked"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_error: _TypeAlias = _typing.Literal["bad_request", "permission_denied", "space_armed", "space_locked"]  # noqa: Y015
        _WhichOneofArgType_error: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_error) -> _WhichOneofReturnType_error | None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def success(self) -> Global___GetAvailableFollowedGroupsResponse.Success: ...
    @_builtins.property
    def failure(self) -> Global___GetAvailableFollowedGroupsResponse.Failure: ...
    def __init__(
        self,
        *,
        success: Global___GetAvailableFollowedGroupsResponse.Success | None = ...,
        failure: Global___GetAvailableFollowedGroupsResponse.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["success", "failure"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___GetAvailableFollowedGroupsResponse: _TypeAlias = GetAvailableFollowedGroupsResponse  # noqa: Y015
