"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _HubType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _HubTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_HubType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    HUB_TYPE_UNSPECIFIED: _HubType.ValueType  # 0
    HUB_TYPE_HUB: _HubType.ValueType  # 1
    HUB_TYPE_HUB_PLUS: _HubType.ValueType  # 2
    HUB_TYPE_YAVIR: _HubType.ValueType  # 3
    HUB_TYPE_YAVIR_PLUS: _HubType.ValueType  # 4
    HUB_TYPE_HUB_2: _HubType.ValueType  # 5
    HUB_TYPE_HUB_2_PLUS: _HubType.ValueType  # 6
    HUB_TYPE_HUB_3: _HubType.ValueType  # 7
    HUB_TYPE_HUB_FIBRA: _HubType.ValueType  # 8
    HUB_TYPE_HUB_LITE: _HubType.ValueType  # 9
    HUB_TYPE_HUB_2_4G: _HubType.ValueType  # 10
    HUB_TYPE_HUB_HYBRID_4G: _HubType.ValueType  # 11
    HUB_TYPE_HUB_4G: _HubType.ValueType  # 12
    HUB_TYPE_HUB_VOID_4G: _HubType.ValueType  # 13
    HUB_TYPE_HUB1_DEPRECATED: _HubType.ValueType  # 14
    HUB_TYPE_HUB_2_PROSEGUR: _HubType.ValueType  # 15
    HUB_TYPE_HUB_FIRE: _HubType.ValueType  # 16
    HUB_TYPE_HUB_2_LTE_RTK: _HubType.ValueType  # 17
    HUB_TYPE_HUB_MEGA: _HubType.ValueType  # 18
    HUB_TYPE_HUB_SUPERIOR: _HubType.ValueType  # 19
    HUB_TYPE_HUB_HYBRID_2: _HubType.ValueType  # 20

class HubType(_HubType, metaclass=_HubTypeEnumTypeWrapper): ...

HUB_TYPE_UNSPECIFIED: HubType.ValueType  # 0
HUB_TYPE_HUB: HubType.ValueType  # 1
HUB_TYPE_HUB_PLUS: HubType.ValueType  # 2
HUB_TYPE_YAVIR: HubType.ValueType  # 3
HUB_TYPE_YAVIR_PLUS: HubType.ValueType  # 4
HUB_TYPE_HUB_2: HubType.ValueType  # 5
HUB_TYPE_HUB_2_PLUS: HubType.ValueType  # 6
HUB_TYPE_HUB_3: HubType.ValueType  # 7
HUB_TYPE_HUB_FIBRA: HubType.ValueType  # 8
HUB_TYPE_HUB_LITE: HubType.ValueType  # 9
HUB_TYPE_HUB_2_4G: HubType.ValueType  # 10
HUB_TYPE_HUB_HYBRID_4G: HubType.ValueType  # 11
HUB_TYPE_HUB_4G: HubType.ValueType  # 12
HUB_TYPE_HUB_VOID_4G: HubType.ValueType  # 13
HUB_TYPE_HUB1_DEPRECATED: HubType.ValueType  # 14
HUB_TYPE_HUB_2_PROSEGUR: HubType.ValueType  # 15
HUB_TYPE_HUB_FIRE: HubType.ValueType  # 16
HUB_TYPE_HUB_2_LTE_RTK: HubType.ValueType  # 17
HUB_TYPE_HUB_MEGA: HubType.ValueType  # 18
HUB_TYPE_HUB_SUPERIOR: HubType.ValueType  # 19
HUB_TYPE_HUB_HYBRID_2: HubType.ValueType  # 20
Global___HubType: _TypeAlias = HubType  # noqa: Y015
