"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _SimCardStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SimCardStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SimCardStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SIM_CARD_STATUS_UNSPECIFIED: _SimCardStatus.ValueType  # 0
    SIM_CARD_STATUS_OK: _SimCardStatus.ValueType  # 1
    SIM_CARD_STATUS_MISSING: _SimCardStatus.ValueType  # 2
    SIM_CARD_STATUS_MALFUNCTION: _SimCardStatus.ValueType  # 3
    SIM_CARD_STATUS_LOCKED: _SimCardStatus.ValueType  # 4
    SIM_CARD_STATUS_UNKNOWN: _SimCardStatus.ValueType  # 5

class SimCardStatus(_SimCardStatus, metaclass=_SimCardStatusEnumTypeWrapper): ...

SIM_CARD_STATUS_UNSPECIFIED: SimCardStatus.ValueType  # 0
SIM_CARD_STATUS_OK: SimCardStatus.ValueType  # 1
SIM_CARD_STATUS_MISSING: SimCardStatus.ValueType  # 2
SIM_CARD_STATUS_MALFUNCTION: SimCardStatus.ValueType  # 3
SIM_CARD_STATUS_LOCKED: SimCardStatus.ValueType  # 4
SIM_CARD_STATUS_UNKNOWN: SimCardStatus.ValueType  # 5
Global___SimCardStatus: _TypeAlias = SimCardStatus  # noqa: Y015
