"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from systems.ajax.protobuf.gw import error_pb2 as _error_pb2
from systems.ajax.protobuf.hub import user_pb2 as _user_pb2
from systems.ajax.protobuf.v2.hub import hub_for_migration_pb2 as _hub_for_migration_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SubscriptionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TIMESTAMP_TO_DROP_FIELD_NUMBER: _builtins.int
    PERMISSIONS_FIELD_NUMBER: _builtins.int
    timestamp_to_drop: _builtins.int
    @_builtins.property
    def permissions(self) -> _containers.RepeatedScalarFieldContainer[_user_pb2.User.Permission.ValueType]: ...
    def __init__(
        self,
        *,
        timestamp_to_drop: _builtins.int = ...,
        permissions: _abc.Iterable[_user_pb2.User.Permission.ValueType] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["permissions", b"permissions", "timestamp_to_drop", b"timestamp_to_drop"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SubscriptionResponse: _TypeAlias = SubscriptionResponse  # noqa: Y015

@_typing.final
class GetHubForMigrationResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    HUB_FOR_MIGRATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error(self) -> _error_pb2.GwError: ...
    @_builtins.property
    def hub_for_migration(self) -> _hub_for_migration_pb2.HubForMigration: ...
    def __init__(
        self,
        *,
        error: _error_pb2.GwError | None = ...,
        hub_for_migration: _hub_for_migration_pb2.HubForMigration | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "hub_for_migration", b"hub_for_migration", "response", b"response"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "hub_for_migration", b"hub_for_migration", "response", b"response"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["error", "hub_for_migration"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___GetHubForMigrationResponse: _TypeAlias = GetHubForMigrationResponse  # noqa: Y015
