"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.ecosystem.v2.commonmodels.device.common import device_type_pb2 as _device_type_pb2
from v3.mobilegwsvc.commonmodels.space.device.light import light_device_id_pb2 as _light_device_id_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DeviceIdentifier(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def id(self) -> _light_device_id_pb2.LightDeviceId: ...
    @_builtins.property
    def type(self) -> _device_type_pb2.DeviceType: ...
    def __init__(
        self,
        *,
        id: _light_device_id_pb2.LightDeviceId | None = ...,
        type: _device_type_pb2.DeviceType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "type", b"type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeviceIdentifier: _TypeAlias = DeviceIdentifier  # noqa: Y015
