"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.company.additional.data import initiator_info_pb2 as _initiator_info_pb2
from systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.company.additional.data import permission_claim_type_pb2 as _permission_claim_type_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

if sys.version_info >= (3, 13):
    from warnings import deprecated as _deprecated
else:
    from typing_extensions import deprecated as _deprecated

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CompanyPermissionsClaimResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    COMPANY_NAME_FIELD_NUMBER: _builtins.int
    COMPANY_MAIL_FIELD_NUMBER: _builtins.int
    PERMISSIONS_TYPE_FIELD_NUMBER: _builtins.int
    INITIATOR_INFO_FIELD_NUMBER: _builtins.int
    request_id: _builtins.str
    company_name: _builtins.str
    company_mail: _builtins.str
    @_builtins.property
    def permissions_type(self) -> _permission_claim_type_pb2.PermissionsClaimType: ...
    @_builtins.property
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def initiator_info(self) -> _initiator_info_pb2.InitiatorInfo: ...
    def __init__(
        self,
        *,
        request_id: _builtins.str = ...,
        company_name: _builtins.str = ...,
        company_mail: _builtins.str = ...,
        permissions_type: _permission_claim_type_pb2.PermissionsClaimType | None = ...,
        initiator_info: _initiator_info_pb2.InitiatorInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["initiator_info", b"initiator_info", "permissions_type", b"permissions_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["company_mail", b"company_mail", "company_name", b"company_name", "initiator_info", b"initiator_info", "permissions_type", b"permissions_type", "request_id", b"request_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CompanyPermissionsClaimResponse: _TypeAlias = CompanyPermissionsClaimResponse  # noqa: Y015
