"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from v3.mobilegwsvc.commonmodels.response import response_pb2 as _response_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class FindAllZombieChannelsOnVideoEdgeResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Success(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class ZombieChannel(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            ID_FIELD_NUMBER: _builtins.int
            NAME_FIELD_NUMBER: _builtins.int
            id: _builtins.str
            name: _builtins.str
            def __init__(
                self,
                *,
                id: _builtins.str = ...,
                name: _builtins.str | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["_name", b"_name", "name", b"name"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["_name", b"_name", "id", b"id", "name", b"name"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            _WhichOneofReturnType__name: _TypeAlias = _typing.Literal["name"]  # noqa: Y015
            _WhichOneofArgType__name: _TypeAlias = _typing.Literal["_name", b"_name"]  # noqa: Y015
            def WhichOneof(self, oneof_group: _WhichOneofArgType__name) -> _WhichOneofReturnType__name | None: ...

        CHANNELS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def channels(self) -> _containers.RepeatedCompositeFieldContainer[Global___FindAllZombieChannelsOnVideoEdgeResponse.Success.ZombieChannel]: ...
        def __init__(
            self,
            *,
            channels: _abc.Iterable[Global___FindAllZombieChannelsOnVideoEdgeResponse.Success.ZombieChannel] | None = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["channels", b"channels"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class Failure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        BAD_REQUEST_FIELD_NUMBER: _builtins.int
        PERMISSION_DENIED_FIELD_NUMBER: _builtins.int
        SPACE_NOT_FOUND_FIELD_NUMBER: _builtins.int
        VIDEO_EDGE_NOT_FOUND_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def bad_request(self) -> _response_pb2.Error: ...
        @_builtins.property
        def permission_denied(self) -> _response_pb2.Error: ...
        @_builtins.property
        def space_not_found(self) -> _response_pb2.Error: ...
        @_builtins.property
        def video_edge_not_found(self) -> _response_pb2.Error: ...
        def __init__(
            self,
            *,
            bad_request: _response_pb2.Error | None = ...,
            permission_denied: _response_pb2.Error | None = ...,
            space_not_found: _response_pb2.Error | None = ...,
            video_edge_not_found: _response_pb2.Error | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "error", b"error", "permission_denied", b"permission_denied", "space_not_found", b"space_not_found", "video_edge_not_found", b"video_edge_not_found"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "error", b"error", "permission_denied", b"permission_denied", "space_not_found", b"space_not_found", "video_edge_not_found", b"video_edge_not_found"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_error: _TypeAlias = _typing.Literal["bad_request", "permission_denied", "space_not_found", "video_edge_not_found"]  # noqa: Y015
        _WhichOneofArgType_error: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_error) -> _WhichOneofReturnType_error | None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def success(self) -> Global___FindAllZombieChannelsOnVideoEdgeResponse.Success: ...
    @_builtins.property
    def failure(self) -> Global___FindAllZombieChannelsOnVideoEdgeResponse.Failure: ...
    def __init__(
        self,
        *,
        success: Global___FindAllZombieChannelsOnVideoEdgeResponse.Success | None = ...,
        failure: Global___FindAllZombieChannelsOnVideoEdgeResponse.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["success", "failure"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___FindAllZombieChannelsOnVideoEdgeResponse: _TypeAlias = FindAllZombieChannelsOnVideoEdgeResponse  # noqa: Y015
