"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import assigned_extender_pb2 as _assigned_extender_pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import bypass_part_pb2 as _bypass_part_pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import cms_device_index_pb2 as _cms_device_index_pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import device_common_capabilities_pb2 as _device_common_capabilities_pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import device_malfunctions_pb2 as _device_malfunctions_pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import device_migration_status_pb2 as _device_migration_status_pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import device_profile_pb2 as _device_profile_pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import device_telemetry_pb2 as _device_telemetry_pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import device_transmission_power_mode_pb2 as _device_transmission_power_mode_pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import self_monitoring_part_pb2 as _self_monitoring_part_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CommonJewellerPart(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_PROFILE_FIELD_NUMBER: _builtins.int
    DEVICE_TELEMETRY_FIELD_NUMBER: _builtins.int
    DEVICE_TRANSMISSION_POWER_MODE_FIELD_NUMBER: _builtins.int
    DEVICE_MALFUNCTIONS_FIELD_NUMBER: _builtins.int
    ASSIGNED_EXTENDER_FIELD_NUMBER: _builtins.int
    CMS_DEVICE_INDEX_FIELD_NUMBER: _builtins.int
    BYPASS_PART_FIELD_NUMBER: _builtins.int
    DEVICE_MIGRATION_STATUS_FIELD_NUMBER: _builtins.int
    DEVICE_COMMON_CAPABILITIES_FIELD_NUMBER: _builtins.int
    SELF_MONITORING_PART_FIELD_NUMBER: _builtins.int
    device_transmission_power_mode: _device_transmission_power_mode_pb2.DeviceTransmissionPowerMode.ValueType
    device_migration_status: _device_migration_status_pb2.DeviceMigrationStatus.ValueType
    @_builtins.property
    def device_profile(self) -> _device_profile_pb2.DeviceProfile: ...
    @_builtins.property
    def device_telemetry(self) -> _device_telemetry_pb2.DeviceTelemetry: ...
    @_builtins.property
    def device_malfunctions(self) -> _device_malfunctions_pb2.DeviceMalfunctions: ...
    @_builtins.property
    def assigned_extender(self) -> _assigned_extender_pb2.AssignedExtender: ...
    @_builtins.property
    def cms_device_index(self) -> _cms_device_index_pb2.CmsDeviceIndex: ...
    @_builtins.property
    def bypass_part(self) -> _bypass_part_pb2.BypassPart: ...
    @_builtins.property
    def device_common_capabilities(self) -> _containers.RepeatedScalarFieldContainer[_device_common_capabilities_pb2.DeviceCommonCapability.ValueType]: ...
    @_builtins.property
    def self_monitoring_part(self) -> _self_monitoring_part_pb2.SelfMonitoringPart: ...
    def __init__(
        self,
        *,
        device_profile: _device_profile_pb2.DeviceProfile | None = ...,
        device_telemetry: _device_telemetry_pb2.DeviceTelemetry | None = ...,
        device_transmission_power_mode: _device_transmission_power_mode_pb2.DeviceTransmissionPowerMode.ValueType = ...,
        device_malfunctions: _device_malfunctions_pb2.DeviceMalfunctions | None = ...,
        assigned_extender: _assigned_extender_pb2.AssignedExtender | None = ...,
        cms_device_index: _cms_device_index_pb2.CmsDeviceIndex | None = ...,
        bypass_part: _bypass_part_pb2.BypassPart | None = ...,
        device_migration_status: _device_migration_status_pb2.DeviceMigrationStatus.ValueType = ...,
        device_common_capabilities: _abc.Iterable[_device_common_capabilities_pb2.DeviceCommonCapability.ValueType] | None = ...,
        self_monitoring_part: _self_monitoring_part_pb2.SelfMonitoringPart | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["assigned_extender", b"assigned_extender", "bypass_part", b"bypass_part", "cms_device_index", b"cms_device_index", "device_malfunctions", b"device_malfunctions", "device_profile", b"device_profile", "device_telemetry", b"device_telemetry", "self_monitoring_part", b"self_monitoring_part"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["assigned_extender", b"assigned_extender", "bypass_part", b"bypass_part", "cms_device_index", b"cms_device_index", "device_common_capabilities", b"device_common_capabilities", "device_malfunctions", b"device_malfunctions", "device_migration_status", b"device_migration_status", "device_profile", b"device_profile", "device_telemetry", b"device_telemetry", "device_transmission_power_mode", b"device_transmission_power_mode", "self_monitoring_part", b"self_monitoring_part"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CommonJewellerPart: _TypeAlias = CommonJewellerPart  # noqa: Y015
