"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import hub_rfm_pb2 as _hub_rfm_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DeviceFirmwareVersion(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    HUB_RFM_FIELD_NUMBER: _builtins.int
    value: _builtins.str
    hub_rfm: _hub_rfm_pb2.HubRfm.ValueType
    def __init__(
        self,
        *,
        value: _builtins.str = ...,
        hub_rfm: _hub_rfm_pb2.HubRfm.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hub_rfm", b"hub_rfm", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeviceFirmwareVersion: _TypeAlias = DeviceFirmwareVersion  # noqa: Y015
