"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels import object_type_pb2 as _object_type_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DeviceCommandBrightnessRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _BrightnessType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _BrightnessTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DeviceCommandBrightnessRequest._BrightnessType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        BRIGHTNESS_TYPE_UNSPECIFIED: DeviceCommandBrightnessRequest._BrightnessType.ValueType  # 0
        BRIGHTNESS_TYPE_RELATIVE: DeviceCommandBrightnessRequest._BrightnessType.ValueType  # 1
        BRIGHTNESS_TYPE_ABSOLUTE: DeviceCommandBrightnessRequest._BrightnessType.ValueType  # 2

    class BrightnessType(_BrightnessType, metaclass=_BrightnessTypeEnumTypeWrapper): ...
    BRIGHTNESS_TYPE_UNSPECIFIED: DeviceCommandBrightnessRequest.BrightnessType.ValueType  # 0
    BRIGHTNESS_TYPE_RELATIVE: DeviceCommandBrightnessRequest.BrightnessType.ValueType  # 1
    BRIGHTNESS_TYPE_ABSOLUTE: DeviceCommandBrightnessRequest.BrightnessType.ValueType  # 2

    class _Channel:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ChannelEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DeviceCommandBrightnessRequest._Channel.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        CHANNEL_UNSPECIFIED: DeviceCommandBrightnessRequest._Channel.ValueType  # 0
        CHANNEL_1: DeviceCommandBrightnessRequest._Channel.ValueType  # 1
        CHANNEL_2: DeviceCommandBrightnessRequest._Channel.ValueType  # 2
        CHANNEL_3: DeviceCommandBrightnessRequest._Channel.ValueType  # 3
        CHANNEL_4: DeviceCommandBrightnessRequest._Channel.ValueType  # 4

    class Channel(_Channel, metaclass=_ChannelEnumTypeWrapper): ...
    CHANNEL_UNSPECIFIED: DeviceCommandBrightnessRequest.Channel.ValueType  # 0
    CHANNEL_1: DeviceCommandBrightnessRequest.Channel.ValueType  # 1
    CHANNEL_2: DeviceCommandBrightnessRequest.Channel.ValueType  # 2
    CHANNEL_3: DeviceCommandBrightnessRequest.Channel.ValueType  # 3
    CHANNEL_4: DeviceCommandBrightnessRequest.Channel.ValueType  # 4

    HUB_ID_FIELD_NUMBER: _builtins.int
    DEVICE_ID_FIELD_NUMBER: _builtins.int
    DEVICE_TYPE_FIELD_NUMBER: _builtins.int
    BRIGHTNESS_IN_PERCENTAGE_FIELD_NUMBER: _builtins.int
    CHANNELS_FIELD_NUMBER: _builtins.int
    BRIGHTNESS_TYPE_FIELD_NUMBER: _builtins.int
    hub_id: _builtins.str
    device_id: _builtins.str
    brightness_in_percentage: _builtins.int
    brightness_type: Global___DeviceCommandBrightnessRequest.BrightnessType.ValueType
    @_builtins.property
    def device_type(self) -> _object_type_pb2.ObjectType: ...
    @_builtins.property
    def channels(self) -> _containers.RepeatedScalarFieldContainer[Global___DeviceCommandBrightnessRequest.Channel.ValueType]: ...
    def __init__(
        self,
        *,
        hub_id: _builtins.str = ...,
        device_id: _builtins.str = ...,
        device_type: _object_type_pb2.ObjectType | None = ...,
        brightness_in_percentage: _builtins.int = ...,
        channels: _abc.Iterable[Global___DeviceCommandBrightnessRequest.Channel.ValueType] | None = ...,
        brightness_type: Global___DeviceCommandBrightnessRequest.BrightnessType.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["device_type", b"device_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["brightness_in_percentage", b"brightness_in_percentage", "brightness_type", b"brightness_type", "channels", b"channels", "device_id", b"device_id", "device_type", b"device_type", "hub_id", b"hub_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeviceCommandBrightnessRequest: _TypeAlias = DeviceCommandBrightnessRequest  # noqa: Y015
