"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from v3.mobilegwsvc.commonmodels.response import response_pb2 as _response_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DeviceCommandRadioTestStopResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Failure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        BAD_REQUEST_FIELD_NUMBER: _builtins.int
        PERMISSION_DENIED_FIELD_NUMBER: _builtins.int
        HUB_WRONG_STATE_FIELD_NUMBER: _builtins.int
        HUB_OFFLINE_FIELD_NUMBER: _builtins.int
        TIMEOUT_FIELD_NUMBER: _builtins.int
        HUB_BUSY_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def bad_request(self) -> _response_pb2.Error: ...
        @_builtins.property
        def permission_denied(self) -> _response_pb2.Error: ...
        @_builtins.property
        def hub_wrong_state(self) -> _response_pb2.HubWrongStateError: ...
        @_builtins.property
        def hub_offline(self) -> _response_pb2.Error: ...
        @_builtins.property
        def timeout(self) -> _response_pb2.Error: ...
        @_builtins.property
        def hub_busy(self) -> _response_pb2.HubBusyError: ...
        def __init__(
            self,
            *,
            bad_request: _response_pb2.Error | None = ...,
            permission_denied: _response_pb2.Error | None = ...,
            hub_wrong_state: _response_pb2.HubWrongStateError | None = ...,
            hub_offline: _response_pb2.Error | None = ...,
            timeout: _response_pb2.Error | None = ...,
            hub_busy: _response_pb2.HubBusyError | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "error", b"error", "hub_busy", b"hub_busy", "hub_offline", b"hub_offline", "hub_wrong_state", b"hub_wrong_state", "permission_denied", b"permission_denied", "timeout", b"timeout"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "error", b"error", "hub_busy", b"hub_busy", "hub_offline", b"hub_offline", "hub_wrong_state", b"hub_wrong_state", "permission_denied", b"permission_denied", "timeout", b"timeout"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_error: _TypeAlias = _typing.Literal["bad_request", "permission_denied", "hub_wrong_state", "hub_offline", "timeout", "hub_busy"]  # noqa: Y015
        _WhichOneofArgType_error: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_error) -> _WhichOneofReturnType_error | None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def success(self) -> _response_pb2.Success: ...
    @_builtins.property
    def failure(self) -> Global___DeviceCommandRadioTestStopResponse.Failure: ...
    def __init__(
        self,
        *,
        success: _response_pb2.Success | None = ...,
        failure: Global___DeviceCommandRadioTestStopResponse.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["success", "failure"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___DeviceCommandRadioTestStopResponse: _TypeAlias = DeviceCommandRadioTestStopResponse  # noqa: Y015
