"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.hub import source_type_pb2 as _source_type_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ActionSourceObject(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    HEX_ID_FIELD_NUMBER: _builtins.int
    OBJECT_NAME_FIELD_NUMBER: _builtins.int
    type: _source_type_pb2.HubNotificationSourceType.ValueType
    hex_id: _builtins.str
    object_name: _builtins.str
    def __init__(
        self,
        *,
        type: _source_type_pb2.HubNotificationSourceType.ValueType = ...,
        hex_id: _builtins.str = ...,
        object_name: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hex_id", b"hex_id", "object_name", b"object_name", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ActionSourceObject: _TypeAlias = ActionSourceObject  # noqa: Y015
