"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AlarmSuppressInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TIMER_DURATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def timer_duration(self) -> _duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        timer_duration: _duration_pb2.Duration | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timer_duration", b"timer_duration"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["timer_duration", b"timer_duration"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AlarmSuppressInfo: _TypeAlias = AlarmSuppressInfo  # noqa: Y015
