"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.hub import wire_input_alarm_type_pb2 as _wire_input_alarm_type_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CustomAlarmTypeInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CUSTOM_ALARM_TYPE_FIELD_NUMBER: _builtins.int
    custom_alarm_type: _wire_input_alarm_type_pb2.CustomAlarmType.ValueType
    def __init__(
        self,
        *,
        custom_alarm_type: _wire_input_alarm_type_pb2.CustomAlarmType.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["custom_alarm_type", b"custom_alarm_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CustomAlarmTypeInfo: _TypeAlias = CustomAlarmTypeInfo  # noqa: Y015
