"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class HubConnectionInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _HubConnectionStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _HubConnectionStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HubConnectionInfo._HubConnectionStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        HUB_CONNECTION_STATUS_UNSPECIFIED: HubConnectionInfo._HubConnectionStatus.ValueType  # 0
        ONLINE: HubConnectionInfo._HubConnectionStatus.ValueType  # 1
        OFFLINE: HubConnectionInfo._HubConnectionStatus.ValueType  # 2

    class HubConnectionStatus(_HubConnectionStatus, metaclass=_HubConnectionStatusEnumTypeWrapper): ...
    HUB_CONNECTION_STATUS_UNSPECIFIED: HubConnectionInfo.HubConnectionStatus.ValueType  # 0
    ONLINE: HubConnectionInfo.HubConnectionStatus.ValueType  # 1
    OFFLINE: HubConnectionInfo.HubConnectionStatus.ValueType  # 2

    ORIGINAL_TIMESTAMP_FIELD_NUMBER: _builtins.int
    HUB_CONNECTION_STATUS_FIELD_NUMBER: _builtins.int
    PARENT_NOTIFICATION_ID_FIELD_NUMBER: _builtins.int
    hub_connection_status: Global___HubConnectionInfo.HubConnectionStatus.ValueType
    parent_notification_id: _builtins.str
    @_builtins.property
    def original_timestamp(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        original_timestamp: _timestamp_pb2.Timestamp | None = ...,
        hub_connection_status: Global___HubConnectionInfo.HubConnectionStatus.ValueType = ...,
        parent_notification_id: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_parent_notification_id", b"_parent_notification_id", "original_timestamp", b"original_timestamp", "parent_notification_id", b"parent_notification_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_parent_notification_id", b"_parent_notification_id", "hub_connection_status", b"hub_connection_status", "original_timestamp", b"original_timestamp", "parent_notification_id", b"parent_notification_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__parent_notification_id: _TypeAlias = _typing.Literal["parent_notification_id"]  # noqa: Y015
    _WhichOneofArgType__parent_notification_id: _TypeAlias = _typing.Literal["_parent_notification_id", b"_parent_notification_id"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__parent_notification_id) -> _WhichOneofReturnType__parent_notification_id | None: ...

Global___HubConnectionInfo: _TypeAlias = HubConnectionInfo  # noqa: Y015
