"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ImageChunk(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class DataChunk(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        BYTES_FIELD_NUMBER: _builtins.int
        bytes: _builtins.bytes
        def __init__(
            self,
            *,
            bytes: _builtins.bytes = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bytes", b"bytes"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LastChunk(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class MetadataEntry(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            KEY_FIELD_NUMBER: _builtins.int
            VALUE_FIELD_NUMBER: _builtins.int
            key: _builtins.str
            value: _builtins.str
            def __init__(
                self,
                *,
                key: _builtins.str = ...,
                value: _builtins.str = ...,
            ) -> None: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        FILE_NAME_FIELD_NUMBER: _builtins.int
        METADATA_FIELD_NUMBER: _builtins.int
        file_name: _builtins.str
        @_builtins.property
        def metadata(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
        def __init__(
            self,
            *,
            file_name: _builtins.str = ...,
            metadata: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["file_name", b"file_name", "metadata", b"metadata"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    DATA_CHUNK_FIELD_NUMBER: _builtins.int
    LAST_CHUNK_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def data_chunk(self) -> Global___ImageChunk.DataChunk: ...
    @_builtins.property
    def last_chunk(self) -> Global___ImageChunk.LastChunk: ...
    def __init__(
        self,
        *,
        data_chunk: Global___ImageChunk.DataChunk | None = ...,
        last_chunk: Global___ImageChunk.LastChunk | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["data_chunk", b"data_chunk", "last_chunk", b"last_chunk", "test_oneof", b"test_oneof"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data_chunk", b"data_chunk", "last_chunk", b"last_chunk", "test_oneof", b"test_oneof"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_test_oneof: _TypeAlias = _typing.Literal["data_chunk", "last_chunk"]  # noqa: Y015
    _WhichOneofArgType_test_oneof: _TypeAlias = _typing.Literal["test_oneof", b"test_oneof"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_test_oneof) -> _WhichOneofReturnType_test_oneof | None: ...

Global___ImageChunk: _TypeAlias = ImageChunk  # noqa: Y015
