"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import wrappers_pb2 as _wrappers_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class PhoneNumber(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NUMBER_FIELD_NUMBER: _builtins.int
    COUNTRY_CODE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    number: _builtins.str
    @_builtins.property
    def country_code(self) -> _wrappers_pb2.StringValue: ...
    @_builtins.property
    def description(self) -> _wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        number: _builtins.str = ...,
        country_code: _wrappers_pb2.StringValue | None = ...,
        description: _wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["country_code", b"country_code", "description", b"description"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["country_code", b"country_code", "description", b"description", "number", b"number"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PhoneNumber: _TypeAlias = PhoneNumber  # noqa: Y015
