"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from systems.ajax.api.mobile.v2.common.response import response_pb2 as _response_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class InviteSpaceMembersRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SPACE_ID_FIELD_NUMBER: _builtins.int
    EMAILS_FIELD_NUMBER: _builtins.int
    space_id: _builtins.str
    @_builtins.property
    def emails(self) -> _containers.RepeatedCompositeFieldContainer[Global___SpaceMemberEmail]: ...
    def __init__(
        self,
        *,
        space_id: _builtins.str = ...,
        emails: _abc.Iterable[Global___SpaceMemberEmail] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["emails", b"emails", "space_id", b"space_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___InviteSpaceMembersRequest: _TypeAlias = InviteSpaceMembersRequest  # noqa: Y015

@_typing.final
class InviteSpaceMembersResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class InviteResult(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        EMAIL_FIELD_NUMBER: _builtins.int
        SUCCESS_FIELD_NUMBER: _builtins.int
        FAILURE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def email(self) -> Global___SpaceMemberEmail: ...
        @_builtins.property
        def success(self) -> _response_pb2.Success: ...
        @_builtins.property
        def failure(self) -> Global___InviteSpaceMembersResponse.Failure: ...
        def __init__(
            self,
            *,
            email: Global___SpaceMemberEmail | None = ...,
            success: _response_pb2.Success | None = ...,
            failure: Global___InviteSpaceMembersResponse.Failure | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["email", b"email", "failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["email", b"email", "failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["success", "failure"]  # noqa: Y015
        _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

    @_typing.final
    class Failure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        BAD_REQUEST_FIELD_NUMBER: _builtins.int
        PERMISSION_DENIED_FIELD_NUMBER: _builtins.int
        SPACE_ARMED_FIELD_NUMBER: _builtins.int
        TOO_MANY_USERS_FIELD_NUMBER: _builtins.int
        ALREADY_EXIST_FIELD_NUMBER: _builtins.int
        PRO_NOT_FOUND_FIELD_NUMBER: _builtins.int
        SPACE_LOCKED_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def bad_request(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def permission_denied(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def space_armed(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def too_many_users(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def already_exist(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def pro_not_found(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def space_locked(self) -> _response_pb2.SpaceLockedError: ...
        def __init__(
            self,
            *,
            bad_request: _response_pb2.DefaultError | None = ...,
            permission_denied: _response_pb2.DefaultError | None = ...,
            space_armed: _response_pb2.DefaultError | None = ...,
            too_many_users: _response_pb2.DefaultError | None = ...,
            already_exist: _response_pb2.DefaultError | None = ...,
            pro_not_found: _response_pb2.DefaultError | None = ...,
            space_locked: _response_pb2.SpaceLockedError | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["already_exist", b"already_exist", "bad_request", b"bad_request", "error", b"error", "permission_denied", b"permission_denied", "pro_not_found", b"pro_not_found", "space_armed", b"space_armed", "space_locked", b"space_locked", "too_many_users", b"too_many_users"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["already_exist", b"already_exist", "bad_request", b"bad_request", "error", b"error", "permission_denied", b"permission_denied", "pro_not_found", b"pro_not_found", "space_armed", b"space_armed", "space_locked", b"space_locked", "too_many_users", b"too_many_users"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_error: _TypeAlias = _typing.Literal["bad_request", "permission_denied", "space_armed", "too_many_users", "already_exist", "pro_not_found", "space_locked"]  # noqa: Y015
        _WhichOneofArgType_error: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_error) -> _WhichOneofReturnType_error | None: ...

    RESULT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def result(self) -> _containers.RepeatedCompositeFieldContainer[Global___InviteSpaceMembersResponse.InviteResult]: ...
    def __init__(
        self,
        *,
        result: _abc.Iterable[Global___InviteSpaceMembersResponse.InviteResult] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___InviteSpaceMembersResponse: _TypeAlias = InviteSpaceMembersResponse  # noqa: Y015

@_typing.final
class SpaceMemberEmail(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PRO_EMAIL_FIELD_NUMBER: _builtins.int
    USER_EMAIL_FIELD_NUMBER: _builtins.int
    pro_email: _builtins.str
    user_email: _builtins.str
    def __init__(
        self,
        *,
        pro_email: _builtins.str = ...,
        user_email: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["email", b"email", "pro_email", b"pro_email", "user_email", b"user_email"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["email", b"email", "pro_email", b"pro_email", "user_email", b"user_email"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_email: _TypeAlias = _typing.Literal["pro_email", "user_email"]  # noqa: Y015
    _WhichOneofArgType_email: _TypeAlias = _typing.Literal["email", b"email"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_email) -> _WhichOneofReturnType_email | None: ...

Global___SpaceMemberEmail: _TypeAlias = SpaceMemberEmail  # noqa: Y015
