"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from v3.mobilegwsvc.commonmodels.company.templates import device_identifier_pb2 as _device_identifier_pb2
from v3.mobilegwsvc.commonmodels.company.templates import device_settings_locator_pb2 as _device_settings_locator_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ApplyCompanyTemplateV2Request(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_SETTINGS_LOCATOR_FIELD_NUMBER: _builtins.int
    SPACE_ID_FIELD_NUMBER: _builtins.int
    DEVICES_FIELD_NUMBER: _builtins.int
    space_id: _builtins.str
    @_builtins.property
    def device_settings_locator(self) -> _device_settings_locator_pb2.DeviceSettingsLocator: ...
    @_builtins.property
    def devices(self) -> _containers.RepeatedCompositeFieldContainer[_device_identifier_pb2.DeviceIdentifier]: ...
    def __init__(
        self,
        *,
        device_settings_locator: _device_settings_locator_pb2.DeviceSettingsLocator | None = ...,
        space_id: _builtins.str = ...,
        devices: _abc.Iterable[_device_identifier_pb2.DeviceIdentifier] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["device_settings_locator", b"device_settings_locator"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_settings_locator", b"device_settings_locator", "devices", b"devices", "space_id", b"space_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ApplyCompanyTemplateV2Request: _TypeAlias = ApplyCompanyTemplateV2Request  # noqa: Y015
