"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from v3.mobilegwsvc.commonmodels.response import response_pb2 as _response_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CancelTemporaryVideoEdgeChannelPermissionsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Success(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @_typing.final
    class Failure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        BAD_REQUEST_FIELD_NUMBER: _builtins.int
        PERMISSION_DENIED_FIELD_NUMBER: _builtins.int
        SPACE_NOT_FOUND_FIELD_NUMBER: _builtins.int
        ASSIGNEE_NOT_FOUND_FIELD_NUMBER: _builtins.int
        SPACE_ARMED_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def bad_request(self) -> _response_pb2.Error: ...
        @_builtins.property
        def permission_denied(self) -> _response_pb2.Error: ...
        @_builtins.property
        def space_not_found(self) -> _response_pb2.Error: ...
        @_builtins.property
        def assignee_not_found(self) -> _response_pb2.Error: ...
        @_builtins.property
        def space_armed(self) -> _response_pb2.Error: ...
        def __init__(
            self,
            *,
            bad_request: _response_pb2.Error | None = ...,
            permission_denied: _response_pb2.Error | None = ...,
            space_not_found: _response_pb2.Error | None = ...,
            assignee_not_found: _response_pb2.Error | None = ...,
            space_armed: _response_pb2.Error | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["assignee_not_found", b"assignee_not_found", "bad_request", b"bad_request", "error", b"error", "permission_denied", b"permission_denied", "space_armed", b"space_armed", "space_not_found", b"space_not_found"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["assignee_not_found", b"assignee_not_found", "bad_request", b"bad_request", "error", b"error", "permission_denied", b"permission_denied", "space_armed", b"space_armed", "space_not_found", b"space_not_found"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_error: _TypeAlias = _typing.Literal["bad_request", "permission_denied", "space_not_found", "assignee_not_found", "space_armed"]  # noqa: Y015
        _WhichOneofArgType_error: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_error) -> _WhichOneofReturnType_error | None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def success(self) -> Global___CancelTemporaryVideoEdgeChannelPermissionsResponse.Success: ...
    @_builtins.property
    def failure(self) -> Global___CancelTemporaryVideoEdgeChannelPermissionsResponse.Failure: ...
    def __init__(
        self,
        *,
        success: Global___CancelTemporaryVideoEdgeChannelPermissionsResponse.Success | None = ...,
        failure: Global___CancelTemporaryVideoEdgeChannelPermissionsResponse.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["success", "failure"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___CancelTemporaryVideoEdgeChannelPermissionsResponse: _TypeAlias = CancelTemporaryVideoEdgeChannelPermissionsResponse  # noqa: Y015
