"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification import space_pb2 as _space_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class OfflineEventCount(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ISALARM_FIELD_NUMBER: _builtins.int
    EVENT_COUNT_FIELD_NUMBER: _builtins.int
    GROUPING_KEY_FIELD_NUMBER: _builtins.int
    HUB_HEX_ID_FIELD_NUMBER: _builtins.int
    SPACE_FIELD_NUMBER: _builtins.int
    isAlarm: _builtins.bool
    event_count: _builtins.int
    grouping_key: _builtins.int
    hub_hex_id: _builtins.str
    @_builtins.property
    def space(self) -> _space_pb2.NotificationSpace: ...
    def __init__(
        self,
        *,
        isAlarm: _builtins.bool = ...,
        event_count: _builtins.int = ...,
        grouping_key: _builtins.int = ...,
        hub_hex_id: _builtins.str = ...,
        space: _space_pb2.NotificationSpace | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["space", b"space"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event_count", b"event_count", "grouping_key", b"grouping_key", "hub_hex_id", b"hub_hex_id", "isAlarm", b"isAlarm", "space", b"space"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___OfflineEventCount: _TypeAlias = OfflineEventCount  # noqa: Y015
