"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.mobile.v2.common.response import response_pb2 as _response_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ApplyForMonitoringWithAccountNumberRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HUB_HEX_ID_FIELD_NUMBER: _builtins.int
    COMPANY_HEX_ID_FIELD_NUMBER: _builtins.int
    ACCOUNT_NUMBER_FIELD_NUMBER: _builtins.int
    hub_hex_id: _builtins.str
    company_hex_id: _builtins.str
    account_number: _builtins.str
    def __init__(
        self,
        *,
        hub_hex_id: _builtins.str = ...,
        company_hex_id: _builtins.str = ...,
        account_number: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["account_number", b"account_number", "company_hex_id", b"company_hex_id", "hub_hex_id", b"hub_hex_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ApplyForMonitoringWithAccountNumberRequest: _TypeAlias = ApplyForMonitoringWithAccountNumberRequest  # noqa: Y015

@_typing.final
class ApplyForMonitoringWithAccountNumberResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Failure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        MESSAGE_FIELD_NUMBER: _builtins.int
        REQUEST_TIMEOUT_FIELD_NUMBER: _builtins.int
        CANNOT_APPLY_ON_LOCKED_HUB_FIELD_NUMBER: _builtins.int
        HUB_USERS_LIMIT_EXCEEDED_FIELD_NUMBER: _builtins.int
        PERMISSION_DENIED_FIELD_NUMBER: _builtins.int
        ACCOUNT_NUMBER_INVALID_FIELD_NUMBER: _builtins.int
        message: _builtins.str
        @_builtins.property
        def request_timeout(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def cannot_apply_on_locked_hub(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def hub_users_limit_exceeded(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def permission_denied(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def account_number_invalid(self) -> _response_pb2.DefaultError: ...
        def __init__(
            self,
            *,
            message: _builtins.str = ...,
            request_timeout: _response_pb2.DefaultError | None = ...,
            cannot_apply_on_locked_hub: _response_pb2.DefaultError | None = ...,
            hub_users_limit_exceeded: _response_pb2.DefaultError | None = ...,
            permission_denied: _response_pb2.DefaultError | None = ...,
            account_number_invalid: _response_pb2.DefaultError | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["account_number_invalid", b"account_number_invalid", "cannot_apply_on_locked_hub", b"cannot_apply_on_locked_hub", "errors", b"errors", "hub_users_limit_exceeded", b"hub_users_limit_exceeded", "permission_denied", b"permission_denied", "request_timeout", b"request_timeout"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["account_number_invalid", b"account_number_invalid", "cannot_apply_on_locked_hub", b"cannot_apply_on_locked_hub", "errors", b"errors", "hub_users_limit_exceeded", b"hub_users_limit_exceeded", "message", b"message", "permission_denied", b"permission_denied", "request_timeout", b"request_timeout"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_errors: _TypeAlias = _typing.Literal["request_timeout", "cannot_apply_on_locked_hub", "hub_users_limit_exceeded", "permission_denied", "account_number_invalid"]  # noqa: Y015
        _WhichOneofArgType_errors: _TypeAlias = _typing.Literal["errors", b"errors"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_errors) -> _WhichOneofReturnType_errors | None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def success(self) -> _response_pb2.Success: ...
    @_builtins.property
    def error(self) -> Global___ApplyForMonitoringWithAccountNumberResponse.Failure: ...
    def __init__(
        self,
        *,
        success: _response_pb2.Success | None = ...,
        error: Global___ApplyForMonitoringWithAccountNumberResponse.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "response", b"response", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "response", b"response", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["success", "error"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___ApplyForMonitoringWithAccountNumberResponse: _TypeAlias = ApplyForMonitoringWithAccountNumberResponse  # noqa: Y015
