"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import empty_pb2 as _empty_pb2
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from systems.ajax.api.mobile.v2.common.response import response_pb2 as _response_pb2
from systems.ajax.api.mobile.v2.common.space import space_locator_pb2 as _space_locator_pb2
from systems.ajax.api.mobile.v2.common.video.videoedge.about import about_pb2 as _about_pb2
from systems.ajax.api.mobile.v2.common.video.videoedge.mediadevice import media_device_pb2 as _media_device_pb2
from systems.ajax.api.mobile.v2.common.video.videoedge.mediadevice.discovering import discovery_address_pb2 as _discovery_address_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DiscoverMediaDevicesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Filter(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        PROTOCOLS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def protocols(self) -> _containers.RepeatedScalarFieldContainer[_media_device_pb2.MediaDeviceProtocol.ValueType]: ...
        def __init__(
            self,
            *,
            protocols: _abc.Iterable[_media_device_pb2.MediaDeviceProtocol.ValueType] | None = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["protocols", b"protocols"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    VIDEO_EDGE_ID_FIELD_NUMBER: _builtins.int
    FILTER_FIELD_NUMBER: _builtins.int
    SPACE_LOCATOR_FIELD_NUMBER: _builtins.int
    video_edge_id: _builtins.str
    @_builtins.property
    def filter(self) -> Global___DiscoverMediaDevicesRequest.Filter: ...
    @_builtins.property
    def space_locator(self) -> _space_locator_pb2.SpaceLocator:
        """[optional] - temporarily for backward compatibility"""

    def __init__(
        self,
        *,
        video_edge_id: _builtins.str = ...,
        filter: Global___DiscoverMediaDevicesRequest.Filter | None = ...,
        space_locator: _space_locator_pb2.SpaceLocator | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["filter", b"filter", "space_locator", b"space_locator"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["filter", b"filter", "space_locator", b"space_locator", "video_edge_id", b"video_edge_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DiscoverMediaDevicesRequest: _TypeAlias = DiscoverMediaDevicesRequest  # noqa: Y015

@_typing.final
class DiscoverMediaDevicesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Success(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        INSTANT_DISCOVERING_RESULT_FIELD_NUMBER: _builtins.int
        DEVICE_ADDED_FIELD_NUMBER: _builtins.int
        DEVICE_REMOVED_FIELD_NUMBER: _builtins.int
        DEVICE_UPDATED_FIELD_NUMBER: _builtins.int
        UNKNOWN_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def instant_discovering_result(self) -> Global___DiscoverMediaDevicesResponse.InstantDiscoveringResult: ...
        @_builtins.property
        def device_added(self) -> Global___DiscoverMediaDevicesResponse.DiscoveredMediaDevice: ...
        @_builtins.property
        def device_removed(self) -> Global___DiscoverMediaDevicesResponse.DiscoveredMediaDevice: ...
        @_builtins.property
        def device_updated(self) -> Global___DiscoverMediaDevicesResponse.DiscoveredMediaDevice: ...
        @_builtins.property
        def unknown(self) -> _empty_pb2.Empty: ...
        def __init__(
            self,
            *,
            instant_discovering_result: Global___DiscoverMediaDevicesResponse.InstantDiscoveringResult | None = ...,
            device_added: Global___DiscoverMediaDevicesResponse.DiscoveredMediaDevice | None = ...,
            device_removed: Global___DiscoverMediaDevicesResponse.DiscoveredMediaDevice | None = ...,
            device_updated: Global___DiscoverMediaDevicesResponse.DiscoveredMediaDevice | None = ...,
            unknown: _empty_pb2.Empty | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["device_added", b"device_added", "device_removed", b"device_removed", "device_updated", b"device_updated", "instant_discovering_result", b"instant_discovering_result", "success_union", b"success_union", "unknown", b"unknown"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["device_added", b"device_added", "device_removed", b"device_removed", "device_updated", b"device_updated", "instant_discovering_result", b"instant_discovering_result", "success_union", b"success_union", "unknown", b"unknown"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_success_union: _TypeAlias = _typing.Literal["instant_discovering_result", "device_added", "device_removed", "device_updated", "unknown"]  # noqa: Y015
        _WhichOneofArgType_success_union: _TypeAlias = _typing.Literal["success_union", b"success_union"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_success_union) -> _WhichOneofReturnType_success_union | None: ...

    @_typing.final
    class InstantDiscoveringResult(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        DEVICES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def devices(self) -> _containers.RepeatedCompositeFieldContainer[Global___DiscoverMediaDevicesResponse.DiscoveredMediaDevice]: ...
        def __init__(
            self,
            *,
            devices: _abc.Iterable[Global___DiscoverMediaDevicesResponse.DiscoveredMediaDevice] | None = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["devices", b"devices"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class DiscoveredMediaDevice(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        UUID_FIELD_NUMBER: _builtins.int
        VENDOR_FIELD_NUMBER: _builtins.int
        MODEL_FIELD_NUMBER: _builtins.int
        ADDRESSES_FIELD_NUMBER: _builtins.int
        ALREADY_ADDED_FIELD_NUMBER: _builtins.int
        NAME_FIELD_NUMBER: _builtins.int
        VIDEO_EDGE_INFO_FIELD_NUMBER: _builtins.int
        uuid: _builtins.str
        vendor: _builtins.str
        model: _builtins.str
        already_added: _builtins.bool
        name: _builtins.str
        @_builtins.property
        def addresses(self) -> _containers.RepeatedCompositeFieldContainer[_discovery_address_pb2.DiscoveryAddress]: ...
        @_builtins.property
        def video_edge_info(self) -> Global___DiscoverMediaDevicesResponse.DiscoveredVideoEdgeInfo:
            """[optional] - if discovered media device is a video edge"""

        def __init__(
            self,
            *,
            uuid: _builtins.str = ...,
            vendor: _builtins.str = ...,
            model: _builtins.str = ...,
            addresses: _abc.Iterable[_discovery_address_pb2.DiscoveryAddress] | None = ...,
            already_added: _builtins.bool = ...,
            name: _builtins.str = ...,
            video_edge_info: Global___DiscoverMediaDevicesResponse.DiscoveredVideoEdgeInfo | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["video_edge_info", b"video_edge_info"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["addresses", b"addresses", "already_added", b"already_added", "model", b"model", "name", b"name", "uuid", b"uuid", "vendor", b"vendor", "video_edge_info", b"video_edge_info"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class DiscoveredVideoEdgeInfo(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        VIDEO_EDGE_ID_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        INSTALLED_FIELD_NUMBER: _builtins.int
        ROOM_ID_FIELD_NUMBER: _builtins.int
        GROUP_ID_FIELD_NUMBER: _builtins.int
        CHANNELS_FIELD_NUMBER: _builtins.int
        COLOR_FIELD_NUMBER: _builtins.int
        video_edge_id: _builtins.str
        type: _about_pb2.About.Type.ValueType
        installed: _builtins.bool
        room_id: _builtins.str
        group_id: _builtins.str
        color: _about_pb2.About.Color.ValueType
        @_builtins.property
        def channels(self) -> _containers.RepeatedCompositeFieldContainer[Global___DiscoverMediaDevicesResponse.AvailableChannel]: ...
        def __init__(
            self,
            *,
            video_edge_id: _builtins.str = ...,
            type: _about_pb2.About.Type.ValueType = ...,
            installed: _builtins.bool = ...,
            room_id: _builtins.str | None = ...,
            group_id: _builtins.str | None = ...,
            channels: _abc.Iterable[Global___DiscoverMediaDevicesResponse.AvailableChannel] | None = ...,
            color: _about_pb2.About.Color.ValueType = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_group_id", b"_group_id", "_room_id", b"_room_id", "group_id", b"group_id", "room_id", b"room_id"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_group_id", b"_group_id", "_room_id", b"_room_id", "channels", b"channels", "color", b"color", "group_id", b"group_id", "installed", b"installed", "room_id", b"room_id", "type", b"type", "video_edge_id", b"video_edge_id"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__group_id: _TypeAlias = _typing.Literal["group_id"]  # noqa: Y015
        _WhichOneofArgType__group_id: _TypeAlias = _typing.Literal["_group_id", b"_group_id"]  # noqa: Y015
        _WhichOneofReturnType__room_id: _TypeAlias = _typing.Literal["room_id"]  # noqa: Y015
        _WhichOneofArgType__room_id: _TypeAlias = _typing.Literal["_room_id", b"_room_id"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__group_id) -> _WhichOneofReturnType__group_id | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__room_id) -> _WhichOneofReturnType__room_id | None: ...

    @_typing.final
    class AvailableChannel(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ID_FIELD_NUMBER: _builtins.int
        id: _builtins.str
        def __init__(
            self,
            *,
            id: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class Failure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        BAD_REQUEST_FIELD_NUMBER: _builtins.int
        PERMISSION_DENIED_FIELD_NUMBER: _builtins.int
        SPACE_ARMED_FIELD_NUMBER: _builtins.int
        VIDEO_EDGE_NOT_FOUND_FIELD_NUMBER: _builtins.int
        VIDEO_EDGE_IS_OFFLINE_FIELD_NUMBER: _builtins.int
        ROLE_ACCESS_REQUIRED_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def bad_request(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def permission_denied(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def space_armed(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def video_edge_not_found(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def video_edge_is_offline(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def role_access_required(self) -> _response_pb2.DefaultError: ...
        def __init__(
            self,
            *,
            bad_request: _response_pb2.DefaultError | None = ...,
            permission_denied: _response_pb2.DefaultError | None = ...,
            space_armed: _response_pb2.DefaultError | None = ...,
            video_edge_not_found: _response_pb2.DefaultError | None = ...,
            video_edge_is_offline: _response_pb2.DefaultError | None = ...,
            role_access_required: _response_pb2.DefaultError | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "error", b"error", "permission_denied", b"permission_denied", "role_access_required", b"role_access_required", "space_armed", b"space_armed", "video_edge_is_offline", b"video_edge_is_offline", "video_edge_not_found", b"video_edge_not_found"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "error", b"error", "permission_denied", b"permission_denied", "role_access_required", b"role_access_required", "space_armed", b"space_armed", "video_edge_is_offline", b"video_edge_is_offline", "video_edge_not_found", b"video_edge_not_found"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_error: _TypeAlias = _typing.Literal["bad_request", "permission_denied", "space_armed", "video_edge_not_found", "video_edge_is_offline", "role_access_required"]  # noqa: Y015
        _WhichOneofArgType_error: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_error) -> _WhichOneofReturnType_error | None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def success(self) -> Global___DiscoverMediaDevicesResponse.Success: ...
    @_builtins.property
    def failure(self) -> Global___DiscoverMediaDevicesResponse.Failure: ...
    def __init__(
        self,
        *,
        success: Global___DiscoverMediaDevicesResponse.Success | None = ...,
        failure: Global___DiscoverMediaDevicesResponse.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["success", "failure"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___DiscoverMediaDevicesResponse: _TypeAlias = DiscoverMediaDevicesResponse  # noqa: Y015
