"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _SpaceMemberRole:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SpaceMemberRoleEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SpaceMemberRole.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SPACE_MEMBER_ROLE_UNSPECIFIED: _SpaceMemberRole.ValueType  # 0
    SPACE_MEMBER_ROLE_USER: _SpaceMemberRole.ValueType  # 1
    SPACE_MEMBER_ROLE_ADMIN: _SpaceMemberRole.ValueType  # 2
    SPACE_MEMBER_ROLE_PRO: _SpaceMemberRole.ValueType  # 3
    SPACE_MEMBER_ROLE_COMPANY: _SpaceMemberRole.ValueType  # 4

class SpaceMemberRole(_SpaceMemberRole, metaclass=_SpaceMemberRoleEnumTypeWrapper): ...

SPACE_MEMBER_ROLE_UNSPECIFIED: SpaceMemberRole.ValueType  # 0
SPACE_MEMBER_ROLE_USER: SpaceMemberRole.ValueType  # 1
SPACE_MEMBER_ROLE_ADMIN: SpaceMemberRole.ValueType  # 2
SPACE_MEMBER_ROLE_PRO: SpaceMemberRole.ValueType  # 3
SPACE_MEMBER_ROLE_COMPANY: SpaceMemberRole.ValueType  # 4
Global___SpaceMemberRole: _TypeAlias = SpaceMemberRole  # noqa: Y015
