"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from systems.ajax.api.mobile.v2.common.response import response_pb2 as _response_pb2
from systems.ajax.api.mobile.v2.common.space import space_locator_pb2 as _space_locator_pb2
from systems.ajax.api.mobile.v2.common.space.device import hub_device_pb2 as _hub_device_pb2
from systems.ajax.api.mobile.v2.common.space.device import smart_lock_device_pb2 as _smart_lock_device_pb2
from systems.ajax.api.mobile.v2.common.space.device import video_edge_channel_pb2 as _video_edge_channel_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AssignDevicesToGroupRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SPACE_LOCATOR_FIELD_NUMBER: _builtins.int
    GROUP_ID_FIELD_NUMBER: _builtins.int
    DEVICES_FIELD_NUMBER: _builtins.int
    group_id: _builtins.str
    @_builtins.property
    def space_locator(self) -> _space_locator_pb2.SpaceLocator: ...
    @_builtins.property
    def devices(self) -> _containers.RepeatedCompositeFieldContainer[Global___DeviceForGroup]: ...
    def __init__(
        self,
        *,
        space_locator: _space_locator_pb2.SpaceLocator | None = ...,
        group_id: _builtins.str = ...,
        devices: _abc.Iterable[Global___DeviceForGroup] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["space_locator", b"space_locator"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["devices", b"devices", "group_id", b"group_id", "space_locator", b"space_locator"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AssignDevicesToGroupRequest: _TypeAlias = AssignDevicesToGroupRequest  # noqa: Y015

@_typing.final
class DeviceForGroup(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HUB_DEVICE_FIELD_NUMBER: _builtins.int
    VIDEO_EDGE_CHANNEL_FIELD_NUMBER: _builtins.int
    SMART_LOCK_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def hub_device(self) -> _hub_device_pb2.HubDevice: ...
    @_builtins.property
    def video_edge_channel(self) -> _video_edge_channel_pb2.VideoEdgeChannel: ...
    @_builtins.property
    def smart_lock(self) -> _smart_lock_device_pb2.SmartLockDevice: ...
    def __init__(
        self,
        *,
        hub_device: _hub_device_pb2.HubDevice | None = ...,
        video_edge_channel: _video_edge_channel_pb2.VideoEdgeChannel | None = ...,
        smart_lock: _smart_lock_device_pb2.SmartLockDevice | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["device", b"device", "hub_device", b"hub_device", "smart_lock", b"smart_lock", "video_edge_channel", b"video_edge_channel"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device", "hub_device", b"hub_device", "smart_lock", b"smart_lock", "video_edge_channel", b"video_edge_channel"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_device: _TypeAlias = _typing.Literal["hub_device", "video_edge_channel", "smart_lock"]  # noqa: Y015
    _WhichOneofArgType_device: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_device) -> _WhichOneofReturnType_device | None: ...

Global___DeviceForGroup: _TypeAlias = DeviceForGroup  # noqa: Y015

@_typing.final
class AssignDevicesToGroupResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Failure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        BAD_REQUEST_FIELD_NUMBER: _builtins.int
        SPACE_NOT_FOUND_FIELD_NUMBER: _builtins.int
        SPACE_ARMED_FIELD_NUMBER: _builtins.int
        PERMISSION_DENIED_FIELD_NUMBER: _builtins.int
        GROUP_NOT_FOUND_FIELD_NUMBER: _builtins.int
        DEVICES_NOT_FOUND_FIELD_NUMBER: _builtins.int
        HUB_OFFLINE_FIELD_NUMBER: _builtins.int
        HUB_BUSY_FIELD_NUMBER: _builtins.int
        HUB_ERROR_FIELD_NUMBER: _builtins.int
        HUB_WRONG_STATE_FIELD_NUMBER: _builtins.int
        SPACE_LOCKED_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def bad_request(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def space_not_found(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def space_armed(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def permission_denied(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def group_not_found(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def devices_not_found(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def hub_offline(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def hub_busy(self) -> _response_pb2.HubBusyError: ...
        @_builtins.property
        def hub_error(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def hub_wrong_state(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def space_locked(self) -> _response_pb2.SpaceLockedError: ...
        def __init__(
            self,
            *,
            bad_request: _response_pb2.DefaultError | None = ...,
            space_not_found: _response_pb2.DefaultError | None = ...,
            space_armed: _response_pb2.DefaultError | None = ...,
            permission_denied: _response_pb2.DefaultError | None = ...,
            group_not_found: _response_pb2.DefaultError | None = ...,
            devices_not_found: _response_pb2.DefaultError | None = ...,
            hub_offline: _response_pb2.DefaultError | None = ...,
            hub_busy: _response_pb2.HubBusyError | None = ...,
            hub_error: _response_pb2.DefaultError | None = ...,
            hub_wrong_state: _response_pb2.DefaultError | None = ...,
            space_locked: _response_pb2.SpaceLockedError | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "devices_not_found", b"devices_not_found", "error", b"error", "group_not_found", b"group_not_found", "hub_busy", b"hub_busy", "hub_error", b"hub_error", "hub_offline", b"hub_offline", "hub_wrong_state", b"hub_wrong_state", "permission_denied", b"permission_denied", "space_armed", b"space_armed", "space_locked", b"space_locked", "space_not_found", b"space_not_found"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "devices_not_found", b"devices_not_found", "error", b"error", "group_not_found", b"group_not_found", "hub_busy", b"hub_busy", "hub_error", b"hub_error", "hub_offline", b"hub_offline", "hub_wrong_state", b"hub_wrong_state", "permission_denied", b"permission_denied", "space_armed", b"space_armed", "space_locked", b"space_locked", "space_not_found", b"space_not_found"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_error: _TypeAlias = _typing.Literal["bad_request", "space_not_found", "space_armed", "permission_denied", "group_not_found", "devices_not_found", "hub_offline", "hub_busy", "hub_error", "hub_wrong_state", "space_locked"]  # noqa: Y015
        _WhichOneofArgType_error: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_error) -> _WhichOneofReturnType_error | None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def success(self) -> _response_pb2.Success: ...
    @_builtins.property
    def failure(self) -> Global___AssignDevicesToGroupResponse.Failure: ...
    def __init__(
        self,
        *,
        success: _response_pb2.Success | None = ...,
        failure: Global___AssignDevicesToGroupResponse.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["success", "failure"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___AssignDevicesToGroupResponse: _TypeAlias = AssignDevicesToGroupResponse  # noqa: Y015
