"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.event.smartlock import qualifier_pb2 as _qualifier_pb2
from systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.smartlock import source_pb2 as _source_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SmartLockNotificationContent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    QUALIFIER_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def qualifier(self) -> _qualifier_pb2.SmartLockEventQualifier: ...
    @_builtins.property
    def source(self) -> _source_pb2.SmartLockNotificationSource: ...
    def __init__(
        self,
        *,
        qualifier: _qualifier_pb2.SmartLockEventQualifier | None = ...,
        source: _source_pb2.SmartLockNotificationSource | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["qualifier", b"qualifier", "source", b"source"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["qualifier", b"qualifier", "source", b"source"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SmartLockNotificationContent: _TypeAlias = SmartLockNotificationContent  # noqa: Y015
