"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _TwoStageArmingMode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _TwoStageArmingModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_TwoStageArmingMode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    TWO_STAGE_ARMING_MODE_UNSPECIFIED: _TwoStageArmingMode.ValueType  # 0
    TWO_STAGE_ARMING_MODE_ENABLED: _TwoStageArmingMode.ValueType  # 1
    TWO_STAGE_ARMING_MODE_DISABLED: _TwoStageArmingMode.ValueType  # 2

class TwoStageArmingMode(_TwoStageArmingMode, metaclass=_TwoStageArmingModeEnumTypeWrapper): ...

TWO_STAGE_ARMING_MODE_UNSPECIFIED: TwoStageArmingMode.ValueType  # 0
TWO_STAGE_ARMING_MODE_ENABLED: TwoStageArmingMode.ValueType  # 1
TWO_STAGE_ARMING_MODE_DISABLED: TwoStageArmingMode.ValueType  # 2
Global___TwoStageArmingMode: _TypeAlias = TwoStageArmingMode  # noqa: Y015
