"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Channel description"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from systems.ajax.api.mobile.v2.common.video import types_pb2 as _types_pb2
from systems.ajax.api.mobile.v2.common.video.videoedge.about import about_pb2 as _about_pb2
from systems.ajax.api.mobile.v2.common.video.videoedge.archive import archive_pb2 as _archive_pb2
from systems.ajax.api.mobile.v2.common.video.videoedge.archive import calendar_pb2 as _calendar_pb2
from systems.ajax.api.mobile.v2.common.video.videoedge.channel.cloudarchive import cloud_archive_pb2 as _cloud_archive_pb2
from systems.ajax.api.mobile.v2.common.video.videoedge.channel.spacesettings import channel_space_settings_pb2 as _channel_space_settings_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

if sys.version_info >= (3, 13):
    from warnings import deprecated as _deprecated
else:
    from typing_extensions import deprecated as _deprecated

DESCRIPTOR: _descriptor.FileDescriptor

class _ChannelState:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ChannelStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ChannelState.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    CS_NONE: _ChannelState.ValueType  # 0
    ONLINE: _ChannelState.ValueType  # 1
    """Channel is working."""
    RECORDING: _ChannelState.ValueType  # 2
    """Channel is recording."""
    HAVE_ARCHIVE: _ChannelState.ValueType  # 3
    """There's archive for this channel available."""
    HAVE_DETECTION: _ChannelState.ValueType  # 4
    """At least one detector have triggered a detection."""
    HAVE_MOTION: _ChannelState.ValueType  # 5
    """Motion detected."""
    HAVE_SOUND: _ChannelState.ValueType  # 6
    """Sound above threshold."""
    HAVE_ALARM: _ChannelState.ValueType  # 7
    """Alarm triggered."""
    HAVE_OBJECTS: _ChannelState.ValueType  # 8
    """Objects detected."""
    FLICKERING: _ChannelState.ValueType  # 9
    """Channel video is flickering due to e.g. sensor day-night switch."""
    HAVE_PIR_MOTION: _ChannelState.ValueType  # 10
    """PIR motion detected."""
    HAVE_RING: _ChannelState.ValueType  # 11
    """RING detected."""

class ChannelState(_ChannelState, metaclass=_ChannelStateEnumTypeWrapper): ...

CS_NONE: ChannelState.ValueType  # 0
ONLINE: ChannelState.ValueType  # 1
"""Channel is working."""
RECORDING: ChannelState.ValueType  # 2
"""Channel is recording."""
HAVE_ARCHIVE: ChannelState.ValueType  # 3
"""There's archive for this channel available."""
HAVE_DETECTION: ChannelState.ValueType  # 4
"""At least one detector have triggered a detection."""
HAVE_MOTION: ChannelState.ValueType  # 5
"""Motion detected."""
HAVE_SOUND: ChannelState.ValueType  # 6
"""Sound above threshold."""
HAVE_ALARM: ChannelState.ValueType  # 7
"""Alarm triggered."""
HAVE_OBJECTS: ChannelState.ValueType  # 8
"""Objects detected."""
FLICKERING: ChannelState.ValueType  # 9
"""Channel video is flickering due to e.g. sensor day-night switch."""
HAVE_PIR_MOTION: ChannelState.ValueType  # 10
"""PIR motion detected."""
HAVE_RING: ChannelState.ValueType  # 11
"""RING detected."""
Global___ChannelState: _TypeAlias = ChannelState  # noqa: Y015

@_typing.final
class Channel(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    GUID_FIELD_NUMBER: _builtins.int
    DEVICE_INFO_FIELD_NUMBER: _builtins.int
    INFO_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    RECORD_MODE_FIELD_NUMBER: _builtins.int
    CHANNEL_PREVIEW_FIELD_NUMBER: _builtins.int
    CALENDAR_FIELD_NUMBER: _builtins.int
    RECORD_POLICY_FIELD_NUMBER: _builtins.int
    ZOMBIE_FIELD_NUMBER: _builtins.int
    CLOUD_ARCHIVE_FIELD_NUMBER: _builtins.int
    SMART_BACKLIGHT_TRIGGER_SETTINGS_FIELD_NUMBER: _builtins.int
    ROOM_ID_FIELD_NUMBER: _builtins.int
    GROUP_ID_FIELD_NUMBER: _builtins.int
    SPACE_SETTINGS_FIELD_NUMBER: _builtins.int
    SOURCE_ALIASES_FIELD_NUMBER: _builtins.int
    guid: _builtins.str
    record_mode: _archive_pb2.RecordMode.ValueType
    record_policy: _archive_pb2.RecordPolicy.ValueType
    zombie: _builtins.bool
    @_builtins.property
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def room_id(self) -> _builtins.str: ...
    @room_id.setter
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def room_id(self, value: _builtins.str) -> None: ...
    @_builtins.property
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def group_id(self) -> _builtins.str: ...
    @group_id.setter
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def group_id(self, value: _builtins.str) -> None: ...
    @_builtins.property
    def device_info(self) -> Global___MediaDeviceInfo:
        """[optional]
        It's only set when this channel maps some channel of a media device.
        If it's not set - it's a zombie channel.
        """

    @_builtins.property
    def info(self) -> Global___ChannelInfo:
        """[optional]"""

    @_builtins.property
    def state(self) -> _containers.RepeatedScalarFieldContainer[Global___ChannelState.ValueType]: ...
    @_builtins.property
    def channel_preview(self) -> Global___ChannelPreview:
        """[optional]"""

    @_builtins.property
    def calendar(self) -> _calendar_pb2.Calendar: ...
    @_builtins.property
    def cloud_archive(self) -> _cloud_archive_pb2.CloudArchive:
        """[optional] set only if this video edge / channel supports cloud archive"""

    @_builtins.property
    def smart_backlight_trigger_settings(self) -> Global___SmartBacklightTriggerSettings: ...
    @_builtins.property
    def space_settings(self) -> _channel_space_settings_pb2.ChannelSpaceSettings:
        """[optional]"""

    @_builtins.property
    def source_aliases(self) -> Global___SourceAliases: ...
    def __init__(
        self,
        *,
        guid: _builtins.str = ...,
        device_info: Global___MediaDeviceInfo | None = ...,
        info: Global___ChannelInfo | None = ...,
        state: _abc.Iterable[Global___ChannelState.ValueType] | None = ...,
        record_mode: _archive_pb2.RecordMode.ValueType = ...,
        channel_preview: Global___ChannelPreview | None = ...,
        calendar: _calendar_pb2.Calendar | None = ...,
        record_policy: _archive_pb2.RecordPolicy.ValueType = ...,
        zombie: _builtins.bool = ...,
        cloud_archive: _cloud_archive_pb2.CloudArchive | None = ...,
        smart_backlight_trigger_settings: Global___SmartBacklightTriggerSettings | None = ...,
        room_id: _builtins.str = ...,
        group_id: _builtins.str = ...,
        space_settings: _channel_space_settings_pb2.ChannelSpaceSettings | None = ...,
        source_aliases: Global___SourceAliases | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["calendar", b"calendar", "channel_preview", b"channel_preview", "cloud_archive", b"cloud_archive", "device_info", b"device_info", "info", b"info", "smart_backlight_trigger_settings", b"smart_backlight_trigger_settings", "source_aliases", b"source_aliases", "space_settings", b"space_settings"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["calendar", b"calendar", "channel_preview", b"channel_preview", "cloud_archive", b"cloud_archive", "device_info", b"device_info", "group_id", b"group_id", "guid", b"guid", "info", b"info", "record_mode", b"record_mode", "record_policy", b"record_policy", "room_id", b"room_id", "smart_backlight_trigger_settings", b"smart_backlight_trigger_settings", "source_aliases", b"source_aliases", "space_settings", b"space_settings", "state", b"state", "zombie", b"zombie"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Channel: _TypeAlias = Channel  # noqa: Y015

@_typing.final
class MediaDeviceInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MEDIA_DEVICE_GUID_FIELD_NUMBER: _builtins.int
    CHANNEL_ID_FIELD_NUMBER: _builtins.int
    media_device_guid: _builtins.str
    channel_id: _builtins.str
    def __init__(
        self,
        *,
        media_device_guid: _builtins.str = ...,
        channel_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel_id", b"channel_id", "media_device_guid", b"media_device_guid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MediaDeviceInfo: _TypeAlias = MediaDeviceInfo  # noqa: Y015

@_typing.final
class ChannelInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ChannelInfo: _TypeAlias = ChannelInfo  # noqa: Y015

@_typing.final
class ChannelPreview(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IMAGE_URL_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    image_url: _builtins.str
    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp:
        """[optional]"""

    def __init__(
        self,
        *,
        image_url: _builtins.str = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "image_url", b"image_url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ChannelPreview: _TypeAlias = ChannelPreview  # noqa: Y015

@_typing.final
class SourceAliases(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SOURCES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def sources(self) -> _containers.RepeatedCompositeFieldContainer[Global___VideoSource]: ...
    def __init__(
        self,
        *,
        sources: _abc.Iterable[Global___VideoSource] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sources", b"sources"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SourceAliases: _TypeAlias = SourceAliases  # noqa: Y015

@_typing.final
class VideoSource(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PRIMARY_SOURCE_FIELD_NUMBER: _builtins.int
    NVR_SOURCE_FIELD_NUMBER: _builtins.int
    CLOUD_ARCHIVE_SOURCE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def primary_source(self) -> Global___PrimarySource: ...
    @_builtins.property
    def nvr_source(self) -> Global___NvrSource: ...
    @_builtins.property
    def cloud_archive_source(self) -> Global___CloudArchiveSource: ...
    def __init__(
        self,
        *,
        primary_source: Global___PrimarySource | None = ...,
        nvr_source: Global___NvrSource | None = ...,
        cloud_archive_source: Global___CloudArchiveSource | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["cloud_archive_source", b"cloud_archive_source", "kind", b"kind", "nvr_source", b"nvr_source", "primary_source", b"primary_source"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cloud_archive_source", b"cloud_archive_source", "kind", b"kind", "nvr_source", b"nvr_source", "primary_source", b"primary_source"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_kind: _TypeAlias = _typing.Literal["primary_source", "nvr_source", "cloud_archive_source"]  # noqa: Y015
    _WhichOneofArgType_kind: _TypeAlias = _typing.Literal["kind", b"kind"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_kind) -> _WhichOneofReturnType_kind | None: ...

Global___VideoSource: _TypeAlias = VideoSource  # noqa: Y015

@_typing.final
class PrimarySource(_message.Message):
    """Primary source is a reference to the real channel on the owning device (for example Ajax camera).
    All other sources are connected to the primary one and serve as its aliases
    """

    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_EDGE_ID_FIELD_NUMBER: _builtins.int
    CHANNEL_ID_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    COLOR_FIELD_NUMBER: _builtins.int
    video_edge_id: _builtins.str
    channel_id: _builtins.str
    type: _about_pb2.About.Type.ValueType
    color: _about_pb2.About.Color.ValueType
    def __init__(
        self,
        *,
        video_edge_id: _builtins.str = ...,
        channel_id: _builtins.str = ...,
        type: _about_pb2.About.Type.ValueType = ...,
        color: _about_pb2.About.Color.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel_id", b"channel_id", "color", b"color", "type", b"type", "video_edge_id", b"video_edge_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PrimarySource: _TypeAlias = PrimarySource  # noqa: Y015

@_typing.final
class NvrSource(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_EDGE_ID_FIELD_NUMBER: _builtins.int
    CHANNEL_ID_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    video_edge_id: _builtins.str
    channel_id: _builtins.str
    type: _about_pb2.About.Type.ValueType
    def __init__(
        self,
        *,
        video_edge_id: _builtins.str = ...,
        channel_id: _builtins.str = ...,
        type: _about_pb2.About.Type.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel_id", b"channel_id", "type", b"type", "video_edge_id", b"video_edge_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___NvrSource: _TypeAlias = NvrSource  # noqa: Y015

@_typing.final
class CloudArchiveSource(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_EDGE_ID_FIELD_NUMBER: _builtins.int
    CHANNEL_ID_FIELD_NUMBER: _builtins.int
    video_edge_id: _builtins.str
    channel_id: _builtins.str
    def __init__(
        self,
        *,
        video_edge_id: _builtins.str = ...,
        channel_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel_id", b"channel_id", "video_edge_id", b"video_edge_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CloudArchiveSource: _TypeAlias = CloudArchiveSource  # noqa: Y015

@_typing.final
class SmartBacklightTriggerTypeSettings(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Motion(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @_typing.final
    class Object(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        OBJECT_CLASS_FIELD_NUMBER: _builtins.int
        object_class: _types_pb2.ObjectClass.ValueType
        def __init__(
            self,
            *,
            object_class: _types_pb2.ObjectClass.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["object_class", b"object_class"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    ENABLED_FIELD_NUMBER: _builtins.int
    MOTION_FIELD_NUMBER: _builtins.int
    OBJECT_FIELD_NUMBER: _builtins.int
    enabled: _builtins.bool
    @_builtins.property
    def motion(self) -> Global___SmartBacklightTriggerTypeSettings.Motion: ...
    @_builtins.property
    def object(self) -> Global___SmartBacklightTriggerTypeSettings.Object: ...
    def __init__(
        self,
        *,
        enabled: _builtins.bool = ...,
        motion: Global___SmartBacklightTriggerTypeSettings.Motion | None = ...,
        object: Global___SmartBacklightTriggerTypeSettings.Object | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["motion", b"motion", "object", b"object", "trigger_union", b"trigger_union"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled", "motion", b"motion", "object", b"object", "trigger_union", b"trigger_union"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_trigger_union: _TypeAlias = _typing.Literal["motion", "object"]  # noqa: Y015
    _WhichOneofArgType_trigger_union: _TypeAlias = _typing.Literal["trigger_union", b"trigger_union"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_trigger_union) -> _WhichOneofReturnType_trigger_union | None: ...

Global___SmartBacklightTriggerTypeSettings: _TypeAlias = SmartBacklightTriggerTypeSettings  # noqa: Y015

@_typing.final
class SmartBacklightTriggerSettings(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SMART_BACKLIGHT_TRIGGER_TYPES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def smart_backlight_trigger_types(self) -> _containers.RepeatedCompositeFieldContainer[Global___SmartBacklightTriggerTypeSettings]: ...
    def __init__(
        self,
        *,
        smart_backlight_trigger_types: _abc.Iterable[Global___SmartBacklightTriggerTypeSettings] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["smart_backlight_trigger_types", b"smart_backlight_trigger_types"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SmartBacklightTriggerSettings: _TypeAlias = SmartBacklightTriggerSettings  # noqa: Y015
