"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels import object_type_pb2 as _object_type_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DeviceCommandSelfTestRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HUB_ID_FIELD_NUMBER: _builtins.int
    DEVICE_ID_FIELD_NUMBER: _builtins.int
    OBJECT_TYPE_FIELD_NUMBER: _builtins.int
    hub_id: _builtins.str
    device_id: _builtins.str
    @_builtins.property
    def object_type(self) -> _object_type_pb2.ObjectType: ...
    def __init__(
        self,
        *,
        hub_id: _builtins.str = ...,
        device_id: _builtins.str = ...,
        object_type: _object_type_pb2.ObjectType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["object_type", b"object_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_id", b"device_id", "hub_id", b"hub_id", "object_type", b"object_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeviceCommandSelfTestRequest: _TypeAlias = DeviceCommandSelfTestRequest  # noqa: Y015
