"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _AccountingNotificationSourceType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _AccountingNotificationSourceTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_AccountingNotificationSourceType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ACCOUNTING_NOTIFICATION_SOURCE_TYPE_UNSPECIFIED: _AccountingNotificationSourceType.ValueType  # 0
    HUB: _AccountingNotificationSourceType.ValueType  # 1
    VIDEO_EDGE: _AccountingNotificationSourceType.ValueType  # 2

class AccountingNotificationSourceType(_AccountingNotificationSourceType, metaclass=_AccountingNotificationSourceTypeEnumTypeWrapper): ...

ACCOUNTING_NOTIFICATION_SOURCE_TYPE_UNSPECIFIED: AccountingNotificationSourceType.ValueType  # 0
HUB: AccountingNotificationSourceType.ValueType  # 1
VIDEO_EDGE: AccountingNotificationSourceType.ValueType  # 2
Global___AccountingNotificationSourceType: _TypeAlias = AccountingNotificationSourceType  # noqa: Y015
