"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.mobile.v2.common.accounting import feature_target_pb2 as _feature_target_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class RestoreTargetRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FEATURE_TARGET_ID_FIELD_NUMBER: _builtins.int
    FEATURE_TARGET_FIELD_NUMBER: _builtins.int
    FEATURE_ID_FIELD_NUMBER: _builtins.int
    PACKAGE_ID_FIELD_NUMBER: _builtins.int
    feature_target_id: _builtins.str
    feature_target: _feature_target_pb2.FeatureTarget.ValueType
    feature_id: _builtins.str
    package_id: _builtins.str
    def __init__(
        self,
        *,
        feature_target_id: _builtins.str = ...,
        feature_target: _feature_target_pb2.FeatureTarget.ValueType = ...,
        feature_id: _builtins.str = ...,
        package_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["feature_id", b"feature_id", "package_id", b"package_id", "service_id", b"service_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["feature_id", b"feature_id", "feature_target", b"feature_target", "feature_target_id", b"feature_target_id", "package_id", b"package_id", "service_id", b"service_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_service_id: _TypeAlias = _typing.Literal["feature_id", "package_id"]  # noqa: Y015
    _WhichOneofArgType_service_id: _TypeAlias = _typing.Literal["service_id", b"service_id"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_service_id) -> _WhichOneofReturnType_service_id | None: ...

Global___RestoreTargetRequest: _TypeAlias = RestoreTargetRequest  # noqa: Y015
