"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from v3.mobilegwsvc.commonmodels.response import response_pb2 as _response_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetSubscriptionManagementUrlResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Success(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SUBSCRIPTION_MANAGEMENT_URL_FIELD_NUMBER: _builtins.int
        REQUEST_ID_FIELD_NUMBER: _builtins.int
        subscription_management_url: _builtins.str
        request_id: _builtins.str
        def __init__(
            self,
            *,
            subscription_management_url: _builtins.str = ...,
            request_id: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["request_id", b"request_id", "subscription_management_url", b"subscription_management_url"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class Failure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ILLEGAL_ARGUMENT_FIELD_NUMBER: _builtins.int
        AVAILABLE_SERVICE_NOT_FOUND_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def illegal_argument(self) -> _response_pb2.Error: ...
        @_builtins.property
        def available_service_not_found(self) -> _response_pb2.Error: ...
        def __init__(
            self,
            *,
            illegal_argument: _response_pb2.Error | None = ...,
            available_service_not_found: _response_pb2.Error | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["available_service_not_found", b"available_service_not_found", "error", b"error", "illegal_argument", b"illegal_argument"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["available_service_not_found", b"available_service_not_found", "error", b"error", "illegal_argument", b"illegal_argument"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_error: _TypeAlias = _typing.Literal["illegal_argument", "available_service_not_found"]  # noqa: Y015
        _WhichOneofArgType_error: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_error) -> _WhichOneofReturnType_error | None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def success(self) -> Global___GetSubscriptionManagementUrlResponse.Success: ...
    @_builtins.property
    def failure(self) -> Global___GetSubscriptionManagementUrlResponse.Failure: ...
    def __init__(
        self,
        *,
        success: Global___GetSubscriptionManagementUrlResponse.Success | None = ...,
        failure: Global___GetSubscriptionManagementUrlResponse.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["success", "failure"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___GetSubscriptionManagementUrlResponse: _TypeAlias = GetSubscriptionManagementUrlResponse  # noqa: Y015
