"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.mobile.v2.common.video.videoedge.archive import archive_pb2 as _archive_pb2
from v3.mobilegwsvc.commonmodels.video import duration_option_pb2 as _duration_option_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SetVideoCloudArchiveRecordSettingsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SPACE_ID_FIELD_NUMBER: _builtins.int
    VIDEO_EDGE_ID_FIELD_NUMBER: _builtins.int
    CHANNEL_ID_FIELD_NUMBER: _builtins.int
    RECORD_MODE_FIELD_NUMBER: _builtins.int
    RECORD_POLICY_FIELD_NUMBER: _builtins.int
    RECORDING_DURATION_FIELD_NUMBER: _builtins.int
    COOLDOWN_INTERVAL_FIELD_NUMBER: _builtins.int
    space_id: _builtins.str
    """[required]"""
    video_edge_id: _builtins.str
    """[required]"""
    channel_id: _builtins.str
    """[required]"""
    record_mode: _archive_pb2.RecordMode.ValueType
    """[required]"""
    record_policy: _archive_pb2.RecordPolicy.ValueType
    """[required]"""
    recording_duration: _duration_option_pb2.DurationOption.ValueType
    """[required] If set, limits the maximum duration of a single recording."""
    cooldown_interval: _duration_option_pb2.DurationOption.ValueType
    """[required] How long after the previous recording is finished will we be ready to record again."""
    def __init__(
        self,
        *,
        space_id: _builtins.str = ...,
        video_edge_id: _builtins.str = ...,
        channel_id: _builtins.str = ...,
        record_mode: _archive_pb2.RecordMode.ValueType = ...,
        record_policy: _archive_pb2.RecordPolicy.ValueType = ...,
        recording_duration: _duration_option_pb2.DurationOption.ValueType = ...,
        cooldown_interval: _duration_option_pb2.DurationOption.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel_id", b"channel_id", "cooldown_interval", b"cooldown_interval", "record_mode", b"record_mode", "record_policy", b"record_policy", "recording_duration", b"recording_duration", "space_id", b"space_id", "video_edge_id", b"video_edge_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetVideoCloudArchiveRecordSettingsRequest: _TypeAlias = SetVideoCloudArchiveRecordSettingsRequest  # noqa: Y015
