"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.mobile.v2.common.hub.device.common import battery_charged_state_pb2 as _battery_charged_state_pb2
from systems.ajax.api.mobile.v2.common.video.videoedge.mcu import chime_pb2 as _chime_pb2
from systems.ajax.api.mobile.v2.common.video.videoedge.mcu import mcu_pb2 as _mcu_pb2
from systems.ajax.api.mobile.v2.common.video.videoedge.mcu import operating_mode_pb2 as _operating_mode_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class McuBase(_message.Message):
    """this model contains solely fields from video-svc w/o enrichment from other services (space-svc/csa)"""

    DESCRIPTOR: _descriptor.Descriptor

    EXTERNAL_POWER_STATE_FIELD_NUMBER: _builtins.int
    MCU_STATE_FIELD_NUMBER: _builtins.int
    OPERATING_MODE_FIELD_NUMBER: _builtins.int
    BATTERY_STATE_FIELD_NUMBER: _builtins.int
    BATTERY_CHARGED_STATE_FIELD_NUMBER: _builtins.int
    CHIME_FIELD_NUMBER: _builtins.int
    BATTERY_TEMPERATURE_STATE_FIELD_NUMBER: _builtins.int
    PIR_MOTION_LED_INDICATION_FIELD_NUMBER: _builtins.int
    RING_BUTTON_BELL_STATE_FIELD_NUMBER: _builtins.int
    CAPABILITIES_FIELD_NUMBER: _builtins.int
    external_power_state: _mcu_pb2.Mcu.ExternalPowerState.ValueType
    mcu_state: _mcu_pb2.Mcu.McuState.ValueType
    operating_mode: _operating_mode_pb2.OperatingMode.ValueType
    battery_state: _mcu_pb2.Mcu.BatteryState.ValueType
    battery_charged_state: _battery_charged_state_pb2.BatteryChargedState.ValueType
    battery_temperature_state: _mcu_pb2.Mcu.BatteryTemperatureState.ValueType
    pir_motion_led_indication: _mcu_pb2.Mcu.PirMotionLedIndication.ValueType
    ring_button_bell_state: _mcu_pb2.Mcu.RingButtonBellState.ValueType
    @_builtins.property
    def chime(self) -> _chime_pb2.Chime: ...
    @_builtins.property
    def capabilities(self) -> _mcu_pb2.Mcu.Capabilities: ...
    def __init__(
        self,
        *,
        external_power_state: _mcu_pb2.Mcu.ExternalPowerState.ValueType = ...,
        mcu_state: _mcu_pb2.Mcu.McuState.ValueType = ...,
        operating_mode: _operating_mode_pb2.OperatingMode.ValueType = ...,
        battery_state: _mcu_pb2.Mcu.BatteryState.ValueType = ...,
        battery_charged_state: _battery_charged_state_pb2.BatteryChargedState.ValueType = ...,
        chime: _chime_pb2.Chime | None = ...,
        battery_temperature_state: _mcu_pb2.Mcu.BatteryTemperatureState.ValueType = ...,
        pir_motion_led_indication: _mcu_pb2.Mcu.PirMotionLedIndication.ValueType = ...,
        ring_button_bell_state: _mcu_pb2.Mcu.RingButtonBellState.ValueType = ...,
        capabilities: _mcu_pb2.Mcu.Capabilities | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["capabilities", b"capabilities", "chime", b"chime"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["battery_charged_state", b"battery_charged_state", "battery_state", b"battery_state", "battery_temperature_state", b"battery_temperature_state", "capabilities", b"capabilities", "chime", b"chime", "external_power_state", b"external_power_state", "mcu_state", b"mcu_state", "operating_mode", b"operating_mode", "pir_motion_led_indication", b"pir_motion_led_indication", "ring_button_bell_state", b"ring_button_bell_state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___McuBase: _TypeAlias = McuBase  # noqa: Y015
