"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Initiator(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Type:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Initiator._Type.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        TYPE_UNSPECIFIED: Initiator._Type.ValueType  # 0
        TYPE_EXTERNAL_USER: Initiator._Type.ValueType  # 1
        TYPE_SPACE_MEMBER: Initiator._Type.ValueType  # 2
        TYPE_SCENARIO: Initiator._Type.ValueType  # 3

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    TYPE_UNSPECIFIED: Initiator.Type.ValueType  # 0
    TYPE_EXTERNAL_USER: Initiator.Type.ValueType  # 1
    TYPE_SPACE_MEMBER: Initiator.Type.ValueType  # 2
    TYPE_SCENARIO: Initiator.Type.ValueType  # 3

    ID_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    type: Global___Initiator.Type.ValueType
    name: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        type: Global___Initiator.Type.ValueType = ...,
        name: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "name", b"name", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Initiator: _TypeAlias = Initiator  # noqa: Y015
