"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.mobile.v2.common.response import response_pb2 as _response_pb2
from systems.ajax.api.mobile.v2.common.space import space_locator_pb2 as _space_locator_pb2
from systems.ajax.api.mobile.v2.common.video.scenario import video_scenario_pb2 as _video_scenario_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SetEnabledScenarioRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCENARIO_ID_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    SPACE_LOCATOR_FIELD_NUMBER: _builtins.int
    scenario_id: _builtins.str
    enabled: _builtins.bool
    @_builtins.property
    def space_locator(self) -> _space_locator_pb2.SpaceLocator:
        """[optional] - temporarily for backward compatibility"""

    def __init__(
        self,
        *,
        scenario_id: _builtins.str = ...,
        enabled: _builtins.bool = ...,
        space_locator: _space_locator_pb2.SpaceLocator | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["space_locator", b"space_locator"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled", "scenario_id", b"scenario_id", "space_locator", b"space_locator"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetEnabledScenarioRequest: _TypeAlias = SetEnabledScenarioRequest  # noqa: Y015

@_typing.final
class SetEnabledScenarioResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Success(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SCENARIO_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def scenario(self) -> _video_scenario_pb2.VideoScenario: ...
        def __init__(
            self,
            *,
            scenario: _video_scenario_pb2.VideoScenario | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["scenario", b"scenario"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["scenario", b"scenario"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class Failure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        BAD_REQUEST_FIELD_NUMBER: _builtins.int
        SPACE_NOT_FOUND_FIELD_NUMBER: _builtins.int
        PERMISSION_DENIED_FIELD_NUMBER: _builtins.int
        SPACE_ARMED_FIELD_NUMBER: _builtins.int
        SCENARIO_NOT_FOUND_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def bad_request(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def space_not_found(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def permission_denied(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def space_armed(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def scenario_not_found(self) -> _response_pb2.DefaultError: ...
        def __init__(
            self,
            *,
            bad_request: _response_pb2.DefaultError | None = ...,
            space_not_found: _response_pb2.DefaultError | None = ...,
            permission_denied: _response_pb2.DefaultError | None = ...,
            space_armed: _response_pb2.DefaultError | None = ...,
            scenario_not_found: _response_pb2.DefaultError | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "error", b"error", "permission_denied", b"permission_denied", "scenario_not_found", b"scenario_not_found", "space_armed", b"space_armed", "space_not_found", b"space_not_found"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "error", b"error", "permission_denied", b"permission_denied", "scenario_not_found", b"scenario_not_found", "space_armed", b"space_armed", "space_not_found", b"space_not_found"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_error: _TypeAlias = _typing.Literal["bad_request", "space_not_found", "permission_denied", "space_armed", "scenario_not_found"]  # noqa: Y015
        _WhichOneofArgType_error: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_error) -> _WhichOneofReturnType_error | None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def success(self) -> Global___SetEnabledScenarioResponse.Success: ...
    @_builtins.property
    def failure(self) -> Global___SetEnabledScenarioResponse.Failure: ...
    def __init__(
        self,
        *,
        success: Global___SetEnabledScenarioResponse.Success | None = ...,
        failure: Global___SetEnabledScenarioResponse.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["success", "failure"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___SetEnabledScenarioResponse: _TypeAlias = SetEnabledScenarioResponse  # noqa: Y015
