"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from v1.common import image_urls_pb2 as _image_urls_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class UserInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FIRST_NAME_FIELD_NUMBER: _builtins.int
    LAST_NAME_FIELD_NUMBER: _builtins.int
    LOCALE_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    PHONE_FIELD_NUMBER: _builtins.int
    IMAGE_URLS_FIELD_NUMBER: _builtins.int
    CLUSTER_USER_ID_FIELD_NUMBER: _builtins.int
    END_USER_AGREEMENT_VERSION_FIELD_NUMBER: _builtins.int
    PRIVACY_POLICY_VERSION_FIELD_NUMBER: _builtins.int
    first_name: _builtins.str
    last_name: _builtins.str
    locale: _builtins.str
    email: _builtins.str
    phone: _builtins.str
    cluster_user_id: _builtins.str
    end_user_agreement_version: _builtins.int
    privacy_policy_version: _builtins.int
    @_builtins.property
    def image_urls(self) -> _image_urls_pb2.ImageUrls: ...
    def __init__(
        self,
        *,
        first_name: _builtins.str = ...,
        last_name: _builtins.str = ...,
        locale: _builtins.str = ...,
        email: _builtins.str = ...,
        phone: _builtins.str = ...,
        image_urls: _image_urls_pb2.ImageUrls | None = ...,
        cluster_user_id: _builtins.str = ...,
        end_user_agreement_version: _builtins.int = ...,
        privacy_policy_version: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["image_urls", b"image_urls"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cluster_user_id", b"cluster_user_id", "email", b"email", "end_user_agreement_version", b"end_user_agreement_version", "first_name", b"first_name", "image_urls", b"image_urls", "last_name", b"last_name", "locale", b"locale", "phone", b"phone", "privacy_policy_version", b"privacy_policy_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UserInfo: _TypeAlias = UserInfo  # noqa: Y015
