"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from v1.media import media_pb2 as _media_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CreateMediaInfoResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INFO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def info(self) -> _media_pb2.Media.Info: ...
    def __init__(
        self,
        *,
        info: _media_pb2.Media.Info | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["info", b"info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["info", b"info"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateMediaInfoResponse: _TypeAlias = CreateMediaInfoResponse  # noqa: Y015
