"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from v1.media import media_pb2 as _media_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class StreamMediaResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MEDIA_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def media(self) -> _containers.RepeatedCompositeFieldContainer[_media_pb2.Media]: ...
    def __init__(
        self,
        *,
        media: _abc.Iterable[_media_pb2.Media] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["media", b"media"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamMediaResponse: _TypeAlias = StreamMediaResponse  # noqa: Y015
