"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.mobile.v2.common.video.videoedge.channel.detection import image_analysis_mode_pb2 as _image_analysis_mode_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SetVideoEdgeMotionDetectionImageAnalysisModeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SPACE_ID_FIELD_NUMBER: _builtins.int
    VIDEO_EDGE_ID_FIELD_NUMBER: _builtins.int
    CHANNEL_ID_FIELD_NUMBER: _builtins.int
    IMAGE_ANALYSIS_MODE_FIELD_NUMBER: _builtins.int
    space_id: _builtins.str
    """[required]"""
    video_edge_id: _builtins.str
    """[required]"""
    channel_id: _builtins.str
    """[required]"""
    image_analysis_mode: _image_analysis_mode_pb2.ImageAnalysisMode.ValueType
    """[required]"""
    def __init__(
        self,
        *,
        space_id: _builtins.str = ...,
        video_edge_id: _builtins.str = ...,
        channel_id: _builtins.str = ...,
        image_analysis_mode: _image_analysis_mode_pb2.ImageAnalysisMode.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel_id", b"channel_id", "image_analysis_mode", b"image_analysis_mode", "space_id", b"space_id", "video_edge_id", b"video_edge_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetVideoEdgeMotionDetectionImageAnalysisModeRequest: _TypeAlias = SetVideoEdgeMotionDetectionImageAnalysisModeRequest  # noqa: Y015
