"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from systems.ajax.api.mobile.v2.common.accounting import accounting_company_pb2 as _accounting_company_pb2
from v3.mobilegwsvc.commonmodels.accounting import enriched_target_info_pb2 as _enriched_target_info_pb2
from v3.mobilegwsvc.commonmodels.accounting import reseller_pb2 as _reseller_pb2
from v3.mobilegwsvc.commonmodels.accounting import service_pb2 as _service_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

if sys.version_info >= (3, 13):
    from warnings import deprecated as _deprecated
else:
    from typing_extensions import deprecated as _deprecated

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AvailableExtraService(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SERVICE_FIELD_NUMBER: _builtins.int
    RESELLERS_FIELD_NUMBER: _builtins.int
    FEATURE_TARGET_INFOS_FIELD_NUMBER: _builtins.int
    RESELLER_INFOS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def service(self) -> _service_pb2.Service: ...
    @_builtins.property
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def resellers(self) -> _containers.RepeatedCompositeFieldContainer[_accounting_company_pb2.AccountingCompany]: ...
    @_builtins.property
    def feature_target_infos(self) -> _containers.RepeatedCompositeFieldContainer[_enriched_target_info_pb2.EnrichedTargetInfo]: ...
    @_builtins.property
    def reseller_infos(self) -> _containers.RepeatedCompositeFieldContainer[_reseller_pb2.Reseller]: ...
    def __init__(
        self,
        *,
        service: _service_pb2.Service | None = ...,
        resellers: _abc.Iterable[_accounting_company_pb2.AccountingCompany] | None = ...,
        feature_target_infos: _abc.Iterable[_enriched_target_info_pb2.EnrichedTargetInfo] | None = ...,
        reseller_infos: _abc.Iterable[_reseller_pb2.Reseller] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["service", b"service"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["feature_target_infos", b"feature_target_infos", "reseller_infos", b"reseller_infos", "resellers", b"resellers", "service", b"service"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AvailableExtraService: _TypeAlias = AvailableExtraService  # noqa: Y015
