"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class OnvifUser(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _OnvifUserRole:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _OnvifUserRoleEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[OnvifUser._OnvifUserRole.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        ONVIF_USER_ROLE_UNSPECIFIED: OnvifUser._OnvifUserRole.ValueType  # 0
        ONVIF_USER_ROLE_ADMIN: OnvifUser._OnvifUserRole.ValueType  # 1
        ONVIF_USER_ROLE_OPERATOR: OnvifUser._OnvifUserRole.ValueType  # 2
        ONVIF_USER_ROLE_USER: OnvifUser._OnvifUserRole.ValueType  # 3

    class OnvifUserRole(_OnvifUserRole, metaclass=_OnvifUserRoleEnumTypeWrapper): ...
    ONVIF_USER_ROLE_UNSPECIFIED: OnvifUser.OnvifUserRole.ValueType  # 0
    ONVIF_USER_ROLE_ADMIN: OnvifUser.OnvifUserRole.ValueType  # 1
    ONVIF_USER_ROLE_OPERATOR: OnvifUser.OnvifUserRole.ValueType  # 2
    ONVIF_USER_ROLE_USER: OnvifUser.OnvifUserRole.ValueType  # 3

    NAME_FIELD_NUMBER: _builtins.int
    ROLE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    role: Global___OnvifUser.OnvifUserRole.ValueType
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        role: Global___OnvifUser.OnvifUserRole.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "role", b"role"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___OnvifUser: _TypeAlias = OnvifUser  # noqa: Y015
