"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _VideoNotificationSourceType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _VideoNotificationSourceTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_VideoNotificationSourceType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    VIDEO_SOURCE_TYPE_UNSPECIFIED: _VideoNotificationSourceType.ValueType  # 0
    VIDEO_EDGE: _VideoNotificationSourceType.ValueType  # 1
    VIDEO_SCENARIO: _VideoNotificationSourceType.ValueType  # 2
    SPACE_MEMBER: _VideoNotificationSourceType.ValueType  # 3
    COMPANY: _VideoNotificationSourceType.ValueType  # 4

class VideoNotificationSourceType(_VideoNotificationSourceType, metaclass=_VideoNotificationSourceTypeEnumTypeWrapper): ...

VIDEO_SOURCE_TYPE_UNSPECIFIED: VideoNotificationSourceType.ValueType  # 0
VIDEO_EDGE: VideoNotificationSourceType.ValueType  # 1
VIDEO_SCENARIO: VideoNotificationSourceType.ValueType  # 2
SPACE_MEMBER: VideoNotificationSourceType.ValueType  # 3
COMPANY: VideoNotificationSourceType.ValueType  # 4
Global___VideoNotificationSourceType: _TypeAlias = VideoNotificationSourceType  # noqa: Y015
