"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class HubFeatures(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _HubFeature:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _HubFeatureEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HubFeatures._HubFeature.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        HUB_FEATURE_UNSPECIFIED: HubFeatures._HubFeature.ValueType  # 0
        HUB_FEATURE_BUKHOOR_MODE: HubFeatures._HubFeature.ValueType  # 1
        HUB_FEATURE_EXIT_DELAY_EVENT: HubFeatures._HubFeature.ValueType  # 2
        HUB_FEATURE_DIMMER_CALIBRATION: HubFeatures._HubFeature.ValueType  # 3
        HUB_FEATURE_MTRF_ARM_PREVENT_TAMPER: HubFeatures._HubFeature.ValueType  # 5
        HUB_FEATURE_IWH_MODE: HubFeatures._HubFeature.ValueType  # 6
        HUB_FEATURE_MTR_2_3_EOL: HubFeatures._HubFeature.ValueType  # 7
        HUB_FEATURE_DIMMER_SCENARIO: HubFeatures._HubFeature.ValueType  # 8
        HUB_FEATURE_PHOD_SCENARIO_BY_ARMING: HubFeatures._HubFeature.ValueType  # 9
        HUB_FEATURE_SIREN_SOUNDING_RESTART_DURING_ALARM: HubFeatures._HubFeature.ValueType  # 10
        HUB_FEATURE_SIRENS_ALARM_RESTRICTION: HubFeatures._HubFeature.ValueType  # 11
        HUB_FEATURE_ARC_ALARM_SETTING: HubFeatures._HubFeature.ValueType  # 12
        HUB_FEATURE_ENTRY_EXIT_ROUTE: HubFeatures._HubFeature.ValueType  # 13
        HUB_FEATURE_SIA_CP_01_KPTF: HubFeatures._HubFeature.ValueType  # 14
        HUB_FEATURE_BISTABLE_SCENARIO_KPTF: HubFeatures._HubFeature.ValueType  # 15
        HUB_FEATURE_WAKE_UP_FROM_BSM_VIA_SMS: HubFeatures._HubFeature.ValueType  # 16
        HUB_FEATURE_WAKE_UP_FROM_BSM_VIA_APPS: HubFeatures._HubFeature.ValueType  # 17
        HUB_FEATURE_EXPANDED_CUSTOM_ALARM_TYPES: HubFeatures._HubFeature.ValueType  # 18
        HUB_FEATURE_KEYPAD_S_PLUS_ONE_TOUCH_SCREEN: HubFeatures._HubFeature.ValueType  # 19
        HUB_FEATURE_KEYPAD_PLUS_ONE_TOUCH_SCREEN: HubFeatures._HubFeature.ValueType  # 20
        HUB_FEATURE_TWO_FACTOR_AUTH_KPTF: HubFeatures._HubFeature.ValueType  # 21
        HUB_FEATURE_NOTIFY_BATTERY_CHARGING_MALFUNCTION: HubFeatures._HubFeature.ValueType  # 22
        HUB_FEATURE_NOTIFY_BATTERY_TEST_FAILED: HubFeatures._HubFeature.ValueType  # 23
        HUB_FEATURE_NOTIFY_MTR_BATTERY_CHARGING_MALFUNCTION: HubFeatures._HubFeature.ValueType  # 24
        HUB_FEATURE_NFC_SUPPORT: HubFeatures._HubFeature.ValueType  # 25
        HUB_FEATURE_SIP_MULTIPLE_COMMUNICATION_CHANNELS: HubFeatures._HubFeature.ValueType  # 26
        HUB_FEATURE_SUPPORTS_WINGS_FOR_STREET_SIRENS: HubFeatures._HubFeature.ValueType  # 27
        HUB_FEATURE_SUPPORTS_KPT_EVENT_SCREEN: HubFeatures._HubFeature.ValueType  # 28
        HUB_FEATURE_SUPPORTS_ALARM_AUDIO_RECORDING: HubFeatures._HubFeature.ValueType  # 29
        HUB_FEATURE_KEYPAD_PANIC_BUTTON_PROTECTION: HubFeatures._HubFeature.ValueType  # 30
        HUB_FEATURE_SIA_CP_01_KPT: HubFeatures._HubFeature.ValueType  # 31
        HUB_FEATURE_BISTABLE_SCENARIO_KPT: HubFeatures._HubFeature.ValueType  # 32
        HUB_FEATURE_TWO_FACTOR_AUTH_KPT: HubFeatures._HubFeature.ValueType  # 33
        HUB_FEATURE_SUPPORTS_DEVICE_LOCATION: HubFeatures._HubFeature.ValueType  # 34
        HUB_FEATURE_DAY_ALARM_ZONE: HubFeatures._HubFeature.ValueType  # 35
        HUB_FEATURE_SCHEDULED_ACCESS: HubFeatures._HubFeature.ValueType  # 36
        HUB_FEATURE_AJAX_SIP: HubFeatures._HubFeature.ValueType  # 37
        HUB_FEATURE_SUPPORTS_KPTF_EVENT_SCREEN: HubFeatures._HubFeature.ValueType  # 38
        HUB_FEATURE_ARC_REPORTING: HubFeatures._HubFeature.ValueType  # 39
        HUB_FEATURE_FW_UPDATE_PERMISSION_NOT_IN_SYSTEM_PERMISSIONS: HubFeatures._HubFeature.ValueType  # 40
        HUB_FEATURE_SUPPORTS_AUDIO_SCENARIOS: HubFeatures._HubFeature.ValueType  # 41
        HUB_FEATURE_SUPPORTS_JOB_SEND_PROTOBUF: HubFeatures._HubFeature.ValueType  # 42
        HUB_FEATURE_SUPPORTS_WALK_TEST: HubFeatures._HubFeature.ValueType  # 43
        HUB_FEATURE_EN54_LANGUAGES_SUPPORTS_ADDITIONAL_LANGUAGE_PACK_1: HubFeatures._HubFeature.ValueType  # 44
        HUB_FEATURE_DOORBELL_INDOORCAM_AS_TRIGGER_FOR_AUTOMATION_SCENARIO: HubFeatures._HubFeature.ValueType  # 45
        HUB_FEATURE_SUPPORTS_ARM_AFTER_SECOND_STAGE_TIMER: HubFeatures._HubFeature.ValueType  # 46
        HUB_FEATURE_SUPPORTS_GSM_ANTENNA: HubFeatures._HubFeature.ValueType  # 47
        HUB_FEATURE_SUPPORTS_JEWELLER_ANTENNA: HubFeatures._HubFeature.ValueType  # 48
        HUB_FEATURE_IGNORE_EXTERNAL_BATTERY_MALFUNCTION_BADGE_TOGGLE: HubFeatures._HubFeature.ValueType  # 50
        HUB_FEATURE_DOORBELL_BUTTON_PRESSED_AS_TRIGGER_FOR_AUTOMATION_SCENARIO: HubFeatures._HubFeature.ValueType  # 51
        HUB_FEATURE_AJAX_RECHARGEABLE_LITHIUM_BATTERY: HubFeatures._HubFeature.ValueType  # 52

    class HubFeature(_HubFeature, metaclass=_HubFeatureEnumTypeWrapper): ...
    HUB_FEATURE_UNSPECIFIED: HubFeatures.HubFeature.ValueType  # 0
    HUB_FEATURE_BUKHOOR_MODE: HubFeatures.HubFeature.ValueType  # 1
    HUB_FEATURE_EXIT_DELAY_EVENT: HubFeatures.HubFeature.ValueType  # 2
    HUB_FEATURE_DIMMER_CALIBRATION: HubFeatures.HubFeature.ValueType  # 3
    HUB_FEATURE_MTRF_ARM_PREVENT_TAMPER: HubFeatures.HubFeature.ValueType  # 5
    HUB_FEATURE_IWH_MODE: HubFeatures.HubFeature.ValueType  # 6
    HUB_FEATURE_MTR_2_3_EOL: HubFeatures.HubFeature.ValueType  # 7
    HUB_FEATURE_DIMMER_SCENARIO: HubFeatures.HubFeature.ValueType  # 8
    HUB_FEATURE_PHOD_SCENARIO_BY_ARMING: HubFeatures.HubFeature.ValueType  # 9
    HUB_FEATURE_SIREN_SOUNDING_RESTART_DURING_ALARM: HubFeatures.HubFeature.ValueType  # 10
    HUB_FEATURE_SIRENS_ALARM_RESTRICTION: HubFeatures.HubFeature.ValueType  # 11
    HUB_FEATURE_ARC_ALARM_SETTING: HubFeatures.HubFeature.ValueType  # 12
    HUB_FEATURE_ENTRY_EXIT_ROUTE: HubFeatures.HubFeature.ValueType  # 13
    HUB_FEATURE_SIA_CP_01_KPTF: HubFeatures.HubFeature.ValueType  # 14
    HUB_FEATURE_BISTABLE_SCENARIO_KPTF: HubFeatures.HubFeature.ValueType  # 15
    HUB_FEATURE_WAKE_UP_FROM_BSM_VIA_SMS: HubFeatures.HubFeature.ValueType  # 16
    HUB_FEATURE_WAKE_UP_FROM_BSM_VIA_APPS: HubFeatures.HubFeature.ValueType  # 17
    HUB_FEATURE_EXPANDED_CUSTOM_ALARM_TYPES: HubFeatures.HubFeature.ValueType  # 18
    HUB_FEATURE_KEYPAD_S_PLUS_ONE_TOUCH_SCREEN: HubFeatures.HubFeature.ValueType  # 19
    HUB_FEATURE_KEYPAD_PLUS_ONE_TOUCH_SCREEN: HubFeatures.HubFeature.ValueType  # 20
    HUB_FEATURE_TWO_FACTOR_AUTH_KPTF: HubFeatures.HubFeature.ValueType  # 21
    HUB_FEATURE_NOTIFY_BATTERY_CHARGING_MALFUNCTION: HubFeatures.HubFeature.ValueType  # 22
    HUB_FEATURE_NOTIFY_BATTERY_TEST_FAILED: HubFeatures.HubFeature.ValueType  # 23
    HUB_FEATURE_NOTIFY_MTR_BATTERY_CHARGING_MALFUNCTION: HubFeatures.HubFeature.ValueType  # 24
    HUB_FEATURE_NFC_SUPPORT: HubFeatures.HubFeature.ValueType  # 25
    HUB_FEATURE_SIP_MULTIPLE_COMMUNICATION_CHANNELS: HubFeatures.HubFeature.ValueType  # 26
    HUB_FEATURE_SUPPORTS_WINGS_FOR_STREET_SIRENS: HubFeatures.HubFeature.ValueType  # 27
    HUB_FEATURE_SUPPORTS_KPT_EVENT_SCREEN: HubFeatures.HubFeature.ValueType  # 28
    HUB_FEATURE_SUPPORTS_ALARM_AUDIO_RECORDING: HubFeatures.HubFeature.ValueType  # 29
    HUB_FEATURE_KEYPAD_PANIC_BUTTON_PROTECTION: HubFeatures.HubFeature.ValueType  # 30
    HUB_FEATURE_SIA_CP_01_KPT: HubFeatures.HubFeature.ValueType  # 31
    HUB_FEATURE_BISTABLE_SCENARIO_KPT: HubFeatures.HubFeature.ValueType  # 32
    HUB_FEATURE_TWO_FACTOR_AUTH_KPT: HubFeatures.HubFeature.ValueType  # 33
    HUB_FEATURE_SUPPORTS_DEVICE_LOCATION: HubFeatures.HubFeature.ValueType  # 34
    HUB_FEATURE_DAY_ALARM_ZONE: HubFeatures.HubFeature.ValueType  # 35
    HUB_FEATURE_SCHEDULED_ACCESS: HubFeatures.HubFeature.ValueType  # 36
    HUB_FEATURE_AJAX_SIP: HubFeatures.HubFeature.ValueType  # 37
    HUB_FEATURE_SUPPORTS_KPTF_EVENT_SCREEN: HubFeatures.HubFeature.ValueType  # 38
    HUB_FEATURE_ARC_REPORTING: HubFeatures.HubFeature.ValueType  # 39
    HUB_FEATURE_FW_UPDATE_PERMISSION_NOT_IN_SYSTEM_PERMISSIONS: HubFeatures.HubFeature.ValueType  # 40
    HUB_FEATURE_SUPPORTS_AUDIO_SCENARIOS: HubFeatures.HubFeature.ValueType  # 41
    HUB_FEATURE_SUPPORTS_JOB_SEND_PROTOBUF: HubFeatures.HubFeature.ValueType  # 42
    HUB_FEATURE_SUPPORTS_WALK_TEST: HubFeatures.HubFeature.ValueType  # 43
    HUB_FEATURE_EN54_LANGUAGES_SUPPORTS_ADDITIONAL_LANGUAGE_PACK_1: HubFeatures.HubFeature.ValueType  # 44
    HUB_FEATURE_DOORBELL_INDOORCAM_AS_TRIGGER_FOR_AUTOMATION_SCENARIO: HubFeatures.HubFeature.ValueType  # 45
    HUB_FEATURE_SUPPORTS_ARM_AFTER_SECOND_STAGE_TIMER: HubFeatures.HubFeature.ValueType  # 46
    HUB_FEATURE_SUPPORTS_GSM_ANTENNA: HubFeatures.HubFeature.ValueType  # 47
    HUB_FEATURE_SUPPORTS_JEWELLER_ANTENNA: HubFeatures.HubFeature.ValueType  # 48
    HUB_FEATURE_IGNORE_EXTERNAL_BATTERY_MALFUNCTION_BADGE_TOGGLE: HubFeatures.HubFeature.ValueType  # 50
    HUB_FEATURE_DOORBELL_BUTTON_PRESSED_AS_TRIGGER_FOR_AUTOMATION_SCENARIO: HubFeatures.HubFeature.ValueType  # 51
    HUB_FEATURE_AJAX_RECHARGEABLE_LITHIUM_BATTERY: HubFeatures.HubFeature.ValueType  # 52

    HUB_FEATURES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def hub_features(self) -> _containers.RepeatedScalarFieldContainer[Global___HubFeatures.HubFeature.ValueType]: ...
    def __init__(
        self,
        *,
        hub_features: _abc.Iterable[Global___HubFeatures.HubFeature.ValueType] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hub_features", b"hub_features"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HubFeatures: _TypeAlias = HubFeatures  # noqa: Y015
