"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Stub for google/type/datetime.proto
The real definition is in github.com/googleapis/googleapis
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DateTime(_message.Message):
    """Stub DateTime message"""

    DESCRIPTOR: _descriptor.Descriptor

    YEAR_FIELD_NUMBER: _builtins.int
    MONTH_FIELD_NUMBER: _builtins.int
    DAY_FIELD_NUMBER: _builtins.int
    HOURS_FIELD_NUMBER: _builtins.int
    MINUTES_FIELD_NUMBER: _builtins.int
    SECONDS_FIELD_NUMBER: _builtins.int
    NANOS_FIELD_NUMBER: _builtins.int
    year: _builtins.int
    month: _builtins.int
    day: _builtins.int
    hours: _builtins.int
    minutes: _builtins.int
    seconds: _builtins.int
    nanos: _builtins.int
    def __init__(
        self,
        *,
        year: _builtins.int = ...,
        month: _builtins.int = ...,
        day: _builtins.int = ...,
        hours: _builtins.int = ...,
        minutes: _builtins.int = ...,
        seconds: _builtins.int = ...,
        nanos: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["day", b"day", "hours", b"hours", "minutes", b"minutes", "month", b"month", "nanos", b"nanos", "seconds", b"seconds", "year", b"year"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DateTime: _TypeAlias = DateTime  # noqa: Y015

@_typing.final
class TimeZone(_message.Message):
    """Stub TimeZone message"""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    version: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        version: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TimeZone: _TypeAlias = TimeZone  # noqa: Y015
