"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.mobile.v2.common.image import image_pb2 as _image_pb2
from systems.ajax.api.mobile.v2.common.space.company import space_monitoring_company_pb2 as _space_monitoring_company_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class BillingCompany(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COMPANY_LOGO_FIELD_NUMBER: _builtins.int
    COMPANY_NAME_FIELD_NUMBER: _builtins.int
    COMPANY_BILLING_INFO_FIELD_NUMBER: _builtins.int
    company_name: _builtins.str
    @_builtins.property
    def company_logo(self) -> _image_pb2.Images: ...
    @_builtins.property
    def company_billing_info(self) -> _space_monitoring_company_pb2.SpaceMonitoringCompany.CompanyBillingInfo: ...
    def __init__(
        self,
        *,
        company_logo: _image_pb2.Images | None = ...,
        company_name: _builtins.str = ...,
        company_billing_info: _space_monitoring_company_pb2.SpaceMonitoringCompany.CompanyBillingInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["company_billing_info", b"company_billing_info", "company_logo", b"company_logo"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["company_billing_info", b"company_billing_info", "company_logo", b"company_logo", "company_name", b"company_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BillingCompany: _TypeAlias = BillingCompany  # noqa: Y015
