"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.mobile.v2.common.response import response_pb2 as _response_pb2
from systems.ajax.api.mobile.v2.common.space import space_locator_pb2 as _space_locator_pb2
from systems.ajax.api.mobile.v2.common.video.videoedge.channel.detection import detection_settings_pb2 as _detection_settings_pb2
from systems.ajax.api.mobile.v2.common.video.videoedge.channel.detection import detector_locator_pb2 as _detector_locator_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

if sys.version_info >= (3, 13):
    from warnings import deprecated as _deprecated
else:
    from typing_extensions import deprecated as _deprecated

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SetDetectorEnabledRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_EDGE_ID_FIELD_NUMBER: _builtins.int
    DETECTOR_ID_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    SPACE_LOCATOR_FIELD_NUMBER: _builtins.int
    DETECTOR_LOCATOR_FIELD_NUMBER: _builtins.int
    video_edge_id: _builtins.str
    """[required]"""
    @_builtins.property
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def detector_id(self) -> _builtins.str:
        """Use `detector_locator` instead"""

    @detector_id.setter
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def detector_id(self, value: _builtins.str) -> None:
        """Use `detector_locator` instead"""

    enabled: _builtins.bool
    """[required]"""
    @_builtins.property
    def space_locator(self) -> _space_locator_pb2.SpaceLocator:
        """[optional] - will become required once the client apps are adjusted accordingly"""

    @_builtins.property
    def detector_locator(self) -> _detector_locator_pb2.DetectorLocator: ...
    def __init__(
        self,
        *,
        video_edge_id: _builtins.str = ...,
        detector_id: _builtins.str = ...,
        enabled: _builtins.bool = ...,
        space_locator: _space_locator_pb2.SpaceLocator | None = ...,
        detector_locator: _detector_locator_pb2.DetectorLocator | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["detector_locator", b"detector_locator", "space_locator", b"space_locator"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["detector_id", b"detector_id", "detector_locator", b"detector_locator", "enabled", b"enabled", "space_locator", b"space_locator", "video_edge_id", b"video_edge_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetDetectorEnabledRequest: _TypeAlias = SetDetectorEnabledRequest  # noqa: Y015

@_typing.final
class SetDetectorEnabledResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Success(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SETTINGS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def settings(self) -> _detection_settings_pb2.DetectionSettings: ...
        def __init__(
            self,
            *,
            settings: _detection_settings_pb2.DetectionSettings | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["settings", b"settings"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["settings", b"settings"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class Failure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        BAD_REQUEST_FIELD_NUMBER: _builtins.int
        VIDEO_EDGE_NOT_FOUND_FIELD_NUMBER: _builtins.int
        PERMISSION_DENIED_FIELD_NUMBER: _builtins.int
        SPACE_ARMED_FIELD_NUMBER: _builtins.int
        DETECTOR_NOT_FOUND_FIELD_NUMBER: _builtins.int
        VIDEO_EDGE_IS_OFFLINE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def bad_request(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def video_edge_not_found(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def permission_denied(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def space_armed(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def detector_not_found(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def video_edge_is_offline(self) -> _response_pb2.DefaultError: ...
        def __init__(
            self,
            *,
            bad_request: _response_pb2.DefaultError | None = ...,
            video_edge_not_found: _response_pb2.DefaultError | None = ...,
            permission_denied: _response_pb2.DefaultError | None = ...,
            space_armed: _response_pb2.DefaultError | None = ...,
            detector_not_found: _response_pb2.DefaultError | None = ...,
            video_edge_is_offline: _response_pb2.DefaultError | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "detector_not_found", b"detector_not_found", "error", b"error", "permission_denied", b"permission_denied", "space_armed", b"space_armed", "video_edge_is_offline", b"video_edge_is_offline", "video_edge_not_found", b"video_edge_not_found"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "detector_not_found", b"detector_not_found", "error", b"error", "permission_denied", b"permission_denied", "space_armed", b"space_armed", "video_edge_is_offline", b"video_edge_is_offline", "video_edge_not_found", b"video_edge_not_found"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_error: _TypeAlias = _typing.Literal["bad_request", "video_edge_not_found", "permission_denied", "space_armed", "detector_not_found", "video_edge_is_offline"]  # noqa: Y015
        _WhichOneofArgType_error: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_error) -> _WhichOneofReturnType_error | None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def success(self) -> Global___SetDetectorEnabledResponse.Success: ...
    @_builtins.property
    def failure(self) -> Global___SetDetectorEnabledResponse.Failure: ...
    def __init__(
        self,
        *,
        success: Global___SetDetectorEnabledResponse.Success | None = ...,
        failure: Global___SetDetectorEnabledResponse.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["success", "failure"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___SetDetectorEnabledResponse: _TypeAlias = SetDetectorEnabledResponse  # noqa: Y015
