"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.protobuf.hub import config_migration_state_pb2 as _config_migration_state_pb2
from systems.ajax.protobuf.hub import lightweight_hub_pb2 as _lightweight_hub_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class HubForMigration(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HUB_FIELD_NUMBER: _builtins.int
    CONFIG_MIGRATION_STATE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def hub(self) -> _lightweight_hub_pb2.LightweightHub: ...
    @_builtins.property
    def config_migration_state(self) -> _config_migration_state_pb2.ConfigMigrationState: ...
    def __init__(
        self,
        *,
        hub: _lightweight_hub_pb2.LightweightHub | None = ...,
        config_migration_state: _config_migration_state_pb2.ConfigMigrationState | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config_migration_state", b"config_migration_state", "hub", b"hub"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config_migration_state", b"config_migration_state", "hub", b"hub"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HubForMigration: _TypeAlias = HubForMigration  # noqa: Y015
