"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from systems.ajax.api.mobile.v2.common.accounting import feature_target_pb2 as _feature_target_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ActivateServicesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ServiceToActivate(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        FEATURE_ID_FIELD_NUMBER: _builtins.int
        PACKAGE_ID_FIELD_NUMBER: _builtins.int
        feature_id: _builtins.str
        package_id: _builtins.str
        def __init__(
            self,
            *,
            feature_id: _builtins.str = ...,
            package_id: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["feature_id", b"feature_id", "package_id", b"package_id", "service_id", b"service_id"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["feature_id", b"feature_id", "package_id", b"package_id", "service_id", b"service_id"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_service_id: _TypeAlias = _typing.Literal["feature_id", "package_id"]  # noqa: Y015
        _WhichOneofArgType_service_id: _TypeAlias = _typing.Literal["service_id", b"service_id"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_service_id) -> _WhichOneofReturnType_service_id | None: ...

    FEATURE_TARGET_ID_FIELD_NUMBER: _builtins.int
    FEATURE_TARGET_FIELD_NUMBER: _builtins.int
    SERVICE_TO_ACTIVATE_FIELD_NUMBER: _builtins.int
    RESELLER_ID_FIELD_NUMBER: _builtins.int
    AGREEMENT_VERSION_FIELD_NUMBER: _builtins.int
    feature_target: _feature_target_pb2.FeatureTarget.ValueType
    reseller_id: _builtins.str
    agreement_version: _builtins.str
    @_builtins.property
    def feature_target_id(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def service_to_activate(self) -> _containers.RepeatedCompositeFieldContainer[Global___ActivateServicesRequest.ServiceToActivate]: ...
    def __init__(
        self,
        *,
        feature_target_id: _abc.Iterable[_builtins.str] | None = ...,
        feature_target: _feature_target_pb2.FeatureTarget.ValueType = ...,
        service_to_activate: _abc.Iterable[Global___ActivateServicesRequest.ServiceToActivate] | None = ...,
        reseller_id: _builtins.str = ...,
        agreement_version: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_agreement_version", b"_agreement_version", "agreement_version", b"agreement_version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_agreement_version", b"_agreement_version", "agreement_version", b"agreement_version", "feature_target", b"feature_target", "feature_target_id", b"feature_target_id", "reseller_id", b"reseller_id", "service_to_activate", b"service_to_activate"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__agreement_version: _TypeAlias = _typing.Literal["agreement_version"]  # noqa: Y015
    _WhichOneofArgType__agreement_version: _TypeAlias = _typing.Literal["_agreement_version", b"_agreement_version"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__agreement_version) -> _WhichOneofReturnType__agreement_version | None: ...

Global___ActivateServicesRequest: _TypeAlias = ActivateServicesRequest  # noqa: Y015
