"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DetectorLocator(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _DetectionType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _DetectionTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DetectorLocator._DetectionType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        DETECTION_TYPE_UNSPECIFIED: DetectorLocator._DetectionType.ValueType  # 0
        DETECTION_TYPE_PIR: DetectorLocator._DetectionType.ValueType  # 1
        DETECTION_TYPE_MOTION: DetectorLocator._DetectionType.ValueType  # 2
        DETECTION_TYPE_OBJECT: DetectorLocator._DetectionType.ValueType  # 3

    class DetectionType(_DetectionType, metaclass=_DetectionTypeEnumTypeWrapper): ...
    DETECTION_TYPE_UNSPECIFIED: DetectorLocator.DetectionType.ValueType  # 0
    DETECTION_TYPE_PIR: DetectorLocator.DetectionType.ValueType  # 1
    DETECTION_TYPE_MOTION: DetectorLocator.DetectionType.ValueType  # 2
    DETECTION_TYPE_OBJECT: DetectorLocator.DetectionType.ValueType  # 3

    CHANNEL_ID_FIELD_NUMBER: _builtins.int
    DETECTION_TYPE_FIELD_NUMBER: _builtins.int
    channel_id: _builtins.str
    """[required]"""
    detection_type: Global___DetectorLocator.DetectionType.ValueType
    """[required]"""
    def __init__(
        self,
        *,
        channel_id: _builtins.str = ...,
        detection_type: Global___DetectorLocator.DetectionType.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel_id", b"channel_id", "detection_type", b"detection_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DetectorLocator: _TypeAlias = DetectorLocator  # noqa: Y015
