"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.mobile.v2.common.response import response_pb2 as _response_pb2
from systems.ajax.api.mobile.v2.common.space import space_locator_pb2 as _space_locator_pb2
from systems.ajax.api.mobile.v2.common.video.videoedge.firmware import firmware_version_pb2 as _firmware_version_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class UpdateFirmwareToRecommendedVersionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_EDGE_ID_FIELD_NUMBER: _builtins.int
    ACKNOWLEDGED_FIRMWARE_VERSION_FIELD_NUMBER: _builtins.int
    SPACE_LOCATOR_FIELD_NUMBER: _builtins.int
    video_edge_id: _builtins.str
    @_builtins.property
    def acknowledged_firmware_version(self) -> _firmware_version_pb2.FirmwareVersion: ...
    @_builtins.property
    def space_locator(self) -> _space_locator_pb2.SpaceLocator:
        """[optional] - will become required once the client apps are adjusted accordingly"""

    def __init__(
        self,
        *,
        video_edge_id: _builtins.str = ...,
        acknowledged_firmware_version: _firmware_version_pb2.FirmwareVersion | None = ...,
        space_locator: _space_locator_pb2.SpaceLocator | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["acknowledged_firmware_version", b"acknowledged_firmware_version", "space_locator", b"space_locator"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["acknowledged_firmware_version", b"acknowledged_firmware_version", "space_locator", b"space_locator", "video_edge_id", b"video_edge_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateFirmwareToRecommendedVersionRequest: _TypeAlias = UpdateFirmwareToRecommendedVersionRequest  # noqa: Y015

@_typing.final
class UpdateFirmwareToRecommendedVersionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Failure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        BAD_REQUEST_FIELD_NUMBER: _builtins.int
        PERMISSION_DENIED_FIELD_NUMBER: _builtins.int
        SPACE_ARMED_FIELD_NUMBER: _builtins.int
        VIDEO_EDGE_NOT_FOUND_FIELD_NUMBER: _builtins.int
        FIRMWARE_UPDATE_ALREADY_IN_PROGRESS_FIELD_NUMBER: _builtins.int
        NO_AVAILABLE_FIRMWARE_UPDATE_FIELD_NUMBER: _builtins.int
        ACKNOWLEDGED_FIRMWARE_VERSION_MISMATCH_FIELD_NUMBER: _builtins.int
        VIDEO_EDGE_IS_OFFLINE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def bad_request(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def permission_denied(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def space_armed(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def video_edge_not_found(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def firmware_update_already_in_progress(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def no_available_firmware_update(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def acknowledged_firmware_version_mismatch(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def video_edge_is_offline(self) -> _response_pb2.DefaultError: ...
        def __init__(
            self,
            *,
            bad_request: _response_pb2.DefaultError | None = ...,
            permission_denied: _response_pb2.DefaultError | None = ...,
            space_armed: _response_pb2.DefaultError | None = ...,
            video_edge_not_found: _response_pb2.DefaultError | None = ...,
            firmware_update_already_in_progress: _response_pb2.DefaultError | None = ...,
            no_available_firmware_update: _response_pb2.DefaultError | None = ...,
            acknowledged_firmware_version_mismatch: _response_pb2.DefaultError | None = ...,
            video_edge_is_offline: _response_pb2.DefaultError | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["acknowledged_firmware_version_mismatch", b"acknowledged_firmware_version_mismatch", "bad_request", b"bad_request", "error", b"error", "firmware_update_already_in_progress", b"firmware_update_already_in_progress", "no_available_firmware_update", b"no_available_firmware_update", "permission_denied", b"permission_denied", "space_armed", b"space_armed", "video_edge_is_offline", b"video_edge_is_offline", "video_edge_not_found", b"video_edge_not_found"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["acknowledged_firmware_version_mismatch", b"acknowledged_firmware_version_mismatch", "bad_request", b"bad_request", "error", b"error", "firmware_update_already_in_progress", b"firmware_update_already_in_progress", "no_available_firmware_update", b"no_available_firmware_update", "permission_denied", b"permission_denied", "space_armed", b"space_armed", "video_edge_is_offline", b"video_edge_is_offline", "video_edge_not_found", b"video_edge_not_found"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_error: _TypeAlias = _typing.Literal["bad_request", "permission_denied", "space_armed", "video_edge_not_found", "firmware_update_already_in_progress", "no_available_firmware_update", "acknowledged_firmware_version_mismatch", "video_edge_is_offline"]  # noqa: Y015
        _WhichOneofArgType_error: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_error) -> _WhichOneofReturnType_error | None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def success(self) -> _response_pb2.Success: ...
    @_builtins.property
    def failure(self) -> Global___UpdateFirmwareToRecommendedVersionResponse.Failure: ...
    def __init__(
        self,
        *,
        success: _response_pb2.Success | None = ...,
        failure: Global___UpdateFirmwareToRecommendedVersionResponse.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["success", "failure"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___UpdateFirmwareToRecommendedVersionResponse: _TypeAlias = UpdateFirmwareToRecommendedVersionResponse  # noqa: Y015
