"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.type import datetime_pb2 as _datetime_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _LifeQualityDataDiscreteness:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _LifeQualityDataDiscretenessEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_LifeQualityDataDiscreteness.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    LIFE_QUALITY_DATA_DISCRETENESS_UNSPECIFIED: _LifeQualityDataDiscreteness.ValueType  # 0
    LIFE_QUALITY_DATA_DISCRETENESS_MINUTE: _LifeQualityDataDiscreteness.ValueType  # 1
    LIFE_QUALITY_DATA_DISCRETENESS_HOUR: _LifeQualityDataDiscreteness.ValueType  # 2
    LIFE_QUALITY_DATA_DISCRETENESS_DAY: _LifeQualityDataDiscreteness.ValueType  # 3
    LIFE_QUALITY_DATA_DISCRETENESS_MONTH: _LifeQualityDataDiscreteness.ValueType  # 4

class LifeQualityDataDiscreteness(_LifeQualityDataDiscreteness, metaclass=_LifeQualityDataDiscretenessEnumTypeWrapper): ...

LIFE_QUALITY_DATA_DISCRETENESS_UNSPECIFIED: LifeQualityDataDiscreteness.ValueType  # 0
LIFE_QUALITY_DATA_DISCRETENESS_MINUTE: LifeQualityDataDiscreteness.ValueType  # 1
LIFE_QUALITY_DATA_DISCRETENESS_HOUR: LifeQualityDataDiscreteness.ValueType  # 2
LIFE_QUALITY_DATA_DISCRETENESS_DAY: LifeQualityDataDiscreteness.ValueType  # 3
LIFE_QUALITY_DATA_DISCRETENESS_MONTH: LifeQualityDataDiscreteness.ValueType  # 4
Global___LifeQualityDataDiscreteness: _TypeAlias = LifeQualityDataDiscreteness  # noqa: Y015

@_typing.final
class LifeQualityDataItem(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUE_Y_FIELD_NUMBER: _builtins.int
    VALUE_Y_RANGE_FIELD_NUMBER: _builtins.int
    value_y: _builtins.float
    @_builtins.property
    def value_y_range(self) -> Global___LifeQualityDataRange: ...
    def __init__(
        self,
        *,
        value_y: _builtins.float = ...,
        value_y_range: Global___LifeQualityDataRange | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "value_y", b"value_y", "value_y_range", b"value_y_range"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "value_y", b"value_y", "value_y_range", b"value_y_range"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_data: _TypeAlias = _typing.Literal["value_y", "value_y_range"]  # noqa: Y015
    _WhichOneofArgType_data: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_data) -> _WhichOneofReturnType_data | None: ...

Global___LifeQualityDataItem: _TypeAlias = LifeQualityDataItem  # noqa: Y015

@_typing.final
class LifeQualityDataRange(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MIN_VALUE_Y_FIELD_NUMBER: _builtins.int
    MAX_VALUE_Y_FIELD_NUMBER: _builtins.int
    min_value_y: _builtins.float
    max_value_y: _builtins.float
    def __init__(
        self,
        *,
        min_value_y: _builtins.float = ...,
        max_value_y: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["max_value_y", b"max_value_y", "min_value_y", b"min_value_y"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LifeQualityDataRange: _TypeAlias = LifeQualityDataRange  # noqa: Y015

@_typing.final
class LifeQualityDataResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ValuesTemperatureEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        @_builtins.property
        def value(self) -> Global___LifeQualityDataItem: ...
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: Global___LifeQualityDataItem | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class ValuesHumidityEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        @_builtins.property
        def value(self) -> Global___LifeQualityDataItem: ...
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: Global___LifeQualityDataItem | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class ValuesAirqualityEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        @_builtins.property
        def value(self) -> Global___LifeQualityDataItem: ...
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: Global___LifeQualityDataItem | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    VALUES_TEMPERATURE_FIELD_NUMBER: _builtins.int
    VALUES_HUMIDITY_FIELD_NUMBER: _builtins.int
    VALUES_AIRQUALITY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def values_temperature(self) -> _containers.MessageMap[_builtins.int, Global___LifeQualityDataItem]: ...
    @_builtins.property
    def values_humidity(self) -> _containers.MessageMap[_builtins.int, Global___LifeQualityDataItem]: ...
    @_builtins.property
    def values_airquality(self) -> _containers.MessageMap[_builtins.int, Global___LifeQualityDataItem]: ...
    def __init__(
        self,
        *,
        values_temperature: _abc.Mapping[_builtins.int, Global___LifeQualityDataItem] | None = ...,
        values_humidity: _abc.Mapping[_builtins.int, Global___LifeQualityDataItem] | None = ...,
        values_airquality: _abc.Mapping[_builtins.int, Global___LifeQualityDataItem] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["values_airquality", b"values_airquality", "values_humidity", b"values_humidity", "values_temperature", b"values_temperature"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LifeQualityDataResponse: _TypeAlias = LifeQualityDataResponse  # noqa: Y015

@_typing.final
class LifeQualityDataRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HUB_HEX_ID_FIELD_NUMBER: _builtins.int
    DEVICE_HEX_ID_FIELD_NUMBER: _builtins.int
    DISCRETENESS_FIELD_NUMBER: _builtins.int
    TIME_ZONE_FIELD_NUMBER: _builtins.int
    START_TIMESTAMP_FIELD_NUMBER: _builtins.int
    END_TIMESTAMP_FIELD_NUMBER: _builtins.int
    hub_hex_id: _builtins.str
    device_hex_id: _builtins.str
    discreteness: Global___LifeQualityDataDiscreteness.ValueType
    start_timestamp: _builtins.int
    end_timestamp: _builtins.int
    @_builtins.property
    def time_zone(self) -> _datetime_pb2.TimeZone: ...
    def __init__(
        self,
        *,
        hub_hex_id: _builtins.str = ...,
        device_hex_id: _builtins.str = ...,
        discreteness: Global___LifeQualityDataDiscreteness.ValueType = ...,
        time_zone: _datetime_pb2.TimeZone | None = ...,
        start_timestamp: _builtins.int = ...,
        end_timestamp: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["time_zone", b"time_zone"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_hex_id", b"device_hex_id", "discreteness", b"discreteness", "end_timestamp", b"end_timestamp", "hub_hex_id", b"hub_hex_id", "start_timestamp", b"start_timestamp", "time_zone", b"time_zone"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LifeQualityDataRequest: _TypeAlias = LifeQualityDataRequest  # noqa: Y015

@_typing.final
class StreamLifeQualityDataRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HUB_HEX_ID_FIELD_NUMBER: _builtins.int
    DEVICE_HEX_ID_FIELD_NUMBER: _builtins.int
    DISCRETENESS_FIELD_NUMBER: _builtins.int
    TIME_ZONE_FIELD_NUMBER: _builtins.int
    START_TIMESTAMP_FIELD_NUMBER: _builtins.int
    hub_hex_id: _builtins.str
    device_hex_id: _builtins.str
    discreteness: Global___LifeQualityDataDiscreteness.ValueType
    start_timestamp: _builtins.int
    @_builtins.property
    def time_zone(self) -> _datetime_pb2.TimeZone: ...
    def __init__(
        self,
        *,
        hub_hex_id: _builtins.str = ...,
        device_hex_id: _builtins.str = ...,
        discreteness: Global___LifeQualityDataDiscreteness.ValueType = ...,
        time_zone: _datetime_pb2.TimeZone | None = ...,
        start_timestamp: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["time_zone", b"time_zone"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_hex_id", b"device_hex_id", "discreteness", b"discreteness", "hub_hex_id", b"hub_hex_id", "start_timestamp", b"start_timestamp", "time_zone", b"time_zone"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamLifeQualityDataRequest: _TypeAlias = StreamLifeQualityDataRequest  # noqa: Y015
