"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from systems.ajax.api.mobile.v2.common.accounting import accounting_company_pb2 as _accounting_company_pb2
from v3.mobilegwsvc.commonmodels.accounting import enriched_target_info_pb2 as _enriched_target_info_pb2
from v3.mobilegwsvc.commonmodels.accounting import extra_service_state_pb2 as _extra_service_state_pb2
from v3.mobilegwsvc.commonmodels.accounting import service_pb2 as _service_pb2
from v3.mobilegwsvc.commonmodels.accounting import service_switch_availability_status_pb2 as _service_switch_availability_status_pb2
from v3.mobilegwsvc.commonmodels.response import response_pb2 as _response_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetActiveServicesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Success(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ACTIVE_SERVICES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def active_services(self) -> _containers.RepeatedCompositeFieldContainer[Global___GetActiveServicesResponse.ActiveService]: ...
        def __init__(
            self,
            *,
            active_services: _abc.Iterable[Global___GetActiveServicesResponse.ActiveService] | None = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["active_services", b"active_services"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class ActiveService(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SERVICE_FIELD_NUMBER: _builtins.int
        ACCOUNTING_COMPANY_FIELD_NUMBER: _builtins.int
        SUBSCRIPTION_ID_FIELD_NUMBER: _builtins.int
        SERVICE_SWITCH_AVAILABILITY_STATUS_FIELD_NUMBER: _builtins.int
        ENRICHED_TARGET_INFO_FIELD_NUMBER: _builtins.int
        SERVICE_STATE_FIELD_NUMBER: _builtins.int
        subscription_id: _builtins.str
        service_switch_availability_status: _service_switch_availability_status_pb2.ServiceSwitchAvailabilityStatus.ValueType
        @_builtins.property
        def service(self) -> _service_pb2.Service: ...
        @_builtins.property
        def accounting_company(self) -> _accounting_company_pb2.AccountingCompany: ...
        @_builtins.property
        def enriched_target_info(self) -> _containers.RepeatedCompositeFieldContainer[_enriched_target_info_pb2.EnrichedTargetInfo]: ...
        @_builtins.property
        def service_state(self) -> _extra_service_state_pb2.ExtraServiceState.Active: ...
        def __init__(
            self,
            *,
            service: _service_pb2.Service | None = ...,
            accounting_company: _accounting_company_pb2.AccountingCompany | None = ...,
            subscription_id: _builtins.str = ...,
            service_switch_availability_status: _service_switch_availability_status_pb2.ServiceSwitchAvailabilityStatus.ValueType = ...,
            enriched_target_info: _abc.Iterable[_enriched_target_info_pb2.EnrichedTargetInfo] | None = ...,
            service_state: _extra_service_state_pb2.ExtraServiceState.Active | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["accounting_company", b"accounting_company", "service", b"service", "service_state", b"service_state"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["accounting_company", b"accounting_company", "enriched_target_info", b"enriched_target_info", "service", b"service", "service_state", b"service_state", "service_switch_availability_status", b"service_switch_availability_status", "subscription_id", b"subscription_id"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class Failure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        BAD_REQUEST_FIELD_NUMBER: _builtins.int
        NOT_FOUND_ACTIVE_MANDATORY_SERVICE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def bad_request(self) -> _response_pb2.Error: ...
        @_builtins.property
        def not_found_active_mandatory_service(self) -> _response_pb2.Error: ...
        def __init__(
            self,
            *,
            bad_request: _response_pb2.Error | None = ...,
            not_found_active_mandatory_service: _response_pb2.Error | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "error", b"error", "not_found_active_mandatory_service", b"not_found_active_mandatory_service"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "error", b"error", "not_found_active_mandatory_service", b"not_found_active_mandatory_service"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_error: _TypeAlias = _typing.Literal["bad_request", "not_found_active_mandatory_service"]  # noqa: Y015
        _WhichOneofArgType_error: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_error) -> _WhichOneofReturnType_error | None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def success(self) -> Global___GetActiveServicesResponse.Success: ...
    @_builtins.property
    def failure(self) -> Global___GetActiveServicesResponse.Failure: ...
    def __init__(
        self,
        *,
        success: Global___GetActiveServicesResponse.Success | None = ...,
        failure: Global___GetActiveServicesResponse.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["success", "failure"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___GetActiveServicesResponse: _TypeAlias = GetActiveServicesResponse  # noqa: Y015
