"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DeviceCommandChimesModeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _ChimesStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ChimesStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DeviceCommandChimesModeRequest._ChimesStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        CHIMES_STATUS_UNSPECIFIED: DeviceCommandChimesModeRequest._ChimesStatus.ValueType  # 0
        CHIMES_STATUS_DISABLE: DeviceCommandChimesModeRequest._ChimesStatus.ValueType  # 1
        CHIMES_STATUS_ENABLE: DeviceCommandChimesModeRequest._ChimesStatus.ValueType  # 2

    class ChimesStatus(_ChimesStatus, metaclass=_ChimesStatusEnumTypeWrapper): ...
    CHIMES_STATUS_UNSPECIFIED: DeviceCommandChimesModeRequest.ChimesStatus.ValueType  # 0
    CHIMES_STATUS_DISABLE: DeviceCommandChimesModeRequest.ChimesStatus.ValueType  # 1
    CHIMES_STATUS_ENABLE: DeviceCommandChimesModeRequest.ChimesStatus.ValueType  # 2

    @_typing.final
    class GroupsStatuses(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        class _GroupChimesStatus:
            ValueType = _typing.NewType("ValueType", _builtins.int)
            V: _TypeAlias = ValueType  # noqa: Y015

        class _GroupChimesStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DeviceCommandChimesModeRequest.GroupsStatuses._GroupChimesStatus.ValueType], _builtins.type):
            DESCRIPTOR: _descriptor.EnumDescriptor
            GROUP_CHIMES_STATUS_UNSPECIFIED: DeviceCommandChimesModeRequest.GroupsStatuses._GroupChimesStatus.ValueType  # 0
            GROUP_CHIMES_STATUS_DISABLE: DeviceCommandChimesModeRequest.GroupsStatuses._GroupChimesStatus.ValueType  # 1
            GROUP_CHIMES_STATUS_ENABLE: DeviceCommandChimesModeRequest.GroupsStatuses._GroupChimesStatus.ValueType  # 2

        class GroupChimesStatus(_GroupChimesStatus, metaclass=_GroupChimesStatusEnumTypeWrapper): ...
        GROUP_CHIMES_STATUS_UNSPECIFIED: DeviceCommandChimesModeRequest.GroupsStatuses.GroupChimesStatus.ValueType  # 0
        GROUP_CHIMES_STATUS_DISABLE: DeviceCommandChimesModeRequest.GroupsStatuses.GroupChimesStatus.ValueType  # 1
        GROUP_CHIMES_STATUS_ENABLE: DeviceCommandChimesModeRequest.GroupsStatuses.GroupChimesStatus.ValueType  # 2

        @_typing.final
        class GroupStatus(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            GROUP_ID_FIELD_NUMBER: _builtins.int
            GROUP_CHIMES_STATUS_FIELD_NUMBER: _builtins.int
            group_id: _builtins.str
            group_chimes_status: Global___DeviceCommandChimesModeRequest.GroupsStatuses.GroupChimesStatus.ValueType
            def __init__(
                self,
                *,
                group_id: _builtins.str = ...,
                group_chimes_status: Global___DeviceCommandChimesModeRequest.GroupsStatuses.GroupChimesStatus.ValueType = ...,
            ) -> None: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["group_chimes_status", b"group_chimes_status", "group_id", b"group_id"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        GROUPS_STATUSES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def groups_statuses(self) -> _containers.RepeatedCompositeFieldContainer[Global___DeviceCommandChimesModeRequest.GroupsStatuses.GroupStatus]: ...
        def __init__(
            self,
            *,
            groups_statuses: _abc.Iterable[Global___DeviceCommandChimesModeRequest.GroupsStatuses.GroupStatus] | None = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["groups_statuses", b"groups_statuses"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    HUB_ID_FIELD_NUMBER: _builtins.int
    CHIMES_STATUS_FIELD_NUMBER: _builtins.int
    GROUPS_STATUSES_FIELD_NUMBER: _builtins.int
    hub_id: _builtins.str
    chimes_status: Global___DeviceCommandChimesModeRequest.ChimesStatus.ValueType
    @_builtins.property
    def groups_statuses(self) -> Global___DeviceCommandChimesModeRequest.GroupsStatuses: ...
    def __init__(
        self,
        *,
        hub_id: _builtins.str = ...,
        chimes_status: Global___DeviceCommandChimesModeRequest.ChimesStatus.ValueType = ...,
        groups_statuses: Global___DeviceCommandChimesModeRequest.GroupsStatuses | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["additional_param", b"additional_param", "chimes_status", b"chimes_status", "groups_statuses", b"groups_statuses"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["additional_param", b"additional_param", "chimes_status", b"chimes_status", "groups_statuses", b"groups_statuses", "hub_id", b"hub_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_additional_param: _TypeAlias = _typing.Literal["chimes_status", "groups_statuses"]  # noqa: Y015
    _WhichOneofArgType_additional_param: _TypeAlias = _typing.Literal["additional_param", b"additional_param"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_additional_param) -> _WhichOneofReturnType_additional_param | None: ...

Global___DeviceCommandChimesModeRequest: _TypeAlias = DeviceCommandChimesModeRequest  # noqa: Y015
