"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from v1.responsible_person import responsible_person_pb2 as _responsible_person_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class StreamResponsiblePersonsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESPONSIBLE_PERSONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def responsible_persons(self) -> _containers.RepeatedCompositeFieldContainer[_responsible_person_pb2.ResponsiblePerson]: ...
    def __init__(
        self,
        *,
        responsible_persons: _abc.Iterable[_responsible_person_pb2.ResponsiblePerson] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["responsible_persons", b"responsible_persons"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamResponsiblePersonsResponse: _TypeAlias = StreamResponsiblePersonsResponse  # noqa: Y015
