"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.mobile.v2.common.response import response_pb2 as _response_pb2
from systems.ajax.api.mobile.v2.common.space import space_lite_pb2 as _space_lite_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

if sys.version_info >= (3, 13):
    from warnings import deprecated as _deprecated
else:
    from typing_extensions import deprecated as _deprecated

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CreateSpaceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    IMAGE_ID_FIELD_NUMBER: _builtins.int
    DEVICE_QR_CODE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    image_id: _builtins.str
    device_qr_code: _builtins.str
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        image_id: _builtins.str | None = ...,
        device_qr_code: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_device_qr_code", b"_device_qr_code", "_image_id", b"_image_id", "device_qr_code", b"device_qr_code", "image_id", b"image_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_device_qr_code", b"_device_qr_code", "_image_id", b"_image_id", "device_qr_code", b"device_qr_code", "image_id", b"image_id", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__device_qr_code: _TypeAlias = _typing.Literal["device_qr_code"]  # noqa: Y015
    _WhichOneofArgType__device_qr_code: _TypeAlias = _typing.Literal["_device_qr_code", b"_device_qr_code"]  # noqa: Y015
    _WhichOneofReturnType__image_id: _TypeAlias = _typing.Literal["image_id"]  # noqa: Y015
    _WhichOneofArgType__image_id: _TypeAlias = _typing.Literal["_image_id", b"_image_id"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__device_qr_code) -> _WhichOneofReturnType__device_qr_code | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__image_id) -> _WhichOneofReturnType__image_id | None: ...

Global___CreateSpaceRequest: _TypeAlias = CreateSpaceRequest  # noqa: Y015

@_typing.final
class CreateSpaceResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Success(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SPACE_ID_FIELD_NUMBER: _builtins.int
        LITE_SPACE_FIELD_NUMBER: _builtins.int
        ADD_DEVICE_FAILED_FIELD_NUMBER: _builtins.int
        @_builtins.property
        @_deprecated("""This field has been marked as deprecated using proto field options.""")
        def space_id(self) -> _builtins.str:
            """Should be removed after space aps release"""

        @space_id.setter
        @_deprecated("""This field has been marked as deprecated using proto field options.""")
        def space_id(self, value: _builtins.str) -> None:
            """Should be removed after space aps release"""

        @_builtins.property
        def lite_space(self) -> _space_lite_pb2.LiteSpace: ...
        @_builtins.property
        def add_device_failed(self) -> _response_pb2.AddDeviceError: ...
        def __init__(
            self,
            *,
            space_id: _builtins.str = ...,
            lite_space: _space_lite_pb2.LiteSpace | None = ...,
            add_device_failed: _response_pb2.AddDeviceError | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["add_device_failed", b"add_device_failed", "created_with_warning", b"created_with_warning", "lite_space", b"lite_space"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["add_device_failed", b"add_device_failed", "created_with_warning", b"created_with_warning", "lite_space", b"lite_space", "space_id", b"space_id"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_created_with_warning: _TypeAlias = _typing.Literal["add_device_failed"]  # noqa: Y015
        _WhichOneofArgType_created_with_warning: _TypeAlias = _typing.Literal["created_with_warning", b"created_with_warning"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_created_with_warning) -> _WhichOneofReturnType_created_with_warning | None: ...

    @_typing.final
    class Failure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        BAD_REQUEST_FIELD_NUMBER: _builtins.int
        EMPTY_SPACES_LIMIT_EXCEEDED_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def bad_request(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def empty_spaces_limit_exceeded(self) -> _response_pb2.DefaultError: ...
        def __init__(
            self,
            *,
            bad_request: _response_pb2.DefaultError | None = ...,
            empty_spaces_limit_exceeded: _response_pb2.DefaultError | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "empty_spaces_limit_exceeded", b"empty_spaces_limit_exceeded", "error", b"error"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "empty_spaces_limit_exceeded", b"empty_spaces_limit_exceeded", "error", b"error"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_error: _TypeAlias = _typing.Literal["bad_request", "empty_spaces_limit_exceeded"]  # noqa: Y015
        _WhichOneofArgType_error: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_error) -> _WhichOneofReturnType_error | None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def success(self) -> Global___CreateSpaceResponse.Success: ...
    @_builtins.property
    def failure(self) -> Global___CreateSpaceResponse.Failure: ...
    def __init__(
        self,
        *,
        success: Global___CreateSpaceResponse.Success | None = ...,
        failure: Global___CreateSpaceResponse.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["success", "failure"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___CreateSpaceResponse: _TypeAlias = CreateSpaceResponse  # noqa: Y015
