"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from systems.ajax.api.mobile.v2.common.accounting import extra_services_availability_status_pb2 as _extra_services_availability_status_pb2
from systems.ajax.api.mobile.v2.common.accounting import service_deactivation_pending_status_pb2 as _service_deactivation_pending_status_pb2
from systems.ajax.api.mobile.v2.common.response import response_pb2 as _response_pb2
from systems.ajax.api.mobile.v2.common.space import current_member_pb2 as _current_member_pb2
from systems.ajax.api.mobile.v2.common.space import space_address_pb2 as _space_address_pb2
from systems.ajax.api.mobile.v2.common.space import space_locator_pb2 as _space_locator_pb2
from systems.ajax.api.mobile.v2.common.space import space_pb2 as _space_pb2
from systems.ajax.api.mobile.v2.common.space import space_profile_pb2 as _space_profile_pb2
from systems.ajax.api.mobile.v2.common.space.capability import space_capabilities_pb2 as _space_capabilities_pb2
from systems.ajax.api.mobile.v2.common.space.company import privacy_override_pb2 as _privacy_override_pb2
from systems.ajax.api.mobile.v2.common.space.company import space_installation_company_pb2 as _space_installation_company_pb2
from systems.ajax.api.mobile.v2.common.space.company import space_monitoring_company_pb2 as _space_monitoring_company_pb2
from systems.ajax.api.mobile.v2.common.space.device import standalone_device_pb2 as _standalone_device_pb2
from systems.ajax.api.mobile.v2.common.space.member import pending_member_pb2 as _pending_member_pb2
from systems.ajax.api.mobile.v2.common.space.member import space_member_pb2 as _space_member_pb2
from systems.ajax.api.mobile.v2.common.space.room import room_pb2 as _room_pb2
from systems.ajax.api.mobile.v2.common.space.security import space_security_mode_pb2 as _space_security_mode_pb2
from systems.ajax.api.mobile.v2.common.space.security.group import group_pb2 as _group_pb2
from systems.ajax.api.mobile.v2.common.time import time_zone_pb2 as _time_zone_pb2
from systems.ajax.api.mobile.v2.common.video import video_wall_pb2 as _video_wall_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

if sys.version_info >= (3, 13):
    from warnings import deprecated as _deprecated
else:
    from typing_extensions import deprecated as _deprecated

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class StreamSpaceUpdatesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SPACE_LOCATOR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def space_locator(self) -> _space_locator_pb2.SpaceLocator: ...
    def __init__(
        self,
        *,
        space_locator: _space_locator_pb2.SpaceLocator | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["space_locator", b"space_locator"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["space_locator", b"space_locator"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamSpaceUpdatesRequest: _TypeAlias = StreamSpaceUpdatesRequest  # noqa: Y015

@_typing.final
class StreamSpaceUpdatesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Success(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class Updates(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            UPDATES_FIELD_NUMBER: _builtins.int
            @_builtins.property
            def updates(self) -> _containers.RepeatedCompositeFieldContainer[Global___StreamSpaceUpdatesResponse.Success.Update]: ...
            def __init__(
                self,
                *,
                updates: _abc.Iterable[Global___StreamSpaceUpdatesResponse.Success.Update] | None = ...,
            ) -> None: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["updates", b"updates"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        @_typing.final
        class Update(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            class _SpaceUpdateType:
                ValueType = _typing.NewType("ValueType", _builtins.int)
                V: _TypeAlias = ValueType  # noqa: Y015

            class _SpaceUpdateTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[StreamSpaceUpdatesResponse.Success.Update._SpaceUpdateType.ValueType], _builtins.type):
                DESCRIPTOR: _descriptor.EnumDescriptor
                SPACE_UPDATE_TYPE_UNKNOWN: StreamSpaceUpdatesResponse.Success.Update._SpaceUpdateType.ValueType  # 0
                SPACE_UPDATE_TYPE_ADD: StreamSpaceUpdatesResponse.Success.Update._SpaceUpdateType.ValueType  # 1
                SPACE_UPDATE_TYPE_UPDATE: StreamSpaceUpdatesResponse.Success.Update._SpaceUpdateType.ValueType  # 2
                SPACE_UPDATE_TYPE_REMOVE: StreamSpaceUpdatesResponse.Success.Update._SpaceUpdateType.ValueType  # 3

            class SpaceUpdateType(_SpaceUpdateType, metaclass=_SpaceUpdateTypeEnumTypeWrapper): ...
            SPACE_UPDATE_TYPE_UNKNOWN: StreamSpaceUpdatesResponse.Success.Update.SpaceUpdateType.ValueType  # 0
            SPACE_UPDATE_TYPE_ADD: StreamSpaceUpdatesResponse.Success.Update.SpaceUpdateType.ValueType  # 1
            SPACE_UPDATE_TYPE_UPDATE: StreamSpaceUpdatesResponse.Success.Update.SpaceUpdateType.ValueType  # 2
            SPACE_UPDATE_TYPE_REMOVE: StreamSpaceUpdatesResponse.Success.Update.SpaceUpdateType.ValueType  # 3

            SPACE_ID_FIELD_NUMBER: _builtins.int
            SPACE_UPDATE_TYPE_FIELD_NUMBER: _builtins.int
            CURRENT_MEMBER_FIELD_NUMBER: _builtins.int
            TOTAL_NOTIFICATION_UNREAD_COUNTER_FIELD_NUMBER: _builtins.int
            SECURITY_MODE_FIELD_NUMBER: _builtins.int
            GROUP_FIELD_NUMBER: _builtins.int
            PROFILE_FIELD_NUMBER: _builtins.int
            MEMBER_FIELD_NUMBER: _builtins.int
            ROOM_FIELD_NUMBER: _builtins.int
            DEVICE_FIELD_NUMBER: _builtins.int
            INSTALLATION_COMPANY_FIELD_NUMBER: _builtins.int
            MONITORING_COMPANY_FIELD_NUMBER: _builtins.int
            PRIVACY_OVERRIDE_FIELD_NUMBER: _builtins.int
            TIME_ZONE_ID_FIELD_NUMBER: _builtins.int
            PENDING_MEMBER_FIELD_NUMBER: _builtins.int
            VIDEO_WALL_FIELD_NUMBER: _builtins.int
            ADDRESS_FIELD_NUMBER: _builtins.int
            SERVICE_DEACTIVATION_PENDING_STATUS_FIELD_NUMBER: _builtins.int
            EXTRA_SERVICES_AVAILABILITY_STATUS_FIELD_NUMBER: _builtins.int
            SPACE_CAPABILITIES_FIELD_NUMBER: _builtins.int
            space_id: _builtins.str
            space_update_type: Global___StreamSpaceUpdatesResponse.Success.Update.SpaceUpdateType.ValueType
            total_notification_unread_counter: _builtins.int
            service_deactivation_pending_status: _service_deactivation_pending_status_pb2.ServiceDeactivationPendingStatus.ValueType
            extra_services_availability_status: _extra_services_availability_status_pb2.ExtraServicesAvailabilityStatus.ValueType
            @_builtins.property
            def current_member(self) -> _current_member_pb2.CurrentMember:
                """initiator-level"""

            @_builtins.property
            def security_mode(self) -> _space_security_mode_pb2.SpaceSecurityMode:
                """space-level"""

            @_builtins.property
            def group(self) -> _group_pb2.Group: ...
            @_builtins.property
            def profile(self) -> _space_profile_pb2.SpaceProfile: ...
            @_builtins.property
            @_deprecated("""This field has been marked as deprecated using proto field options.""")
            def member(self) -> _space_member_pb2.SpaceMember:
                """don't send member updates for new apps
                members list deprecated in the space.proto
                """

            @_builtins.property
            def room(self) -> _room_pb2.Room: ...
            @_builtins.property
            def device(self) -> _standalone_device_pb2.StandaloneDevice: ...
            @_builtins.property
            def installation_company(self) -> _space_installation_company_pb2.SpaceInstallationCompany: ...
            @_builtins.property
            def monitoring_company(self) -> _space_monitoring_company_pb2.SpaceMonitoringCompany: ...
            @_builtins.property
            def privacy_override(self) -> _privacy_override_pb2.PrivacyOverride: ...
            @_builtins.property
            def time_zone_id(self) -> _time_zone_pb2.TimeZone: ...
            @_builtins.property
            def pending_member(self) -> _pending_member_pb2.PendingMember: ...
            @_builtins.property
            def video_wall(self) -> _video_wall_pb2.VideoWall: ...
            @_builtins.property
            def address(self) -> _space_address_pb2.SpaceAddress: ...
            @_builtins.property
            def space_capabilities(self) -> _space_capabilities_pb2.SpaceCapabilities: ...
            def __init__(
                self,
                *,
                space_id: _builtins.str = ...,
                space_update_type: Global___StreamSpaceUpdatesResponse.Success.Update.SpaceUpdateType.ValueType = ...,
                current_member: _current_member_pb2.CurrentMember | None = ...,
                total_notification_unread_counter: _builtins.int = ...,
                security_mode: _space_security_mode_pb2.SpaceSecurityMode | None = ...,
                group: _group_pb2.Group | None = ...,
                profile: _space_profile_pb2.SpaceProfile | None = ...,
                member: _space_member_pb2.SpaceMember | None = ...,
                room: _room_pb2.Room | None = ...,
                device: _standalone_device_pb2.StandaloneDevice | None = ...,
                installation_company: _space_installation_company_pb2.SpaceInstallationCompany | None = ...,
                monitoring_company: _space_monitoring_company_pb2.SpaceMonitoringCompany | None = ...,
                privacy_override: _privacy_override_pb2.PrivacyOverride | None = ...,
                time_zone_id: _time_zone_pb2.TimeZone | None = ...,
                pending_member: _pending_member_pb2.PendingMember | None = ...,
                video_wall: _video_wall_pb2.VideoWall | None = ...,
                address: _space_address_pb2.SpaceAddress | None = ...,
                service_deactivation_pending_status: _service_deactivation_pending_status_pb2.ServiceDeactivationPendingStatus.ValueType = ...,
                extra_services_availability_status: _extra_services_availability_status_pb2.ExtraServicesAvailabilityStatus.ValueType = ...,
                space_capabilities: _space_capabilities_pb2.SpaceCapabilities | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "current_member", b"current_member", "device", b"device", "entity", b"entity", "extra_services_availability_status", b"extra_services_availability_status", "group", b"group", "installation_company", b"installation_company", "member", b"member", "monitoring_company", b"monitoring_company", "pending_member", b"pending_member", "privacy_override", b"privacy_override", "profile", b"profile", "room", b"room", "security_mode", b"security_mode", "service_deactivation_pending_status", b"service_deactivation_pending_status", "space_capabilities", b"space_capabilities", "time_zone_id", b"time_zone_id", "total_notification_unread_counter", b"total_notification_unread_counter", "video_wall", b"video_wall"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "current_member", b"current_member", "device", b"device", "entity", b"entity", "extra_services_availability_status", b"extra_services_availability_status", "group", b"group", "installation_company", b"installation_company", "member", b"member", "monitoring_company", b"monitoring_company", "pending_member", b"pending_member", "privacy_override", b"privacy_override", "profile", b"profile", "room", b"room", "security_mode", b"security_mode", "service_deactivation_pending_status", b"service_deactivation_pending_status", "space_capabilities", b"space_capabilities", "space_id", b"space_id", "space_update_type", b"space_update_type", "time_zone_id", b"time_zone_id", "total_notification_unread_counter", b"total_notification_unread_counter", "video_wall", b"video_wall"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            _WhichOneofReturnType_entity: _TypeAlias = _typing.Literal["current_member", "total_notification_unread_counter", "security_mode", "group", "profile", "member", "room", "device", "installation_company", "monitoring_company", "privacy_override", "time_zone_id", "pending_member", "video_wall", "address", "service_deactivation_pending_status", "extra_services_availability_status", "space_capabilities"]  # noqa: Y015
            _WhichOneofArgType_entity: _TypeAlias = _typing.Literal["entity", b"entity"]  # noqa: Y015
            def WhichOneof(self, oneof_group: _WhichOneofArgType_entity) -> _WhichOneofReturnType_entity | None: ...

        SNAPSHOT_FIELD_NUMBER: _builtins.int
        UPDATE_FIELD_NUMBER: _builtins.int
        UPDATES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def snapshot(self) -> _space_pb2.Space: ...
        @_builtins.property
        def update(self) -> Global___StreamSpaceUpdatesResponse.Success.Update: ...
        @_builtins.property
        def updates(self) -> Global___StreamSpaceUpdatesResponse.Success.Updates: ...
        def __init__(
            self,
            *,
            snapshot: _space_pb2.Space | None = ...,
            update: Global___StreamSpaceUpdatesResponse.Success.Update | None = ...,
            updates: Global___StreamSpaceUpdatesResponse.Success.Updates | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["snapshot", b"snapshot", "success", b"success", "update", b"update", "updates", b"updates"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["snapshot", b"snapshot", "success", b"success", "update", b"update", "updates", b"updates"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_success: _TypeAlias = _typing.Literal["snapshot", "update", "updates"]  # noqa: Y015
        _WhichOneofArgType_success: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_success) -> _WhichOneofReturnType_success | None: ...

    @_typing.final
    class Failure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        BAD_REQUEST_FIELD_NUMBER: _builtins.int
        SPACE_NOT_FOUND_FIELD_NUMBER: _builtins.int
        PERMISSION_DENIED_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def bad_request(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def space_not_found(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def permission_denied(self) -> _response_pb2.DefaultError: ...
        def __init__(
            self,
            *,
            bad_request: _response_pb2.DefaultError | None = ...,
            space_not_found: _response_pb2.DefaultError | None = ...,
            permission_denied: _response_pb2.DefaultError | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "error", b"error", "permission_denied", b"permission_denied", "space_not_found", b"space_not_found"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "error", b"error", "permission_denied", b"permission_denied", "space_not_found", b"space_not_found"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_error: _TypeAlias = _typing.Literal["bad_request", "space_not_found", "permission_denied"]  # noqa: Y015
        _WhichOneofArgType_error: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_error) -> _WhichOneofReturnType_error | None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def success(self) -> Global___StreamSpaceUpdatesResponse.Success: ...
    @_builtins.property
    def failure(self) -> Global___StreamSpaceUpdatesResponse.Failure: ...
    def __init__(
        self,
        *,
        success: Global___StreamSpaceUpdatesResponse.Success | None = ...,
        failure: Global___StreamSpaceUpdatesResponse.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["success", "failure"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___StreamSpaceUpdatesResponse: _TypeAlias = StreamSpaceUpdatesResponse  # noqa: Y015
