"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.mobile.v2.common.space.smartlock import smart_lock_pb2 as _smart_lock_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetUrlRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SMART_LOCK_TYPE_FIELD_NUMBER: _builtins.int
    smart_lock_type: _smart_lock_pb2.SmartLockType.ValueType
    def __init__(
        self,
        *,
        smart_lock_type: _smart_lock_pb2.SmartLockType.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["smart_lock_type", b"smart_lock_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetUrlRequest: _TypeAlias = GetUrlRequest  # noqa: Y015

@_typing.final
class GetUrlResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Success(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        URL_FIELD_NUMBER: _builtins.int
        url: _builtins.str
        def __init__(
            self,
            *,
            url: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["url", b"url"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class Failure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        MESSAGE_FIELD_NUMBER: _builtins.int
        message: _builtins.str
        def __init__(
            self,
            *,
            message: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def success(self) -> Global___GetUrlResponse.Success: ...
    @_builtins.property
    def failure(self) -> Global___GetUrlResponse.Failure: ...
    def __init__(
        self,
        *,
        success: Global___GetUrlResponse.Success | None = ...,
        failure: Global___GetUrlResponse.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["success", "failure"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___GetUrlResponse: _TypeAlias = GetUrlResponse  # noqa: Y015
