"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.mobile.v2.common.response import response_pb2 as _response_pb2
from systems.ajax.api.mobile.v2.common.space.smartlock import smart_lock_in_space_update_pb2 as _smart_lock_in_space_update_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class UpdateSmartLockRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SPACE_ID_FIELD_NUMBER: _builtins.int
    SMART_LOCK_ID_FIELD_NUMBER: _builtins.int
    UPDATE_FIELD_NUMBER: _builtins.int
    space_id: _builtins.str
    smart_lock_id: _builtins.str
    @_builtins.property
    def update(self) -> _smart_lock_in_space_update_pb2.SmartLockInSpaceUpdate: ...
    def __init__(
        self,
        *,
        space_id: _builtins.str = ...,
        smart_lock_id: _builtins.str = ...,
        update: _smart_lock_in_space_update_pb2.SmartLockInSpaceUpdate | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["update", b"update"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["smart_lock_id", b"smart_lock_id", "space_id", b"space_id", "update", b"update"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateSmartLockRequest: _TypeAlias = UpdateSmartLockRequest  # noqa: Y015

@_typing.final
class UpdateSmartLockResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Failure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        MESSAGE_FIELD_NUMBER: _builtins.int
        BAD_REQUEST_FIELD_NUMBER: _builtins.int
        PERMISSION_DENIED_FIELD_NUMBER: _builtins.int
        SPACE_NOT_FOUND_FIELD_NUMBER: _builtins.int
        SPACE_ARMED_FIELD_NUMBER: _builtins.int
        ROOM_NOT_FOUND_FIELD_NUMBER: _builtins.int
        SMART_LOCK_NOT_FOUND_FIELD_NUMBER: _builtins.int
        EXTERNAL_SERVICE_ACCESS_DENIED_FIELD_NUMBER: _builtins.int
        SMART_LOCK_OFFLINE_FIELD_NUMBER: _builtins.int
        message: _builtins.str
        @_builtins.property
        def bad_request(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def permission_denied(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def space_not_found(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def space_armed(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def room_not_found(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def smart_lock_not_found(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def external_service_access_denied(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def smart_lock_offline(self) -> _response_pb2.DefaultError: ...
        def __init__(
            self,
            *,
            message: _builtins.str = ...,
            bad_request: _response_pb2.DefaultError | None = ...,
            permission_denied: _response_pb2.DefaultError | None = ...,
            space_not_found: _response_pb2.DefaultError | None = ...,
            space_armed: _response_pb2.DefaultError | None = ...,
            room_not_found: _response_pb2.DefaultError | None = ...,
            smart_lock_not_found: _response_pb2.DefaultError | None = ...,
            external_service_access_denied: _response_pb2.DefaultError | None = ...,
            smart_lock_offline: _response_pb2.DefaultError | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "error", b"error", "external_service_access_denied", b"external_service_access_denied", "permission_denied", b"permission_denied", "room_not_found", b"room_not_found", "smart_lock_not_found", b"smart_lock_not_found", "smart_lock_offline", b"smart_lock_offline", "space_armed", b"space_armed", "space_not_found", b"space_not_found"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "error", b"error", "external_service_access_denied", b"external_service_access_denied", "message", b"message", "permission_denied", b"permission_denied", "room_not_found", b"room_not_found", "smart_lock_not_found", b"smart_lock_not_found", "smart_lock_offline", b"smart_lock_offline", "space_armed", b"space_armed", "space_not_found", b"space_not_found"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_error: _TypeAlias = _typing.Literal["bad_request", "permission_denied", "space_not_found", "space_armed", "room_not_found", "smart_lock_not_found", "external_service_access_denied", "smart_lock_offline"]  # noqa: Y015
        _WhichOneofArgType_error: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_error) -> _WhichOneofReturnType_error | None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def success(self) -> _response_pb2.Success: ...
    @_builtins.property
    def failure(self) -> Global___UpdateSmartLockResponse.Failure: ...
    def __init__(
        self,
        *,
        success: _response_pb2.Success | None = ...,
        failure: Global___UpdateSmartLockResponse.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["success", "failure"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___UpdateSmartLockResponse: _TypeAlias = UpdateSmartLockResponse  # noqa: Y015
