"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import alarm_restriction_pb2 as _alarm_restriction_pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import alarm_verification_pb2 as _alarm_verification_pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import common_jeweller_part_pb2 as _common_jeweller_part_pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import common_siren_part_pb2 as _common_siren_part_pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import common_standard_compliance_part_pb2 as _common_standard_compliance_part_pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import device_battery_pb2 as _device_battery_pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import device_tamper_status_pb2 as _device_tamper_status_pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import device_temperature_pb2 as _device_temperature_pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import group_association_pb2 as _group_association_pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import post_alarm_indication_pb2 as _post_alarm_indication_pb2
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import radio_interference_detection_part_pb2 as _radio_interference_detection_part_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class HomeSiren(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COMMON_JEWELLER_PART_FIELD_NUMBER: _builtins.int
    COMMON_SIREN_PART_FIELD_NUMBER: _builtins.int
    ALARM_VERIFICATION_FIELD_NUMBER: _builtins.int
    ALARM_RESTRICTION_FIELD_NUMBER: _builtins.int
    POST_ALARM_INDICATION_PROPS_FIELD_NUMBER: _builtins.int
    DEVICE_BATTERY_FIELD_NUMBER: _builtins.int
    DEVICE_TEMPERATURE_FIELD_NUMBER: _builtins.int
    DEVICE_TAMPER_STATUS_FIELD_NUMBER: _builtins.int
    COMMON_STANDARD_COMPLIANCE_PART_FIELD_NUMBER: _builtins.int
    GROUP_ASSOCIATION_FIELD_NUMBER: _builtins.int
    device_tamper_status: _device_tamper_status_pb2.DeviceTamperStatus.ValueType
    @_builtins.property
    def common_jeweller_part(self) -> _common_jeweller_part_pb2.CommonJewellerPart: ...
    @_builtins.property
    def common_siren_part(self) -> _common_siren_part_pb2.CommonSirenPart: ...
    @_builtins.property
    def alarm_verification(self) -> _alarm_verification_pb2.AlarmVerification: ...
    @_builtins.property
    def alarm_restriction(self) -> _alarm_restriction_pb2.AlarmRestriction: ...
    @_builtins.property
    def post_alarm_indication_props(self) -> _post_alarm_indication_pb2.PostAlarmIndication: ...
    @_builtins.property
    def device_battery(self) -> _device_battery_pb2.DeviceBatteryWithoutCharging: ...
    @_builtins.property
    def device_temperature(self) -> _device_temperature_pb2.DeviceTemperature: ...
    @_builtins.property
    def common_standard_compliance_part(self) -> _common_standard_compliance_part_pb2.CommonStandardCompliancePart: ...
    @_builtins.property
    def group_association(self) -> _group_association_pb2.GroupAssociation: ...
    def __init__(
        self,
        *,
        common_jeweller_part: _common_jeweller_part_pb2.CommonJewellerPart | None = ...,
        common_siren_part: _common_siren_part_pb2.CommonSirenPart | None = ...,
        alarm_verification: _alarm_verification_pb2.AlarmVerification | None = ...,
        alarm_restriction: _alarm_restriction_pb2.AlarmRestriction | None = ...,
        post_alarm_indication_props: _post_alarm_indication_pb2.PostAlarmIndication | None = ...,
        device_battery: _device_battery_pb2.DeviceBatteryWithoutCharging | None = ...,
        device_temperature: _device_temperature_pb2.DeviceTemperature | None = ...,
        device_tamper_status: _device_tamper_status_pb2.DeviceTamperStatus.ValueType = ...,
        common_standard_compliance_part: _common_standard_compliance_part_pb2.CommonStandardCompliancePart | None = ...,
        group_association: _group_association_pb2.GroupAssociation | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["alarm_restriction", b"alarm_restriction", "alarm_verification", b"alarm_verification", "common_jeweller_part", b"common_jeweller_part", "common_siren_part", b"common_siren_part", "common_standard_compliance_part", b"common_standard_compliance_part", "device_battery", b"device_battery", "device_temperature", b"device_temperature", "group_association", b"group_association", "post_alarm_indication_props", b"post_alarm_indication_props"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["alarm_restriction", b"alarm_restriction", "alarm_verification", b"alarm_verification", "common_jeweller_part", b"common_jeweller_part", "common_siren_part", b"common_siren_part", "common_standard_compliance_part", b"common_standard_compliance_part", "device_battery", b"device_battery", "device_tamper_status", b"device_tamper_status", "device_temperature", b"device_temperature", "group_association", b"group_association", "post_alarm_indication_props", b"post_alarm_indication_props"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HomeSiren: _TypeAlias = HomeSiren  # noqa: Y015

@_typing.final
class HomeSirenG3(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COMMON_JEWELLER_PART_FIELD_NUMBER: _builtins.int
    COMMON_SIREN_PART_FIELD_NUMBER: _builtins.int
    ALARM_VERIFICATION_FIELD_NUMBER: _builtins.int
    ALARM_RESTRICTION_FIELD_NUMBER: _builtins.int
    POST_ALARM_INDICATION_PROPS_FIELD_NUMBER: _builtins.int
    DEVICE_BATTERY_FIELD_NUMBER: _builtins.int
    DEVICE_TEMPERATURE_FIELD_NUMBER: _builtins.int
    DEVICE_TAMPER_STATUS_FIELD_NUMBER: _builtins.int
    COMMON_STANDARD_COMPLIANCE_PART_FIELD_NUMBER: _builtins.int
    GROUP_ASSOCIATION_FIELD_NUMBER: _builtins.int
    RADIO_INTERFERENCE_DETECTION_PART_FIELD_NUMBER: _builtins.int
    device_tamper_status: _device_tamper_status_pb2.DeviceTamperStatus.ValueType
    @_builtins.property
    def common_jeweller_part(self) -> _common_jeweller_part_pb2.CommonJewellerPart: ...
    @_builtins.property
    def common_siren_part(self) -> _common_siren_part_pb2.CommonSirenPart: ...
    @_builtins.property
    def alarm_verification(self) -> _alarm_verification_pb2.AlarmVerification: ...
    @_builtins.property
    def alarm_restriction(self) -> _alarm_restriction_pb2.AlarmRestriction: ...
    @_builtins.property
    def post_alarm_indication_props(self) -> _post_alarm_indication_pb2.PostAlarmIndication: ...
    @_builtins.property
    def device_battery(self) -> _device_battery_pb2.DeviceBatteryWithoutCharging: ...
    @_builtins.property
    def device_temperature(self) -> _device_temperature_pb2.DeviceTemperature: ...
    @_builtins.property
    def common_standard_compliance_part(self) -> _common_standard_compliance_part_pb2.CommonStandardCompliancePart: ...
    @_builtins.property
    def group_association(self) -> _group_association_pb2.GroupAssociation: ...
    @_builtins.property
    def radio_interference_detection_part(self) -> _radio_interference_detection_part_pb2.RadioInterferenceDetectionPart: ...
    def __init__(
        self,
        *,
        common_jeweller_part: _common_jeweller_part_pb2.CommonJewellerPart | None = ...,
        common_siren_part: _common_siren_part_pb2.CommonSirenPart | None = ...,
        alarm_verification: _alarm_verification_pb2.AlarmVerification | None = ...,
        alarm_restriction: _alarm_restriction_pb2.AlarmRestriction | None = ...,
        post_alarm_indication_props: _post_alarm_indication_pb2.PostAlarmIndication | None = ...,
        device_battery: _device_battery_pb2.DeviceBatteryWithoutCharging | None = ...,
        device_temperature: _device_temperature_pb2.DeviceTemperature | None = ...,
        device_tamper_status: _device_tamper_status_pb2.DeviceTamperStatus.ValueType = ...,
        common_standard_compliance_part: _common_standard_compliance_part_pb2.CommonStandardCompliancePart | None = ...,
        group_association: _group_association_pb2.GroupAssociation | None = ...,
        radio_interference_detection_part: _radio_interference_detection_part_pb2.RadioInterferenceDetectionPart | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["alarm_restriction", b"alarm_restriction", "alarm_verification", b"alarm_verification", "common_jeweller_part", b"common_jeweller_part", "common_siren_part", b"common_siren_part", "common_standard_compliance_part", b"common_standard_compliance_part", "device_battery", b"device_battery", "device_temperature", b"device_temperature", "group_association", b"group_association", "post_alarm_indication_props", b"post_alarm_indication_props", "radio_interference_detection_part", b"radio_interference_detection_part"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["alarm_restriction", b"alarm_restriction", "alarm_verification", b"alarm_verification", "common_jeweller_part", b"common_jeweller_part", "common_siren_part", b"common_siren_part", "common_standard_compliance_part", b"common_standard_compliance_part", "device_battery", b"device_battery", "device_tamper_status", b"device_tamper_status", "device_temperature", b"device_temperature", "group_association", b"group_association", "post_alarm_indication_props", b"post_alarm_indication_props", "radio_interference_detection_part", b"radio_interference_detection_part"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HomeSirenG3: _TypeAlias = HomeSirenG3  # noqa: Y015

@_typing.final
class HomeSirenS(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COMMON_JEWELLER_PART_FIELD_NUMBER: _builtins.int
    COMMON_SIREN_PART_FIELD_NUMBER: _builtins.int
    ALARM_VERIFICATION_FIELD_NUMBER: _builtins.int
    ALARM_RESTRICTION_FIELD_NUMBER: _builtins.int
    POST_ALARM_INDICATION_PROPS_FIELD_NUMBER: _builtins.int
    DEVICE_BATTERY_FIELD_NUMBER: _builtins.int
    DEVICE_TEMPERATURE_FIELD_NUMBER: _builtins.int
    DEVICE_TAMPER_STATUS_FIELD_NUMBER: _builtins.int
    COMMON_STANDARD_COMPLIANCE_PART_FIELD_NUMBER: _builtins.int
    GROUP_ASSOCIATION_FIELD_NUMBER: _builtins.int
    device_tamper_status: _device_tamper_status_pb2.DeviceTamperStatus.ValueType
    @_builtins.property
    def common_jeweller_part(self) -> _common_jeweller_part_pb2.CommonJewellerPart: ...
    @_builtins.property
    def common_siren_part(self) -> _common_siren_part_pb2.CommonSirenPart: ...
    @_builtins.property
    def alarm_verification(self) -> _alarm_verification_pb2.AlarmVerification: ...
    @_builtins.property
    def alarm_restriction(self) -> _alarm_restriction_pb2.AlarmRestriction: ...
    @_builtins.property
    def post_alarm_indication_props(self) -> _post_alarm_indication_pb2.PostAlarmIndication: ...
    @_builtins.property
    def device_battery(self) -> _device_battery_pb2.DeviceBatteryWithoutCharging: ...
    @_builtins.property
    def device_temperature(self) -> _device_temperature_pb2.DeviceTemperature: ...
    @_builtins.property
    def common_standard_compliance_part(self) -> _common_standard_compliance_part_pb2.CommonStandardCompliancePart: ...
    @_builtins.property
    def group_association(self) -> _group_association_pb2.GroupAssociation: ...
    def __init__(
        self,
        *,
        common_jeweller_part: _common_jeweller_part_pb2.CommonJewellerPart | None = ...,
        common_siren_part: _common_siren_part_pb2.CommonSirenPart | None = ...,
        alarm_verification: _alarm_verification_pb2.AlarmVerification | None = ...,
        alarm_restriction: _alarm_restriction_pb2.AlarmRestriction | None = ...,
        post_alarm_indication_props: _post_alarm_indication_pb2.PostAlarmIndication | None = ...,
        device_battery: _device_battery_pb2.DeviceBatteryWithoutCharging | None = ...,
        device_temperature: _device_temperature_pb2.DeviceTemperature | None = ...,
        device_tamper_status: _device_tamper_status_pb2.DeviceTamperStatus.ValueType = ...,
        common_standard_compliance_part: _common_standard_compliance_part_pb2.CommonStandardCompliancePart | None = ...,
        group_association: _group_association_pb2.GroupAssociation | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["alarm_restriction", b"alarm_restriction", "alarm_verification", b"alarm_verification", "common_jeweller_part", b"common_jeweller_part", "common_siren_part", b"common_siren_part", "common_standard_compliance_part", b"common_standard_compliance_part", "device_battery", b"device_battery", "device_temperature", b"device_temperature", "group_association", b"group_association", "post_alarm_indication_props", b"post_alarm_indication_props"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["alarm_restriction", b"alarm_restriction", "alarm_verification", b"alarm_verification", "common_jeweller_part", b"common_jeweller_part", "common_siren_part", b"common_siren_part", "common_standard_compliance_part", b"common_standard_compliance_part", "device_battery", b"device_battery", "device_tamper_status", b"device_tamper_status", "device_temperature", b"device_temperature", "group_association", b"group_association", "post_alarm_indication_props", b"post_alarm_indication_props"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HomeSirenS: _TypeAlias = HomeSirenS  # noqa: Y015
