"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from systems.ajax.api.mobile.v2.common.video import types_pb2 as _types_pb2
from v3.mobilegwsvc.commonmodels.video.videoedge.channel.detection import line_crossing_direction_pb2 as _line_crossing_direction_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AddVideoEdgeLineCrossingRuleRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SPACE_ID_FIELD_NUMBER: _builtins.int
    VIDEO_EDGE_ID_FIELD_NUMBER: _builtins.int
    CHANNEL_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    POINTS_FIELD_NUMBER: _builtins.int
    DIRECTION_FIELD_NUMBER: _builtins.int
    OBJECT_CLASSES_FIELD_NUMBER: _builtins.int
    space_id: _builtins.str
    """[required]"""
    video_edge_id: _builtins.str
    """[required]"""
    channel_id: _builtins.str
    """[required]"""
    name: _builtins.str
    """[required]"""
    direction: _line_crossing_direction_pb2.LineCrossingDirection.ValueType
    """[required]"""
    @_builtins.property
    def points(self) -> _containers.RepeatedCompositeFieldContainer[_types_pb2.Point2f]:
        """[required]
        non-intersecting polyline (2 points minimum). Valid values for coordinates are in range [0, 1] inclusive.
        """

    @_builtins.property
    def object_classes(self) -> _containers.RepeatedScalarFieldContainer[_types_pb2.ObjectClass.ValueType]:
        """[required]"""

    def __init__(
        self,
        *,
        space_id: _builtins.str = ...,
        video_edge_id: _builtins.str = ...,
        channel_id: _builtins.str = ...,
        name: _builtins.str = ...,
        points: _abc.Iterable[_types_pb2.Point2f] | None = ...,
        direction: _line_crossing_direction_pb2.LineCrossingDirection.ValueType = ...,
        object_classes: _abc.Iterable[_types_pb2.ObjectClass.ValueType] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel_id", b"channel_id", "direction", b"direction", "name", b"name", "object_classes", b"object_classes", "points", b"points", "space_id", b"space_id", "video_edge_id", b"video_edge_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AddVideoEdgeLineCrossingRuleRequest: _TypeAlias = AddVideoEdgeLineCrossingRuleRequest  # noqa: Y015
