"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.mobile.v2.common.response import response_pb2 as _response_pb2
from systems.ajax.api.mobile.v2.common.space import space_locator_pb2 as _space_locator_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class RemoveHubRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SPACE_LOCATOR_FIELD_NUMBER: _builtins.int
    HUB_ID_FIELD_NUMBER: _builtins.int
    hub_id: _builtins.str
    @_builtins.property
    def space_locator(self) -> _space_locator_pb2.SpaceLocator: ...
    def __init__(
        self,
        *,
        space_locator: _space_locator_pb2.SpaceLocator | None = ...,
        hub_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["space_locator", b"space_locator"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hub_id", b"hub_id", "space_locator", b"space_locator"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RemoveHubRequest: _TypeAlias = RemoveHubRequest  # noqa: Y015

@_typing.final
class RemoveHubResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Failure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        BAD_REQUEST_FIELD_NUMBER: _builtins.int
        SPACE_NOT_FOUND_FIELD_NUMBER: _builtins.int
        HUB_NOT_FOUND_FIELD_NUMBER: _builtins.int
        SPACE_ARMED_FIELD_NUMBER: _builtins.int
        PERMISSION_DENIED_FIELD_NUMBER: _builtins.int
        SPACE_LOCKED_FIELD_NUMBER: _builtins.int
        SPACE_ON_MONITORING_FIELD_NUMBER: _builtins.int
        SPACE_HAS_SUBSCRIPTIONS_FIELD_NUMBER: _builtins.int
        SPACE_HAS_SUBSCRIPTIONS_BY_MEMBER_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def bad_request(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def space_not_found(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def hub_not_found(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def space_armed(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def permission_denied(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def space_locked(self) -> _response_pb2.SpaceLockedError: ...
        @_builtins.property
        def space_on_monitoring(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def space_has_subscriptions(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def space_has_subscriptions_by_member(self) -> _response_pb2.DefaultError: ...
        def __init__(
            self,
            *,
            bad_request: _response_pb2.DefaultError | None = ...,
            space_not_found: _response_pb2.DefaultError | None = ...,
            hub_not_found: _response_pb2.DefaultError | None = ...,
            space_armed: _response_pb2.DefaultError | None = ...,
            permission_denied: _response_pb2.DefaultError | None = ...,
            space_locked: _response_pb2.SpaceLockedError | None = ...,
            space_on_monitoring: _response_pb2.DefaultError | None = ...,
            space_has_subscriptions: _response_pb2.DefaultError | None = ...,
            space_has_subscriptions_by_member: _response_pb2.DefaultError | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "error", b"error", "hub_not_found", b"hub_not_found", "permission_denied", b"permission_denied", "space_armed", b"space_armed", "space_has_subscriptions", b"space_has_subscriptions", "space_has_subscriptions_by_member", b"space_has_subscriptions_by_member", "space_locked", b"space_locked", "space_not_found", b"space_not_found", "space_on_monitoring", b"space_on_monitoring"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "error", b"error", "hub_not_found", b"hub_not_found", "permission_denied", b"permission_denied", "space_armed", b"space_armed", "space_has_subscriptions", b"space_has_subscriptions", "space_has_subscriptions_by_member", b"space_has_subscriptions_by_member", "space_locked", b"space_locked", "space_not_found", b"space_not_found", "space_on_monitoring", b"space_on_monitoring"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_error: _TypeAlias = _typing.Literal["bad_request", "space_not_found", "hub_not_found", "space_armed", "permission_denied", "space_locked", "space_on_monitoring", "space_has_subscriptions", "space_has_subscriptions_by_member"]  # noqa: Y015
        _WhichOneofArgType_error: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_error) -> _WhichOneofReturnType_error | None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def success(self) -> _response_pb2.Success: ...
    @_builtins.property
    def failure(self) -> Global___RemoveHubResponse.Failure: ...
    def __init__(
        self,
        *,
        success: _response_pb2.Success | None = ...,
        failure: Global___RemoveHubResponse.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["success", "failure"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___RemoveHubResponse: _TypeAlias = RemoveHubResponse  # noqa: Y015
