"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from v1.common.privacy import surveillance_cameras_devices_pb2 as _surveillance_cameras_devices_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class EmployeeSurveillanceCamerasAccess(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class NotAllowed(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @_typing.final
    class Allowed(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        DEVICES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def devices(self) -> _surveillance_cameras_devices_pb2.SurveillanceCamerasDevices: ...
        def __init__(
            self,
            *,
            devices: _surveillance_cameras_devices_pb2.SurveillanceCamerasDevices | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["devices", b"devices"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["devices", b"devices"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    NOT_ALLOWED_FIELD_NUMBER: _builtins.int
    ALLOWED_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def not_allowed(self) -> Global___EmployeeSurveillanceCamerasAccess.NotAllowed: ...
    @_builtins.property
    def allowed(self) -> Global___EmployeeSurveillanceCamerasAccess.Allowed: ...
    def __init__(
        self,
        *,
        not_allowed: Global___EmployeeSurveillanceCamerasAccess.NotAllowed | None = ...,
        allowed: Global___EmployeeSurveillanceCamerasAccess.Allowed | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["allowed", b"allowed", "current_availability_mode", b"current_availability_mode", "not_allowed", b"not_allowed"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allowed", b"allowed", "current_availability_mode", b"current_availability_mode", "not_allowed", b"not_allowed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_current_availability_mode: _TypeAlias = _typing.Literal["not_allowed", "allowed"]  # noqa: Y015
    _WhichOneofArgType_current_availability_mode: _TypeAlias = _typing.Literal["current_availability_mode", b"current_availability_mode"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_current_availability_mode) -> _WhichOneofReturnType_current_availability_mode | None: ...

Global___EmployeeSurveillanceCamerasAccess: _TypeAlias = EmployeeSurveillanceCamerasAccess  # noqa: Y015
