"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from v1.company import employee_pb2 as _employee_pb2
from v1.user import user_company_pb2 as _user_company_pb2
from v1.user import user_info_pb2 as _user_info_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class LoginResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    SESSION_TOKEN_FIELD_NUMBER: _builtins.int
    COMPANY_ID_FIELD_NUMBER: _builtins.int
    EMPLOYEE_INFO_FIELD_NUMBER: _builtins.int
    USER_COMPANIES_FIELD_NUMBER: _builtins.int
    USER_INFO_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    session_token: _builtins.str
    company_id: _builtins.str
    @_builtins.property
    def employee_info(self) -> _employee_pb2.Employee.EmployeeInfo: ...
    @_builtins.property
    def user_companies(self) -> _containers.RepeatedCompositeFieldContainer[_user_company_pb2.UserCompany]: ...
    @_builtins.property
    def user_info(self) -> _user_info_pb2.UserInfo: ...
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        session_token: _builtins.str = ...,
        company_id: _builtins.str = ...,
        employee_info: _employee_pb2.Employee.EmployeeInfo | None = ...,
        user_companies: _abc.Iterable[_user_company_pb2.UserCompany] | None = ...,
        user_info: _user_info_pb2.UserInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["employee_info", b"employee_info", "user_info", b"user_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["company_id", b"company_id", "employee_info", b"employee_info", "session_token", b"session_token", "user_companies", b"user_companies", "user_id", b"user_id", "user_info", b"user_info"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LoginResponse: _TypeAlias = LoginResponse  # noqa: Y015
