"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _OnvifUserRole:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _OnvifUserRoleEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_OnvifUserRole.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ONVIF_USER_ROLE_UNSPECIFIED: _OnvifUserRole.ValueType  # 0
    ONVIF_USER_ROLE_ADMIN: _OnvifUserRole.ValueType  # 1
    ONVIF_USER_ROLE_OPERATOR: _OnvifUserRole.ValueType  # 2
    ONVIF_USER_ROLE_USER: _OnvifUserRole.ValueType  # 3

class OnvifUserRole(_OnvifUserRole, metaclass=_OnvifUserRoleEnumTypeWrapper): ...

ONVIF_USER_ROLE_UNSPECIFIED: OnvifUserRole.ValueType  # 0
ONVIF_USER_ROLE_ADMIN: OnvifUserRole.ValueType  # 1
ONVIF_USER_ROLE_OPERATOR: OnvifUserRole.ValueType  # 2
ONVIF_USER_ROLE_USER: OnvifUserRole.ValueType  # 3
Global___OnvifUserRole: _TypeAlias = OnvifUserRole  # noqa: Y015
