"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from v3.mobilegwsvc.commonmodels.hub.device.common import device_radio_test_type_pb2 as _device_radio_test_type_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class StreamRadioTestRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HUB_ID_FIELD_NUMBER: _builtins.int
    DEVICE_ID_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    hub_id: _builtins.str
    device_id: _builtins.str
    type: _device_radio_test_type_pb2.DeviceRadioTestType.ValueType
    def __init__(
        self,
        *,
        hub_id: _builtins.str = ...,
        device_id: _builtins.str = ...,
        type: _device_radio_test_type_pb2.DeviceRadioTestType.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_id", b"device_id", "hub_id", b"hub_id", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamRadioTestRequest: _TypeAlias = StreamRadioTestRequest  # noqa: Y015
