"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from systems.ajax.api.ecosystem.v2.hubsvc.commonmodels import object_type_pb2 as _object_type_pb2
from systems.ajax.api.mobile.v2.common.response import response_pb2 as _response_pb2
from systems.ajax.api.mobile.v2.common.video.videoedge.about import about_pb2 as _about_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetDeviceAboutRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    QR_CODE_FIELD_NUMBER: _builtins.int
    qr_code: _builtins.str
    def __init__(
        self,
        *,
        qr_code: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["qr_code", b"qr_code"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetDeviceAboutRequest: _TypeAlias = GetDeviceAboutRequest  # noqa: Y015

@_typing.final
class GetDeviceAboutResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Success(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        HUB_FIELD_NUMBER: _builtins.int
        VIDEO_EDGE_FIELD_NUMBER: _builtins.int
        HUB_DEVICE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def hub(self) -> Global___GetDeviceAboutResponse.Hub: ...
        @_builtins.property
        def video_edge(self) -> Global___GetDeviceAboutResponse.VideoEdge: ...
        @_builtins.property
        def hub_device(self) -> Global___GetDeviceAboutResponse.HubDevice: ...
        def __init__(
            self,
            *,
            hub: Global___GetDeviceAboutResponse.Hub | None = ...,
            video_edge: Global___GetDeviceAboutResponse.VideoEdge | None = ...,
            hub_device: Global___GetDeviceAboutResponse.HubDevice | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["device_type", b"device_type", "hub", b"hub", "hub_device", b"hub_device", "video_edge", b"video_edge"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["device_type", b"device_type", "hub", b"hub", "hub_device", b"hub_device", "video_edge", b"video_edge"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_device_type: _TypeAlias = _typing.Literal["hub", "video_edge", "hub_device"]  # noqa: Y015
        _WhichOneofArgType_device_type: _TypeAlias = _typing.Literal["device_type", b"device_type"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_device_type) -> _WhichOneofReturnType_device_type | None: ...

    @_typing.final
    class Failure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        BAD_REQUEST_FIELD_NUMBER: _builtins.int
        DEVICE_NOT_FOUND_FIELD_NUMBER: _builtins.int
        DEVICE_IS_ALREADY_INSTALLED_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def bad_request(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def device_not_found(self) -> _response_pb2.DefaultError:
            """This error is returned when qr is related to VideoEdge and such device is not found.
            This error is not returned for Hub and HubDevice (at least for now), currently
            success response with empty body is returned: Hub {} or HubDevice {}.
            """

        @_builtins.property
        def device_is_already_installed(self) -> _response_pb2.DefaultError:
            """ This error is returned when qr is related to VideoEdge that is already installed."""

        def __init__(
            self,
            *,
            bad_request: _response_pb2.DefaultError | None = ...,
            device_not_found: _response_pb2.DefaultError | None = ...,
            device_is_already_installed: _response_pb2.DefaultError | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "device_is_already_installed", b"device_is_already_installed", "device_not_found", b"device_not_found", "error", b"error"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "device_is_already_installed", b"device_is_already_installed", "device_not_found", b"device_not_found", "error", b"error"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_error: _TypeAlias = _typing.Literal["bad_request", "device_not_found", "device_is_already_installed"]  # noqa: Y015
        _WhichOneofArgType_error: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_error) -> _WhichOneofReturnType_error | None: ...

    @_typing.final
    class Hub(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        OBJECT_TYPE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def object_type(self) -> _object_type_pb2.ObjectType:
            """[optional] - this field is absent when qr_code is valid but hub is not found"""

        def __init__(
            self,
            *,
            object_type: _object_type_pb2.ObjectType | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["object_type", b"object_type"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["object_type", b"object_type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class VideoEdge(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ABOUT_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def about(self) -> _about_pb2.About: ...
        def __init__(
            self,
            *,
            about: _about_pb2.About | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["about", b"about"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["about", b"about"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class HubDevice(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        OBJECT_TYPE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def object_type(self) -> _object_type_pb2.ObjectType:
            """[optional] - this field is absent when qr_code is valid but hub device is not found"""

        def __init__(
            self,
            *,
            object_type: _object_type_pb2.ObjectType | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["object_type", b"object_type"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["object_type", b"object_type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def success(self) -> Global___GetDeviceAboutResponse.Success: ...
    @_builtins.property
    def failure(self) -> Global___GetDeviceAboutResponse.Failure: ...
    def __init__(
        self,
        *,
        success: Global___GetDeviceAboutResponse.Success | None = ...,
        failure: Global___GetDeviceAboutResponse.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["success", "failure"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___GetDeviceAboutResponse: _TypeAlias = GetDeviceAboutResponse  # noqa: Y015
