"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from systems.ajax.api.mobile.v2.common.response import response_pb2 as _response_pb2
from systems.ajax.api.mobile.v2.common.space import space_locator_pb2 as _space_locator_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class MakeMediaDevicePermanentRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class NewChannel(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        CHANNEL_ID_ON_MEDIA_DEVICE_FIELD_NUMBER: _builtins.int
        GROUP_ID_FIELD_NUMBER: _builtins.int
        ROOM_ID_FIELD_NUMBER: _builtins.int
        channel_id_on_media_device: _builtins.str
        group_id: _builtins.str
        room_id: _builtins.str
        def __init__(
            self,
            *,
            channel_id_on_media_device: _builtins.str = ...,
            group_id: _builtins.str = ...,
            room_id: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["channel_id_on_media_device", b"channel_id_on_media_device", "group_id", b"group_id", "room_id", b"room_id"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    VIDEO_EDGE_ID_FIELD_NUMBER: _builtins.int
    MEDIA_DEVICE_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    NEW_CHANNEL_FIELD_NUMBER: _builtins.int
    SPACE_LOCATOR_FIELD_NUMBER: _builtins.int
    video_edge_id: _builtins.str
    media_device_id: _builtins.str
    name: _builtins.str
    @_builtins.property
    def new_channel(self) -> _containers.RepeatedCompositeFieldContainer[Global___MakeMediaDevicePermanentRequest.NewChannel]: ...
    @_builtins.property
    def space_locator(self) -> _space_locator_pb2.SpaceLocator:
        """[optional] - temporarily for backward compatibility"""

    def __init__(
        self,
        *,
        video_edge_id: _builtins.str = ...,
        media_device_id: _builtins.str = ...,
        name: _builtins.str = ...,
        new_channel: _abc.Iterable[Global___MakeMediaDevicePermanentRequest.NewChannel] | None = ...,
        space_locator: _space_locator_pb2.SpaceLocator | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["space_locator", b"space_locator"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["media_device_id", b"media_device_id", "name", b"name", "new_channel", b"new_channel", "space_locator", b"space_locator", "video_edge_id", b"video_edge_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MakeMediaDevicePermanentRequest: _TypeAlias = MakeMediaDevicePermanentRequest  # noqa: Y015

@_typing.final
class MakeMediaDevicePermanentResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Failure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        BAD_REQUEST_FIELD_NUMBER: _builtins.int
        PERMISSION_DENIED_FIELD_NUMBER: _builtins.int
        SPACE_ARMED_FIELD_NUMBER: _builtins.int
        VIDEO_EDGE_NOT_FOUND_FIELD_NUMBER: _builtins.int
        DEVICE_NOT_FOUND_FIELD_NUMBER: _builtins.int
        ROOM_NOT_FOUND_FIELD_NUMBER: _builtins.int
        GROUP_NOT_FOUND_FIELD_NUMBER: _builtins.int
        CHANNELS_NUMBER_CONSTRAINT_VIOLATION_FIELD_NUMBER: _builtins.int
        VIDEO_EDGE_IS_OFFLINE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def bad_request(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def permission_denied(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def space_armed(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def video_edge_not_found(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def device_not_found(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def room_not_found(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def group_not_found(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def channels_number_constraint_violation(self) -> _response_pb2.DefaultError: ...
        @_builtins.property
        def video_edge_is_offline(self) -> _response_pb2.DefaultError: ...
        def __init__(
            self,
            *,
            bad_request: _response_pb2.DefaultError | None = ...,
            permission_denied: _response_pb2.DefaultError | None = ...,
            space_armed: _response_pb2.DefaultError | None = ...,
            video_edge_not_found: _response_pb2.DefaultError | None = ...,
            device_not_found: _response_pb2.DefaultError | None = ...,
            room_not_found: _response_pb2.DefaultError | None = ...,
            group_not_found: _response_pb2.DefaultError | None = ...,
            channels_number_constraint_violation: _response_pb2.DefaultError | None = ...,
            video_edge_is_offline: _response_pb2.DefaultError | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "channels_number_constraint_violation", b"channels_number_constraint_violation", "device_not_found", b"device_not_found", "error", b"error", "group_not_found", b"group_not_found", "permission_denied", b"permission_denied", "room_not_found", b"room_not_found", "space_armed", b"space_armed", "video_edge_is_offline", b"video_edge_is_offline", "video_edge_not_found", b"video_edge_not_found"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bad_request", b"bad_request", "channels_number_constraint_violation", b"channels_number_constraint_violation", "device_not_found", b"device_not_found", "error", b"error", "group_not_found", b"group_not_found", "permission_denied", b"permission_denied", "room_not_found", b"room_not_found", "space_armed", b"space_armed", "video_edge_is_offline", b"video_edge_is_offline", "video_edge_not_found", b"video_edge_not_found"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_error: _TypeAlias = _typing.Literal["bad_request", "permission_denied", "space_armed", "video_edge_not_found", "device_not_found", "room_not_found", "group_not_found", "channels_number_constraint_violation", "video_edge_is_offline"]  # noqa: Y015
        _WhichOneofArgType_error: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_error) -> _WhichOneofReturnType_error | None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def success(self) -> _response_pb2.Success: ...
    @_builtins.property
    def failure(self) -> Global___MakeMediaDevicePermanentResponse.Failure: ...
    def __init__(
        self,
        *,
        success: _response_pb2.Success | None = ...,
        failure: Global___MakeMediaDevicePermanentResponse.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "response", b"response", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_response: _TypeAlias = _typing.Literal["success", "failure"]  # noqa: Y015
    _WhichOneofArgType_response: _TypeAlias = _typing.Literal["response", b"response"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_response) -> _WhichOneofReturnType_response | None: ...

Global___MakeMediaDevicePermanentResponse: _TypeAlias = MakeMediaDevicePermanentResponse  # noqa: Y015
