"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from systems.ajax.protobuf.hub.device import common_device_pb2 as _common_device_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DoorProtectPlus(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _SirenTrigger:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SirenTriggerEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DoorProtectPlus._SirenTrigger.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_SIREN_TRIGGER_INFO: DoorProtectPlus._SirenTrigger.ValueType  # 0
        REED: DoorProtectPlus._SirenTrigger.ValueType  # 1
        EXTRA_CONTACT: DoorProtectPlus._SirenTrigger.ValueType  # 2
        TILT: DoorProtectPlus._SirenTrigger.ValueType  # 3
        SHOCK: DoorProtectPlus._SirenTrigger.ValueType  # 4
        SHUTTER_ALARM: DoorProtectPlus._SirenTrigger.ValueType  # 5
        SHUTTER_ONLINE: DoorProtectPlus._SirenTrigger.ValueType  # 6

    class SirenTrigger(_SirenTrigger, metaclass=_SirenTriggerEnumTypeWrapper): ...
    NO_SIREN_TRIGGER_INFO: DoorProtectPlus.SirenTrigger.ValueType  # 0
    REED: DoorProtectPlus.SirenTrigger.ValueType  # 1
    EXTRA_CONTACT: DoorProtectPlus.SirenTrigger.ValueType  # 2
    TILT: DoorProtectPlus.SirenTrigger.ValueType  # 3
    SHOCK: DoorProtectPlus.SirenTrigger.ValueType  # 4
    SHUTTER_ALARM: DoorProtectPlus.SirenTrigger.ValueType  # 5
    SHUTTER_ONLINE: DoorProtectPlus.SirenTrigger.ValueType  # 6

    class _ExtraContactType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ExtraContactTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DoorProtectPlus._ExtraContactType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_EXTRA_CONTACT_TYPE_INFO: DoorProtectPlus._ExtraContactType.ValueType  # 0
        STANDARD: DoorProtectPlus._ExtraContactType.ValueType  # 1
        ROLLER_SHUTTER: DoorProtectPlus._ExtraContactType.ValueType  # 2

    class ExtraContactType(_ExtraContactType, metaclass=_ExtraContactTypeEnumTypeWrapper): ...
    NO_EXTRA_CONTACT_TYPE_INFO: DoorProtectPlus.ExtraContactType.ValueType  # 0
    STANDARD: DoorProtectPlus.ExtraContactType.ValueType  # 1
    ROLLER_SHUTTER: DoorProtectPlus.ExtraContactType.ValueType  # 2

    class _AccelerometerTiltDegrees:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _AccelerometerTiltDegreesEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DoorProtectPlus._AccelerometerTiltDegrees.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_ACCELEROMETER_TILT_DEGREES_INFO: DoorProtectPlus._AccelerometerTiltDegrees.ValueType  # 0
        DEG_5: DoorProtectPlus._AccelerometerTiltDegrees.ValueType  # 1
        DEG_10: DoorProtectPlus._AccelerometerTiltDegrees.ValueType  # 2
        DEG_15: DoorProtectPlus._AccelerometerTiltDegrees.ValueType  # 3
        DEG_20: DoorProtectPlus._AccelerometerTiltDegrees.ValueType  # 4
        DEG_25: DoorProtectPlus._AccelerometerTiltDegrees.ValueType  # 5

    class AccelerometerTiltDegrees(_AccelerometerTiltDegrees, metaclass=_AccelerometerTiltDegreesEnumTypeWrapper): ...
    NO_ACCELEROMETER_TILT_DEGREES_INFO: DoorProtectPlus.AccelerometerTiltDegrees.ValueType  # 0
    DEG_5: DoorProtectPlus.AccelerometerTiltDegrees.ValueType  # 1
    DEG_10: DoorProtectPlus.AccelerometerTiltDegrees.ValueType  # 2
    DEG_15: DoorProtectPlus.AccelerometerTiltDegrees.ValueType  # 3
    DEG_20: DoorProtectPlus.AccelerometerTiltDegrees.ValueType  # 4
    DEG_25: DoorProtectPlus.AccelerometerTiltDegrees.ValueType  # 5

    class _AccelerometerTiltAlarmDelaySeconds:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _AccelerometerTiltAlarmDelaySecondsEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DoorProtectPlus._AccelerometerTiltAlarmDelaySeconds.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_ACCELEROMETER_TILT_ALARM_DELAY_SECONDS_INFO: DoorProtectPlus._AccelerometerTiltAlarmDelaySeconds.ValueType  # 0
        SEC_1: DoorProtectPlus._AccelerometerTiltAlarmDelaySeconds.ValueType  # 1
        SEC_2: DoorProtectPlus._AccelerometerTiltAlarmDelaySeconds.ValueType  # 2
        SEC_5: DoorProtectPlus._AccelerometerTiltAlarmDelaySeconds.ValueType  # 3
        SEC_10: DoorProtectPlus._AccelerometerTiltAlarmDelaySeconds.ValueType  # 4
        SEC_30: DoorProtectPlus._AccelerometerTiltAlarmDelaySeconds.ValueType  # 5
        SEC_60: DoorProtectPlus._AccelerometerTiltAlarmDelaySeconds.ValueType  # 6

    class AccelerometerTiltAlarmDelaySeconds(_AccelerometerTiltAlarmDelaySeconds, metaclass=_AccelerometerTiltAlarmDelaySecondsEnumTypeWrapper): ...
    NO_ACCELEROMETER_TILT_ALARM_DELAY_SECONDS_INFO: DoorProtectPlus.AccelerometerTiltAlarmDelaySeconds.ValueType  # 0
    SEC_1: DoorProtectPlus.AccelerometerTiltAlarmDelaySeconds.ValueType  # 1
    SEC_2: DoorProtectPlus.AccelerometerTiltAlarmDelaySeconds.ValueType  # 2
    SEC_5: DoorProtectPlus.AccelerometerTiltAlarmDelaySeconds.ValueType  # 3
    SEC_10: DoorProtectPlus.AccelerometerTiltAlarmDelaySeconds.ValueType  # 4
    SEC_30: DoorProtectPlus.AccelerometerTiltAlarmDelaySeconds.ValueType  # 5
    SEC_60: DoorProtectPlus.AccelerometerTiltAlarmDelaySeconds.ValueType  # 6

    class _ChimeTrigger:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ChimeTriggerEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DoorProtectPlus._ChimeTrigger.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_CHIME_TRIGGER_INFO: DoorProtectPlus._ChimeTrigger.ValueType  # 0
        CHIME_REED: DoorProtectPlus._ChimeTrigger.ValueType  # 1
        CHIME_EXTRA_CONTACT: DoorProtectPlus._ChimeTrigger.ValueType  # 2

    class ChimeTrigger(_ChimeTrigger, metaclass=_ChimeTriggerEnumTypeWrapper): ...
    NO_CHIME_TRIGGER_INFO: DoorProtectPlus.ChimeTrigger.ValueType  # 0
    CHIME_REED: DoorProtectPlus.ChimeTrigger.ValueType  # 1
    CHIME_EXTRA_CONTACT: DoorProtectPlus.ChimeTrigger.ValueType  # 2

    class _Subtype:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SubtypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DoorProtectPlus._Subtype.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_SUBTYPE: DoorProtectPlus._Subtype.ValueType  # 0

    class Subtype(_Subtype, metaclass=_SubtypeEnumTypeWrapper): ...
    NO_SUBTYPE: DoorProtectPlus.Subtype.ValueType  # 0

    @_typing.final
    class RollerShutterSettings(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        COUNT_PERIOD_FIELD_NUMBER: _builtins.int
        COUNT_THRESHOLD_FIELD_NUMBER: _builtins.int
        ROLLER_SHUTTER_ONLINE_FIELD_NUMBER: _builtins.int
        count_period: _builtins.int
        count_threshold: _builtins.int
        @_builtins.property
        def roller_shutter_online(self) -> _wrappers_pb2.BoolValue: ...
        def __init__(
            self,
            *,
            count_period: _builtins.int = ...,
            count_threshold: _builtins.int = ...,
            roller_shutter_online: _wrappers_pb2.BoolValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["roller_shutter_online", b"roller_shutter_online"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["count_period", b"count_period", "count_threshold", b"count_threshold", "roller_shutter_online", b"roller_shutter_online"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    COMMON_PART_FIELD_NUMBER: _builtins.int
    SIREN_TRIGGERS_FIELD_NUMBER: _builtins.int
    REED_CLOSED_FIELD_NUMBER: _builtins.int
    EXTRA_CONTACT_CLOSED_FIELD_NUMBER: _builtins.int
    ALWAYS_ACTIVE_FIELD_NUMBER: _builtins.int
    EXTRA_CONTACT_AWARE_FIELD_NUMBER: _builtins.int
    REED_CONTACT_AWARE_FIELD_NUMBER: _builtins.int
    SHOCK_SENSOR_AWARE_FIELD_NUMBER: _builtins.int
    SHOCK_SENSOR_SENSITIVITY_FIELD_NUMBER: _builtins.int
    IGNORE_SIMPLE_IMPACT_FIELD_NUMBER: _builtins.int
    ACCELEROMETER_AWARE_FIELD_NUMBER: _builtins.int
    ACCELEROMETER_TILT_DEGREES_FIELD_NUMBER: _builtins.int
    ACCELEROMETER_TILT_ALARM_DELAY_SECONDS_FIELD_NUMBER: _builtins.int
    EXTRA_CONTACT_TYPE_FIELD_NUMBER: _builtins.int
    ROLLER_SHUTTER_SUPPORTED_FIELD_NUMBER: _builtins.int
    ROLLER_SHUTTER_SETTINGS_FIELD_NUMBER: _builtins.int
    CHIME_TRIGGERS_FIELD_NUMBER: _builtins.int
    CHIME_SIGNAL_FIELD_NUMBER: _builtins.int
    SUBTYPE_FIELD_NUMBER: _builtins.int
    always_active: _builtins.bool
    extra_contact_aware: _builtins.bool
    reed_contact_aware: _builtins.bool
    shock_sensor_aware: _builtins.bool
    shock_sensor_sensitivity: _builtins.int
    ignore_simple_impact: _builtins.bool
    accelerometer_aware: _builtins.bool
    accelerometer_tilt_degrees: Global___DoorProtectPlus.AccelerometerTiltDegrees.ValueType
    accelerometer_tilt_alarm_delay_seconds: Global___DoorProtectPlus.AccelerometerTiltAlarmDelaySeconds.ValueType
    extra_contact_type: Global___DoorProtectPlus.ExtraContactType.ValueType
    chime_signal: _builtins.int
    subtype: Global___DoorProtectPlus.Subtype.ValueType
    @_builtins.property
    def common_part(self) -> _common_device_pb2.CommonDevicePart: ...
    @_builtins.property
    def siren_triggers(self) -> _containers.RepeatedScalarFieldContainer[Global___DoorProtectPlus.SirenTrigger.ValueType]: ...
    @_builtins.property
    def reed_closed(self) -> _wrappers_pb2.BoolValue: ...
    @_builtins.property
    def extra_contact_closed(self) -> _wrappers_pb2.BoolValue: ...
    @_builtins.property
    def roller_shutter_supported(self) -> _wrappers_pb2.BoolValue: ...
    @_builtins.property
    def roller_shutter_settings(self) -> Global___DoorProtectPlus.RollerShutterSettings: ...
    @_builtins.property
    def chime_triggers(self) -> _containers.RepeatedScalarFieldContainer[Global___DoorProtectPlus.ChimeTrigger.ValueType]: ...
    def __init__(
        self,
        *,
        common_part: _common_device_pb2.CommonDevicePart | None = ...,
        siren_triggers: _abc.Iterable[Global___DoorProtectPlus.SirenTrigger.ValueType] | None = ...,
        reed_closed: _wrappers_pb2.BoolValue | None = ...,
        extra_contact_closed: _wrappers_pb2.BoolValue | None = ...,
        always_active: _builtins.bool = ...,
        extra_contact_aware: _builtins.bool = ...,
        reed_contact_aware: _builtins.bool = ...,
        shock_sensor_aware: _builtins.bool = ...,
        shock_sensor_sensitivity: _builtins.int = ...,
        ignore_simple_impact: _builtins.bool = ...,
        accelerometer_aware: _builtins.bool = ...,
        accelerometer_tilt_degrees: Global___DoorProtectPlus.AccelerometerTiltDegrees.ValueType = ...,
        accelerometer_tilt_alarm_delay_seconds: Global___DoorProtectPlus.AccelerometerTiltAlarmDelaySeconds.ValueType = ...,
        extra_contact_type: Global___DoorProtectPlus.ExtraContactType.ValueType = ...,
        roller_shutter_supported: _wrappers_pb2.BoolValue | None = ...,
        roller_shutter_settings: Global___DoorProtectPlus.RollerShutterSettings | None = ...,
        chime_triggers: _abc.Iterable[Global___DoorProtectPlus.ChimeTrigger.ValueType] | None = ...,
        chime_signal: _builtins.int = ...,
        subtype: Global___DoorProtectPlus.Subtype.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["common_part", b"common_part", "extra_contact_closed", b"extra_contact_closed", "reed_closed", b"reed_closed", "roller_shutter_settings", b"roller_shutter_settings", "roller_shutter_supported", b"roller_shutter_supported"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accelerometer_aware", b"accelerometer_aware", "accelerometer_tilt_alarm_delay_seconds", b"accelerometer_tilt_alarm_delay_seconds", "accelerometer_tilt_degrees", b"accelerometer_tilt_degrees", "always_active", b"always_active", "chime_signal", b"chime_signal", "chime_triggers", b"chime_triggers", "common_part", b"common_part", "extra_contact_aware", b"extra_contact_aware", "extra_contact_closed", b"extra_contact_closed", "extra_contact_type", b"extra_contact_type", "ignore_simple_impact", b"ignore_simple_impact", "reed_closed", b"reed_closed", "reed_contact_aware", b"reed_contact_aware", "roller_shutter_settings", b"roller_shutter_settings", "roller_shutter_supported", b"roller_shutter_supported", "shock_sensor_aware", b"shock_sensor_aware", "shock_sensor_sensitivity", b"shock_sensor_sensitivity", "siren_triggers", b"siren_triggers", "subtype", b"subtype"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DoorProtectPlus: _TypeAlias = DoorProtectPlus  # noqa: Y015
