"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from systems.ajax.protobuf.hub.device import common_device_pb2 as _common_device_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class HomeSiren(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _ArmedLightIndication:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ArmedLightIndicationEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HomeSiren._ArmedLightIndication.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_ARMED_LIGHT_INDICATION_INFO: HomeSiren._ArmedLightIndication.ValueType  # 0
        OFF_ARMED_LIGHT_INDICATION: HomeSiren._ArmedLightIndication.ValueType  # 1
        BLINK_ARMED_LIGHT_INDICATION: HomeSiren._ArmedLightIndication.ValueType  # 2
        CONSTANT_ON_ARMED_LIGHT_INDICATION: HomeSiren._ArmedLightIndication.ValueType  # 3

    class ArmedLightIndication(_ArmedLightIndication, metaclass=_ArmedLightIndicationEnumTypeWrapper): ...
    NO_ARMED_LIGHT_INDICATION_INFO: HomeSiren.ArmedLightIndication.ValueType  # 0
    OFF_ARMED_LIGHT_INDICATION: HomeSiren.ArmedLightIndication.ValueType  # 1
    BLINK_ARMED_LIGHT_INDICATION: HomeSiren.ArmedLightIndication.ValueType  # 2
    CONSTANT_ON_ARMED_LIGHT_INDICATION: HomeSiren.ArmedLightIndication.ValueType  # 3

    class _BuzzerState:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _BuzzerStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HomeSiren._BuzzerState.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NOT_BUZZER_STATE_INFO: HomeSiren._BuzzerState.ValueType  # 0
        OFF_BUZZER_STATE: HomeSiren._BuzzerState.ValueType  # 1
        ON_BUZZER_STATE: HomeSiren._BuzzerState.ValueType  # 2
        WAIT_START_BUZZER_STATE: HomeSiren._BuzzerState.ValueType  # 3
        WAIT_STOP_BUZZER_STATE: HomeSiren._BuzzerState.ValueType  # 4

    class BuzzerState(_BuzzerState, metaclass=_BuzzerStateEnumTypeWrapper): ...
    NOT_BUZZER_STATE_INFO: HomeSiren.BuzzerState.ValueType  # 0
    OFF_BUZZER_STATE: HomeSiren.BuzzerState.ValueType  # 1
    ON_BUZZER_STATE: HomeSiren.BuzzerState.ValueType  # 2
    WAIT_START_BUZZER_STATE: HomeSiren.BuzzerState.ValueType  # 3
    WAIT_STOP_BUZZER_STATE: HomeSiren.BuzzerState.ValueType  # 4

    class _SirenVolumeLevel:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SirenVolumeLevelEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HomeSiren._SirenVolumeLevel.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_SIREN_VOLUME_LEVEL_INFO: HomeSiren._SirenVolumeLevel.ValueType  # 0
        VERY_LOUD_SIREN_VOLUME_LEVEL: HomeSiren._SirenVolumeLevel.ValueType  # 1
        LOUD_SIREN_VOLUME_LEVEL: HomeSiren._SirenVolumeLevel.ValueType  # 18
        QUIET_SIREN_VOLUME_LEVEL: HomeSiren._SirenVolumeLevel.ValueType  # 29
        DISABLED_SIREN_VOLUME_LEVEL: HomeSiren._SirenVolumeLevel.ValueType  # 32

    class SirenVolumeLevel(_SirenVolumeLevel, metaclass=_SirenVolumeLevelEnumTypeWrapper): ...
    NO_SIREN_VOLUME_LEVEL_INFO: HomeSiren.SirenVolumeLevel.ValueType  # 0
    VERY_LOUD_SIREN_VOLUME_LEVEL: HomeSiren.SirenVolumeLevel.ValueType  # 1
    LOUD_SIREN_VOLUME_LEVEL: HomeSiren.SirenVolumeLevel.ValueType  # 18
    QUIET_SIREN_VOLUME_LEVEL: HomeSiren.SirenVolumeLevel.ValueType  # 29
    DISABLED_SIREN_VOLUME_LEVEL: HomeSiren.SirenVolumeLevel.ValueType  # 32

    class _BeepVolumeLevel:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _BeepVolumeLevelEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HomeSiren._BeepVolumeLevel.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_BEEP_VOLUME_LEVEL_INFO: HomeSiren._BeepVolumeLevel.ValueType  # 0
        VERY_LOUD_BEEP_VOLUME_LEVEL: HomeSiren._BeepVolumeLevel.ValueType  # 1
        LOUD_BEEP_VOLUME_LEVEL: HomeSiren._BeepVolumeLevel.ValueType  # 18
        QUIET_BEEP_VOLUME_LEVEL: HomeSiren._BeepVolumeLevel.ValueType  # 29

    class BeepVolumeLevel(_BeepVolumeLevel, metaclass=_BeepVolumeLevelEnumTypeWrapper): ...
    NO_BEEP_VOLUME_LEVEL_INFO: HomeSiren.BeepVolumeLevel.ValueType  # 0
    VERY_LOUD_BEEP_VOLUME_LEVEL: HomeSiren.BeepVolumeLevel.ValueType  # 1
    LOUD_BEEP_VOLUME_LEVEL: HomeSiren.BeepVolumeLevel.ValueType  # 18
    QUIET_BEEP_VOLUME_LEVEL: HomeSiren.BeepVolumeLevel.ValueType  # 29

    class _BeepOnArmDisarm:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _BeepOnArmDisarmEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HomeSiren._BeepOnArmDisarm.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_BEEP_ON_ARM_DISARM_INFO: HomeSiren._BeepOnArmDisarm.ValueType  # 0
        BEEP_ON_ARM: HomeSiren._BeepOnArmDisarm.ValueType  # 1
        BEEP_ON_DISARM: HomeSiren._BeepOnArmDisarm.ValueType  # 2
        BEEP_ON_NIGHT_ARM: HomeSiren._BeepOnArmDisarm.ValueType  # 3
        BEEP_ON_NIGHT_DISARM: HomeSiren._BeepOnArmDisarm.ValueType  # 4

    class BeepOnArmDisarm(_BeepOnArmDisarm, metaclass=_BeepOnArmDisarmEnumTypeWrapper): ...
    NO_BEEP_ON_ARM_DISARM_INFO: HomeSiren.BeepOnArmDisarm.ValueType  # 0
    BEEP_ON_ARM: HomeSiren.BeepOnArmDisarm.ValueType  # 1
    BEEP_ON_DISARM: HomeSiren.BeepOnArmDisarm.ValueType  # 2
    BEEP_ON_NIGHT_ARM: HomeSiren.BeepOnArmDisarm.ValueType  # 3
    BEEP_ON_NIGHT_DISARM: HomeSiren.BeepOnArmDisarm.ValueType  # 4

    class _BeepOnDelay:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _BeepOnDelayEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HomeSiren._BeepOnDelay.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_BEEP_ON_DELAY_INFO: HomeSiren._BeepOnDelay.ValueType  # 0
        BEEP_ON_ARM_DELAY: HomeSiren._BeepOnDelay.ValueType  # 1
        BEEP_ON_DISARM_DELAY: HomeSiren._BeepOnDelay.ValueType  # 2
        BEEP_ON_NIGHT_ARM_DELAY: HomeSiren._BeepOnDelay.ValueType  # 3
        BEEP_ON_NIGHT_DISARM_DELAY: HomeSiren._BeepOnDelay.ValueType  # 4

    class BeepOnDelay(_BeepOnDelay, metaclass=_BeepOnDelayEnumTypeWrapper): ...
    NO_BEEP_ON_DELAY_INFO: HomeSiren.BeepOnDelay.ValueType  # 0
    BEEP_ON_ARM_DELAY: HomeSiren.BeepOnDelay.ValueType  # 1
    BEEP_ON_DISARM_DELAY: HomeSiren.BeepOnDelay.ValueType  # 2
    BEEP_ON_NIGHT_ARM_DELAY: HomeSiren.BeepOnDelay.ValueType  # 3
    BEEP_ON_NIGHT_DISARM_DELAY: HomeSiren.BeepOnDelay.ValueType  # 4

    class _Subtype:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SubtypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HomeSiren._Subtype.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_SUBTYPE: HomeSiren._Subtype.ValueType  # 0

    class Subtype(_Subtype, metaclass=_SubtypeEnumTypeWrapper): ...
    NO_SUBTYPE: HomeSiren.Subtype.ValueType  # 0

    COMMON_PART_FIELD_NUMBER: _builtins.int
    ALARM_DURATION_FIELD_NUMBER: _builtins.int
    BEEP_ON_ARM_DISARM_FIELD_NUMBER: _builtins.int
    BEEP_ON_ARM_DISARM_V2_FIELD_NUMBER: _builtins.int
    BLINK_WHILE_ARMED_FIELD_NUMBER: _builtins.int
    SIREN_VOLUME_LEVEL_FIELD_NUMBER: _builtins.int
    BUZZER_STATE_FIELD_NUMBER: _builtins.int
    BEEP_ON_DELAY_FIELD_NUMBER: _builtins.int
    BEEP_ON_DELAY_V2_FIELD_NUMBER: _builtins.int
    BEEP_VOLUME_LEVEL_FIELD_NUMBER: _builtins.int
    ASSOCIATED_GROUP_ID_FIELD_NUMBER: _builtins.int
    CHIMES_ENABLED_FIELD_NUMBER: _builtins.int
    POST_ALARM_INDICATION_ENABLED_FIELD_NUMBER: _builtins.int
    SUBTYPE_FIELD_NUMBER: _builtins.int
    alarm_duration: _builtins.int
    beep_on_arm_disarm: _builtins.bool
    blink_while_armed: Global___HomeSiren.ArmedLightIndication.ValueType
    siren_volume_level: Global___HomeSiren.SirenVolumeLevel.ValueType
    buzzer_state: Global___HomeSiren.BuzzerState.ValueType
    beep_on_delay: _builtins.bool
    beep_volume_level: Global___HomeSiren.BeepVolumeLevel.ValueType
    associated_group_id: _builtins.str
    chimes_enabled: _builtins.bool
    post_alarm_indication_enabled: _builtins.bool
    subtype: Global___HomeSiren.Subtype.ValueType
    @_builtins.property
    def common_part(self) -> _common_device_pb2.CommonDevicePart: ...
    @_builtins.property
    def beep_on_arm_disarm_v2(self) -> _containers.RepeatedScalarFieldContainer[Global___HomeSiren.BeepOnArmDisarm.ValueType]: ...
    @_builtins.property
    def beep_on_delay_v2(self) -> _containers.RepeatedScalarFieldContainer[Global___HomeSiren.BeepOnDelay.ValueType]: ...
    def __init__(
        self,
        *,
        common_part: _common_device_pb2.CommonDevicePart | None = ...,
        alarm_duration: _builtins.int = ...,
        beep_on_arm_disarm: _builtins.bool = ...,
        beep_on_arm_disarm_v2: _abc.Iterable[Global___HomeSiren.BeepOnArmDisarm.ValueType] | None = ...,
        blink_while_armed: Global___HomeSiren.ArmedLightIndication.ValueType = ...,
        siren_volume_level: Global___HomeSiren.SirenVolumeLevel.ValueType = ...,
        buzzer_state: Global___HomeSiren.BuzzerState.ValueType = ...,
        beep_on_delay: _builtins.bool = ...,
        beep_on_delay_v2: _abc.Iterable[Global___HomeSiren.BeepOnDelay.ValueType] | None = ...,
        beep_volume_level: Global___HomeSiren.BeepVolumeLevel.ValueType = ...,
        associated_group_id: _builtins.str = ...,
        chimes_enabled: _builtins.bool = ...,
        post_alarm_indication_enabled: _builtins.bool = ...,
        subtype: Global___HomeSiren.Subtype.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["common_part", b"common_part"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["alarm_duration", b"alarm_duration", "associated_group_id", b"associated_group_id", "beep_on_arm_disarm", b"beep_on_arm_disarm", "beep_on_arm_disarm_v2", b"beep_on_arm_disarm_v2", "beep_on_delay", b"beep_on_delay", "beep_on_delay_v2", b"beep_on_delay_v2", "beep_volume_level", b"beep_volume_level", "blink_while_armed", b"blink_while_armed", "buzzer_state", b"buzzer_state", "chimes_enabled", b"chimes_enabled", "common_part", b"common_part", "post_alarm_indication_enabled", b"post_alarm_indication_enabled", "siren_volume_level", b"siren_volume_level", "subtype", b"subtype"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HomeSiren: _TypeAlias = HomeSiren  # noqa: Y015
