"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from systems.ajax.protobuf.hub.device import common_device_pb2 as _common_device_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class KeypadPlus(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _SirenTrigger:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SirenTriggerEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[KeypadPlus._SirenTrigger.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_SIREN_TRIGGER_INFO: KeypadPlus._SirenTrigger.ValueType  # 0
        SECURITY_BUTTON: KeypadPlus._SirenTrigger.ValueType  # 1

    class SirenTrigger(_SirenTrigger, metaclass=_SirenTriggerEnumTypeWrapper): ...
    NO_SIREN_TRIGGER_INFO: KeypadPlus.SirenTrigger.ValueType  # 0
    SECURITY_BUTTON: KeypadPlus.SirenTrigger.ValueType  # 1

    class _StarButtonFunction:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StarButtonFunctionEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[KeypadPlus._StarButtonFunction.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_STAR_BUTTON_FUNCTION_INFO: KeypadPlus._StarButtonFunction.ValueType  # 0
        DISABLED: KeypadPlus._StarButtonFunction.ValueType  # 1
        PANIC: KeypadPlus._StarButtonFunction.ValueType  # 2
        MUTE_FIRE_ALARM: KeypadPlus._StarButtonFunction.ValueType  # 3

    class StarButtonFunction(_StarButtonFunction, metaclass=_StarButtonFunctionEnumTypeWrapper): ...
    NO_STAR_BUTTON_FUNCTION_INFO: KeypadPlus.StarButtonFunction.ValueType  # 0
    DISABLED: KeypadPlus.StarButtonFunction.ValueType  # 1
    PANIC: KeypadPlus.StarButtonFunction.ValueType  # 2
    MUTE_FIRE_ALARM: KeypadPlus.StarButtonFunction.ValueType  # 3

    class _AccessProfile:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _AccessProfileEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[KeypadPlus._AccessProfile.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_ACCESS_PROFILE_INFO: KeypadPlus._AccessProfile.ValueType  # 0
        KEYBOARD_PASSWORD: KeypadPlus._AccessProfile.ValueType  # 1
        USER_PASSWORD: KeypadPlus._AccessProfile.ValueType  # 2

    class AccessProfile(_AccessProfile, metaclass=_AccessProfileEnumTypeWrapper): ...
    NO_ACCESS_PROFILE_INFO: KeypadPlus.AccessProfile.ValueType  # 0
    KEYBOARD_PASSWORD: KeypadPlus.AccessProfile.ValueType  # 1
    USER_PASSWORD: KeypadPlus.AccessProfile.ValueType  # 2

    class _BleSensitivity:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _BleSensitivityEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[KeypadPlus._BleSensitivity.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_BLE_SENSITIVITY: KeypadPlus._BleSensitivity.ValueType  # 0
        WELL_BELLOW_AVERAGE: KeypadPlus._BleSensitivity.ValueType  # 1
        BELLOW_AVERAGE: KeypadPlus._BleSensitivity.ValueType  # 2
        AVERAGE: KeypadPlus._BleSensitivity.ValueType  # 3
        ABOVE_AVERAGE: KeypadPlus._BleSensitivity.ValueType  # 4
        WELL_ABOVE_AVERAGE: KeypadPlus._BleSensitivity.ValueType  # 5

    class BleSensitivity(_BleSensitivity, metaclass=_BleSensitivityEnumTypeWrapper): ...
    NO_BLE_SENSITIVITY: KeypadPlus.BleSensitivity.ValueType  # 0
    WELL_BELLOW_AVERAGE: KeypadPlus.BleSensitivity.ValueType  # 1
    BELLOW_AVERAGE: KeypadPlus.BleSensitivity.ValueType  # 2
    AVERAGE: KeypadPlus.BleSensitivity.ValueType  # 3
    ABOVE_AVERAGE: KeypadPlus.BleSensitivity.ValueType  # 4
    WELL_ABOVE_AVERAGE: KeypadPlus.BleSensitivity.ValueType  # 5

    class _Subtype:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SubtypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[KeypadPlus._Subtype.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_SUBTYPE: KeypadPlus._Subtype.ValueType  # 0
        S_PLUS: KeypadPlus._Subtype.ValueType  # 1

    class Subtype(_Subtype, metaclass=_SubtypeEnumTypeWrapper): ...
    NO_SUBTYPE: KeypadPlus.Subtype.ValueType  # 0
    S_PLUS: KeypadPlus.Subtype.ValueType  # 1

    COMMON_PART_FIELD_NUMBER: _builtins.int
    SIREN_TRIGGERS_FIELD_NUMBER: _builtins.int
    ACCESS_PROFILES_FIELD_NUMBER: _builtins.int
    STAR_BUTTON_FUNCTION_FIELD_NUMBER: _builtins.int
    PASSWORD_FIELD_NUMBER: _builtins.int
    FORCE_DISARM_PASSWORD_FIELD_NUMBER: _builtins.int
    BLOCK_ON_MULTIPLE_PASSWORD_FAILURES_FIELD_NUMBER: _builtins.int
    TIME_TO_BLOCK_ON_MULTIPLE_PASSWORD_FAILURES_MINUTES_FIELD_NUMBER: _builtins.int
    BLOCKED_FIELD_NUMBER: _builtins.int
    ALLOW_FAST_ARMING_FIELD_NUMBER: _builtins.int
    BRIGHTNESS_LEVEL_FIELD_NUMBER: _builtins.int
    VOLUME_LEVEL_FIELD_NUMBER: _builtins.int
    ASSOCIATED_GROUP_ID_FIELD_NUMBER: _builtins.int
    PASSWORD_HASH_FIELD_NUMBER: _builtins.int
    PASSWORD_HASH_DURESS_FIELD_NUMBER: _builtins.int
    ARM_INVERSION_FIELD_NUMBER: _builtins.int
    NFC_ENABLED_FIELD_NUMBER: _builtins.int
    BLE_ENABLED_FIELD_NUMBER: _builtins.int
    BLE_SENSITIVITY_FIELD_NUMBER: _builtins.int
    SUBTYPE_FIELD_NUMBER: _builtins.int
    star_button_function: Global___KeypadPlus.StarButtonFunction.ValueType
    password: _builtins.str
    force_disarm_password: _builtins.str
    block_on_multiple_password_failures: _builtins.bool
    time_to_block_on_multiple_password_failures_minutes: _builtins.int
    allow_fast_arming: _builtins.bool
    brightness_level: _builtins.int
    volume_level: _builtins.int
    associated_group_id: _builtins.str
    password_hash: _builtins.str
    password_hash_duress: _builtins.str
    arm_inversion: _builtins.bool
    nfc_enabled: _builtins.bool
    ble_enabled: _builtins.bool
    ble_sensitivity: Global___KeypadPlus.BleSensitivity.ValueType
    subtype: Global___KeypadPlus.Subtype.ValueType
    @_builtins.property
    def common_part(self) -> _common_device_pb2.CommonDevicePart: ...
    @_builtins.property
    def siren_triggers(self) -> _containers.RepeatedScalarFieldContainer[Global___KeypadPlus.SirenTrigger.ValueType]: ...
    @_builtins.property
    def access_profiles(self) -> _containers.RepeatedScalarFieldContainer[Global___KeypadPlus.AccessProfile.ValueType]: ...
    @_builtins.property
    def blocked(self) -> _wrappers_pb2.BoolValue: ...
    def __init__(
        self,
        *,
        common_part: _common_device_pb2.CommonDevicePart | None = ...,
        siren_triggers: _abc.Iterable[Global___KeypadPlus.SirenTrigger.ValueType] | None = ...,
        access_profiles: _abc.Iterable[Global___KeypadPlus.AccessProfile.ValueType] | None = ...,
        star_button_function: Global___KeypadPlus.StarButtonFunction.ValueType = ...,
        password: _builtins.str = ...,
        force_disarm_password: _builtins.str = ...,
        block_on_multiple_password_failures: _builtins.bool = ...,
        time_to_block_on_multiple_password_failures_minutes: _builtins.int = ...,
        blocked: _wrappers_pb2.BoolValue | None = ...,
        allow_fast_arming: _builtins.bool = ...,
        brightness_level: _builtins.int = ...,
        volume_level: _builtins.int = ...,
        associated_group_id: _builtins.str = ...,
        password_hash: _builtins.str = ...,
        password_hash_duress: _builtins.str = ...,
        arm_inversion: _builtins.bool = ...,
        nfc_enabled: _builtins.bool = ...,
        ble_enabled: _builtins.bool = ...,
        ble_sensitivity: Global___KeypadPlus.BleSensitivity.ValueType = ...,
        subtype: Global___KeypadPlus.Subtype.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["blocked", b"blocked", "common_part", b"common_part"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["access_profiles", b"access_profiles", "allow_fast_arming", b"allow_fast_arming", "arm_inversion", b"arm_inversion", "associated_group_id", b"associated_group_id", "ble_enabled", b"ble_enabled", "ble_sensitivity", b"ble_sensitivity", "block_on_multiple_password_failures", b"block_on_multiple_password_failures", "blocked", b"blocked", "brightness_level", b"brightness_level", "common_part", b"common_part", "force_disarm_password", b"force_disarm_password", "nfc_enabled", b"nfc_enabled", "password", b"password", "password_hash", b"password_hash", "password_hash_duress", b"password_hash_duress", "siren_triggers", b"siren_triggers", "star_button_function", b"star_button_function", "subtype", b"subtype", "time_to_block_on_multiple_password_failures_minutes", b"time_to_block_on_multiple_password_failures_minutes", "volume_level", b"volume_level"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KeypadPlus: _TypeAlias = KeypadPlus  # noqa: Y015
