"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from systems.ajax.protobuf.hub.device import common_device_pb2 as _common_device_pb2
from systems.ajax.protobuf.hub.device import common_fibra_pb2 as _common_fibra_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class MotionProtectPlusFibra(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _SirenTrigger:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SirenTriggerEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[MotionProtectPlusFibra._SirenTrigger.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_SIREN_TRIGGER_INFO: MotionProtectPlusFibra._SirenTrigger.ValueType  # 0
        MOTION: MotionProtectPlusFibra._SirenTrigger.ValueType  # 1

    class SirenTrigger(_SirenTrigger, metaclass=_SirenTriggerEnumTypeWrapper): ...
    NO_SIREN_TRIGGER_INFO: MotionProtectPlusFibra.SirenTrigger.ValueType  # 0
    MOTION: MotionProtectPlusFibra.SirenTrigger.ValueType  # 1

    class _Subtype:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SubtypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[MotionProtectPlusFibra._Subtype.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_SUBTYPE: MotionProtectPlusFibra._Subtype.ValueType  # 0

    class Subtype(_Subtype, metaclass=_SubtypeEnumTypeWrapper): ...
    NO_SUBTYPE: MotionProtectPlusFibra.Subtype.ValueType  # 0

    COMMON_PART_FIELD_NUMBER: _builtins.int
    COMMON_FIBRA_PART_FIELD_NUMBER: _builtins.int
    SIREN_TRIGGERS_FIELD_NUMBER: _builtins.int
    SENSITIVITY_FIELD_NUMBER: _builtins.int
    ALWAYS_ACTIVE_FIELD_NUMBER: _builtins.int
    SUBTYPE_FIELD_NUMBER: _builtins.int
    sensitivity: _builtins.int
    always_active: _builtins.bool
    subtype: Global___MotionProtectPlusFibra.Subtype.ValueType
    @_builtins.property
    def common_part(self) -> _common_device_pb2.CommonDevicePart: ...
    @_builtins.property
    def common_fibra_part(self) -> _common_fibra_pb2.CommonFibraPart: ...
    @_builtins.property
    def siren_triggers(self) -> _containers.RepeatedScalarFieldContainer[Global___MotionProtectPlusFibra.SirenTrigger.ValueType]: ...
    def __init__(
        self,
        *,
        common_part: _common_device_pb2.CommonDevicePart | None = ...,
        common_fibra_part: _common_fibra_pb2.CommonFibraPart | None = ...,
        siren_triggers: _abc.Iterable[Global___MotionProtectPlusFibra.SirenTrigger.ValueType] | None = ...,
        sensitivity: _builtins.int = ...,
        always_active: _builtins.bool = ...,
        subtype: Global___MotionProtectPlusFibra.Subtype.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["common_fibra_part", b"common_fibra_part", "common_part", b"common_part"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["always_active", b"always_active", "common_fibra_part", b"common_fibra_part", "common_part", b"common_part", "sensitivity", b"sensitivity", "siren_triggers", b"siren_triggers", "subtype", b"subtype"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MotionProtectPlusFibra: _TypeAlias = MotionProtectPlusFibra  # noqa: Y015
