"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from systems.ajax.protobuf.hub.device import common_device_pb2 as _common_device_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Socket(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _ContactNormalState:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ContactNormalStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Socket._ContactNormalState.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NOT_CONTACT_NORMAL_STATE_INFO: Socket._ContactNormalState.ValueType  # 0
        NO: Socket._ContactNormalState.ValueType  # 1
        NC: Socket._ContactNormalState.ValueType  # 2

    class ContactNormalState(_ContactNormalState, metaclass=_ContactNormalStateEnumTypeWrapper): ...
    NOT_CONTACT_NORMAL_STATE_INFO: Socket.ContactNormalState.ValueType  # 0
    NO: Socket.ContactNormalState.ValueType  # 1
    NC: Socket.ContactNormalState.ValueType  # 2

    class _LockupRelayMode:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _LockupRelayModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Socket._LockupRelayMode.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_LOCKUP_RELAY_MODE_INFO: Socket._LockupRelayMode.ValueType  # 0
        BISTABLE: Socket._LockupRelayMode.ValueType  # 1
        IMPULSE: Socket._LockupRelayMode.ValueType  # 2

    class LockupRelayMode(_LockupRelayMode, metaclass=_LockupRelayModeEnumTypeWrapper): ...
    NO_LOCKUP_RELAY_MODE_INFO: Socket.LockupRelayMode.ValueType  # 0
    BISTABLE: Socket.LockupRelayMode.ValueType  # 1
    IMPULSE: Socket.LockupRelayMode.ValueType  # 2

    class _SwitchState:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SwitchStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Socket._SwitchState.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        OFF_TOO_LOW_VOLTAGE: Socket._SwitchState.ValueType  # 0
        OFF_HIGH_VOLTAGE: Socket._SwitchState.ValueType  # 1
        OFF_HIGH_CURRENT: Socket._SwitchState.ValueType  # 2
        OFF_SHORT_CIRCUIT: Socket._SwitchState.ValueType  # 3
        CONTACT_HANG: Socket._SwitchState.ValueType  # 4
        OFF_HIGH_TEMPERATURE: Socket._SwitchState.ValueType  # 5
        SWITCHED_OFF: Socket._SwitchState.ValueType  # 7

    class SwitchState(_SwitchState, metaclass=_SwitchStateEnumTypeWrapper): ...
    OFF_TOO_LOW_VOLTAGE: Socket.SwitchState.ValueType  # 0
    OFF_HIGH_VOLTAGE: Socket.SwitchState.ValueType  # 1
    OFF_HIGH_CURRENT: Socket.SwitchState.ValueType  # 2
    OFF_SHORT_CIRCUIT: Socket.SwitchState.ValueType  # 3
    CONTACT_HANG: Socket.SwitchState.ValueType  # 4
    OFF_HIGH_TEMPERATURE: Socket.SwitchState.ValueType  # 5
    SWITCHED_OFF: Socket.SwitchState.ValueType  # 7

    class _ArmActions:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ArmActionsEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Socket._ArmActions.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_ARM_ACTIONS_INFO: Socket._ArmActions.ValueType  # 0
        ARM_SWITCH_ON: Socket._ArmActions.ValueType  # 1
        ARM_SWITCH_OFF: Socket._ArmActions.ValueType  # 2
        DISARM_SWITCH_ON: Socket._ArmActions.ValueType  # 3
        DISARM_SWITCH_OFF: Socket._ArmActions.ValueType  # 4

    class ArmActions(_ArmActions, metaclass=_ArmActionsEnumTypeWrapper): ...
    NO_ARM_ACTIONS_INFO: Socket.ArmActions.ValueType  # 0
    ARM_SWITCH_ON: Socket.ArmActions.ValueType  # 1
    ARM_SWITCH_OFF: Socket.ArmActions.ValueType  # 2
    DISARM_SWITCH_ON: Socket.ArmActions.ValueType  # 3
    DISARM_SWITCH_OFF: Socket.ArmActions.ValueType  # 4

    class _IndicationBrightness:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _IndicationBrightnessEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Socket._IndicationBrightness.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_INDICATION_BRIGHTNESS_INFO: Socket._IndicationBrightness.ValueType  # 0
        MAX: Socket._IndicationBrightness.ValueType  # 1
        MIN: Socket._IndicationBrightness.ValueType  # 2

    class IndicationBrightness(_IndicationBrightness, metaclass=_IndicationBrightnessEnumTypeWrapper): ...
    NO_INDICATION_BRIGHTNESS_INFO: Socket.IndicationBrightness.ValueType  # 0
    MAX: Socket.IndicationBrightness.ValueType  # 1
    MIN: Socket.IndicationBrightness.ValueType  # 2

    class _Subtype:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SubtypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Socket._Subtype.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_SUBTYPE: Socket._Subtype.ValueType  # 0

    class Subtype(_Subtype, metaclass=_SubtypeEnumTypeWrapper): ...
    NO_SUBTYPE: Socket.Subtype.ValueType  # 0

    COMMON_PART_FIELD_NUMBER: _builtins.int
    SWITCH_STATE_FIELD_NUMBER: _builtins.int
    ACTIONS_ON_ARMING_FIELD_NUMBER: _builtins.int
    VOLTAGE_PROTECTION_ENABLED_FIELD_NUMBER: _builtins.int
    CURRENT_PROTECTION_ENABLED_FIELD_NUMBER: _builtins.int
    POWER_CONSUMED_WATTS_PER_HOUR_FIELD_NUMBER: _builtins.int
    CURRENT_MILLI_AMPERS_FIELD_NUMBER: _builtins.int
    VOLTAGE_VOLTS_FIELD_NUMBER: _builtins.int
    CONTACT_NORMAL_STATE_FIELD_NUMBER: _builtins.int
    LOCKUP_RELAY_MODE_FIELD_NUMBER: _builtins.int
    LOCKUP_RELAY_TIME_SECONDS_FIELD_NUMBER: _builtins.int
    INDICATION_ENABLED_FIELD_NUMBER: _builtins.int
    INDICATION_BRIGHTNESS_FIELD_NUMBER: _builtins.int
    SUBTYPE_FIELD_NUMBER: _builtins.int
    voltage_protection_enabled: _builtins.bool
    current_protection_enabled: _builtins.bool
    contact_normal_state: Global___Socket.ContactNormalState.ValueType
    lockup_relay_mode: Global___Socket.LockupRelayMode.ValueType
    lockup_relay_time_seconds: _builtins.int
    indication_enabled: _builtins.bool
    indication_brightness: Global___Socket.IndicationBrightness.ValueType
    subtype: Global___Socket.Subtype.ValueType
    @_builtins.property
    def common_part(self) -> _common_device_pb2.CommonDevicePart: ...
    @_builtins.property
    def switch_state(self) -> _containers.RepeatedScalarFieldContainer[Global___Socket.SwitchState.ValueType]: ...
    @_builtins.property
    def actions_on_arming(self) -> _containers.RepeatedScalarFieldContainer[Global___Socket.ArmActions.ValueType]: ...
    @_builtins.property
    def power_consumed_watts_per_hour(self) -> _wrappers_pb2.Int32Value: ...
    @_builtins.property
    def current_milli_ampers(self) -> _wrappers_pb2.Int32Value: ...
    @_builtins.property
    def voltage_volts(self) -> _wrappers_pb2.Int32Value: ...
    def __init__(
        self,
        *,
        common_part: _common_device_pb2.CommonDevicePart | None = ...,
        switch_state: _abc.Iterable[Global___Socket.SwitchState.ValueType] | None = ...,
        actions_on_arming: _abc.Iterable[Global___Socket.ArmActions.ValueType] | None = ...,
        voltage_protection_enabled: _builtins.bool = ...,
        current_protection_enabled: _builtins.bool = ...,
        power_consumed_watts_per_hour: _wrappers_pb2.Int32Value | None = ...,
        current_milli_ampers: _wrappers_pb2.Int32Value | None = ...,
        voltage_volts: _wrappers_pb2.Int32Value | None = ...,
        contact_normal_state: Global___Socket.ContactNormalState.ValueType = ...,
        lockup_relay_mode: Global___Socket.LockupRelayMode.ValueType = ...,
        lockup_relay_time_seconds: _builtins.int = ...,
        indication_enabled: _builtins.bool = ...,
        indication_brightness: Global___Socket.IndicationBrightness.ValueType = ...,
        subtype: Global___Socket.Subtype.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["common_part", b"common_part", "current_milli_ampers", b"current_milli_ampers", "power_consumed_watts_per_hour", b"power_consumed_watts_per_hour", "voltage_volts", b"voltage_volts"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actions_on_arming", b"actions_on_arming", "common_part", b"common_part", "contact_normal_state", b"contact_normal_state", "current_milli_ampers", b"current_milli_ampers", "current_protection_enabled", b"current_protection_enabled", "indication_brightness", b"indication_brightness", "indication_enabled", b"indication_enabled", "lockup_relay_mode", b"lockup_relay_mode", "lockup_relay_time_seconds", b"lockup_relay_time_seconds", "power_consumed_watts_per_hour", b"power_consumed_watts_per_hour", "subtype", b"subtype", "switch_state", b"switch_state", "voltage_protection_enabled", b"voltage_protection_enabled", "voltage_volts", b"voltage_volts"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Socket: _TypeAlias = Socket  # noqa: Y015
