"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from systems.ajax.protobuf.hub.device import common_device_pb2 as _common_device_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class UniversalDevice(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Setting:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SettingEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[UniversalDevice._Setting.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_SETTING_INFO: UniversalDevice._Setting.ValueType  # 0
        SETTING_1: UniversalDevice._Setting.ValueType  # 1
        SETTING_2: UniversalDevice._Setting.ValueType  # 2
        SETTING_3: UniversalDevice._Setting.ValueType  # 3
        SETTING_4: UniversalDevice._Setting.ValueType  # 4
        SETTING_5: UniversalDevice._Setting.ValueType  # 5
        SETTING_6: UniversalDevice._Setting.ValueType  # 6
        SETTING_7: UniversalDevice._Setting.ValueType  # 7
        SETTING_8: UniversalDevice._Setting.ValueType  # 8
        SETTING_9: UniversalDevice._Setting.ValueType  # 9
        SETTING_10: UniversalDevice._Setting.ValueType  # 10
        SETTING_11: UniversalDevice._Setting.ValueType  # 11
        SETTING_12: UniversalDevice._Setting.ValueType  # 12
        SETTING_13: UniversalDevice._Setting.ValueType  # 13
        SETTING_14: UniversalDevice._Setting.ValueType  # 14
        SETTING_15: UniversalDevice._Setting.ValueType  # 15
        SETTING_16: UniversalDevice._Setting.ValueType  # 16
        SETTING_17: UniversalDevice._Setting.ValueType  # 17
        SETTING_18: UniversalDevice._Setting.ValueType  # 18
        SETTING_19: UniversalDevice._Setting.ValueType  # 19
        SETTING_20: UniversalDevice._Setting.ValueType  # 20
        SETTING_21: UniversalDevice._Setting.ValueType  # 21
        SETTING_22: UniversalDevice._Setting.ValueType  # 22
        SETTING_23: UniversalDevice._Setting.ValueType  # 23
        SETTING_24: UniversalDevice._Setting.ValueType  # 24
        SETTING_25: UniversalDevice._Setting.ValueType  # 25
        SETTING_26: UniversalDevice._Setting.ValueType  # 26
        SETTING_27: UniversalDevice._Setting.ValueType  # 27
        SETTING_28: UniversalDevice._Setting.ValueType  # 28
        SETTING_29: UniversalDevice._Setting.ValueType  # 29
        SETTING_30: UniversalDevice._Setting.ValueType  # 30
        SETTING_31: UniversalDevice._Setting.ValueType  # 31
        SETTING_32: UniversalDevice._Setting.ValueType  # 32

    class Setting(_Setting, metaclass=_SettingEnumTypeWrapper): ...
    NO_SETTING_INFO: UniversalDevice.Setting.ValueType  # 0
    SETTING_1: UniversalDevice.Setting.ValueType  # 1
    SETTING_2: UniversalDevice.Setting.ValueType  # 2
    SETTING_3: UniversalDevice.Setting.ValueType  # 3
    SETTING_4: UniversalDevice.Setting.ValueType  # 4
    SETTING_5: UniversalDevice.Setting.ValueType  # 5
    SETTING_6: UniversalDevice.Setting.ValueType  # 6
    SETTING_7: UniversalDevice.Setting.ValueType  # 7
    SETTING_8: UniversalDevice.Setting.ValueType  # 8
    SETTING_9: UniversalDevice.Setting.ValueType  # 9
    SETTING_10: UniversalDevice.Setting.ValueType  # 10
    SETTING_11: UniversalDevice.Setting.ValueType  # 11
    SETTING_12: UniversalDevice.Setting.ValueType  # 12
    SETTING_13: UniversalDevice.Setting.ValueType  # 13
    SETTING_14: UniversalDevice.Setting.ValueType  # 14
    SETTING_15: UniversalDevice.Setting.ValueType  # 15
    SETTING_16: UniversalDevice.Setting.ValueType  # 16
    SETTING_17: UniversalDevice.Setting.ValueType  # 17
    SETTING_18: UniversalDevice.Setting.ValueType  # 18
    SETTING_19: UniversalDevice.Setting.ValueType  # 19
    SETTING_20: UniversalDevice.Setting.ValueType  # 20
    SETTING_21: UniversalDevice.Setting.ValueType  # 21
    SETTING_22: UniversalDevice.Setting.ValueType  # 22
    SETTING_23: UniversalDevice.Setting.ValueType  # 23
    SETTING_24: UniversalDevice.Setting.ValueType  # 24
    SETTING_25: UniversalDevice.Setting.ValueType  # 25
    SETTING_26: UniversalDevice.Setting.ValueType  # 26
    SETTING_27: UniversalDevice.Setting.ValueType  # 27
    SETTING_28: UniversalDevice.Setting.ValueType  # 28
    SETTING_29: UniversalDevice.Setting.ValueType  # 29
    SETTING_30: UniversalDevice.Setting.ValueType  # 30
    SETTING_31: UniversalDevice.Setting.ValueType  # 31
    SETTING_32: UniversalDevice.Setting.ValueType  # 32

    class _Status:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[UniversalDevice._Status.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_STATUS_INFO: UniversalDevice._Status.ValueType  # 0
        STATUS_1: UniversalDevice._Status.ValueType  # 1
        STATUS_2: UniversalDevice._Status.ValueType  # 2
        STATUS_3: UniversalDevice._Status.ValueType  # 3
        STATUS_4: UniversalDevice._Status.ValueType  # 4
        STATUS_5: UniversalDevice._Status.ValueType  # 5
        STATUS_6: UniversalDevice._Status.ValueType  # 6
        STATUS_7: UniversalDevice._Status.ValueType  # 7
        STATUS_8: UniversalDevice._Status.ValueType  # 8
        STATUS_9: UniversalDevice._Status.ValueType  # 9
        STATUS_10: UniversalDevice._Status.ValueType  # 10
        STATUS_11: UniversalDevice._Status.ValueType  # 11
        STATUS_12: UniversalDevice._Status.ValueType  # 12
        STATUS_13: UniversalDevice._Status.ValueType  # 13
        STATUS_14: UniversalDevice._Status.ValueType  # 14
        STATUS_15: UniversalDevice._Status.ValueType  # 15
        STATUS_16: UniversalDevice._Status.ValueType  # 16
        STATUS_17: UniversalDevice._Status.ValueType  # 17
        STATUS_18: UniversalDevice._Status.ValueType  # 18
        STATUS_19: UniversalDevice._Status.ValueType  # 19
        STATUS_20: UniversalDevice._Status.ValueType  # 20
        STATUS_21: UniversalDevice._Status.ValueType  # 21
        STATUS_22: UniversalDevice._Status.ValueType  # 22
        STATUS_23: UniversalDevice._Status.ValueType  # 23
        STATUS_24: UniversalDevice._Status.ValueType  # 24
        STATUS_25: UniversalDevice._Status.ValueType  # 25
        STATUS_26: UniversalDevice._Status.ValueType  # 26
        STATUS_27: UniversalDevice._Status.ValueType  # 27
        STATUS_28: UniversalDevice._Status.ValueType  # 28
        STATUS_29: UniversalDevice._Status.ValueType  # 29
        STATUS_30: UniversalDevice._Status.ValueType  # 30
        STATUS_31: UniversalDevice._Status.ValueType  # 31
        STATUS_32: UniversalDevice._Status.ValueType  # 32

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    NO_STATUS_INFO: UniversalDevice.Status.ValueType  # 0
    STATUS_1: UniversalDevice.Status.ValueType  # 1
    STATUS_2: UniversalDevice.Status.ValueType  # 2
    STATUS_3: UniversalDevice.Status.ValueType  # 3
    STATUS_4: UniversalDevice.Status.ValueType  # 4
    STATUS_5: UniversalDevice.Status.ValueType  # 5
    STATUS_6: UniversalDevice.Status.ValueType  # 6
    STATUS_7: UniversalDevice.Status.ValueType  # 7
    STATUS_8: UniversalDevice.Status.ValueType  # 8
    STATUS_9: UniversalDevice.Status.ValueType  # 9
    STATUS_10: UniversalDevice.Status.ValueType  # 10
    STATUS_11: UniversalDevice.Status.ValueType  # 11
    STATUS_12: UniversalDevice.Status.ValueType  # 12
    STATUS_13: UniversalDevice.Status.ValueType  # 13
    STATUS_14: UniversalDevice.Status.ValueType  # 14
    STATUS_15: UniversalDevice.Status.ValueType  # 15
    STATUS_16: UniversalDevice.Status.ValueType  # 16
    STATUS_17: UniversalDevice.Status.ValueType  # 17
    STATUS_18: UniversalDevice.Status.ValueType  # 18
    STATUS_19: UniversalDevice.Status.ValueType  # 19
    STATUS_20: UniversalDevice.Status.ValueType  # 20
    STATUS_21: UniversalDevice.Status.ValueType  # 21
    STATUS_22: UniversalDevice.Status.ValueType  # 22
    STATUS_23: UniversalDevice.Status.ValueType  # 23
    STATUS_24: UniversalDevice.Status.ValueType  # 24
    STATUS_25: UniversalDevice.Status.ValueType  # 25
    STATUS_26: UniversalDevice.Status.ValueType  # 26
    STATUS_27: UniversalDevice.Status.ValueType  # 27
    STATUS_28: UniversalDevice.Status.ValueType  # 28
    STATUS_29: UniversalDevice.Status.ValueType  # 29
    STATUS_30: UniversalDevice.Status.ValueType  # 30
    STATUS_31: UniversalDevice.Status.ValueType  # 31
    STATUS_32: UniversalDevice.Status.ValueType  # 32

    class _Alarm:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _AlarmEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[UniversalDevice._Alarm.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_ALARM_INFO: UniversalDevice._Alarm.ValueType  # 0
        ALARM_1: UniversalDevice._Alarm.ValueType  # 1
        ALARM_2: UniversalDevice._Alarm.ValueType  # 2
        ALARM_3: UniversalDevice._Alarm.ValueType  # 3
        ALARM_4: UniversalDevice._Alarm.ValueType  # 4
        ALARM_5: UniversalDevice._Alarm.ValueType  # 5
        ALARM_6: UniversalDevice._Alarm.ValueType  # 6
        ALARM_7: UniversalDevice._Alarm.ValueType  # 7
        ALARM_8: UniversalDevice._Alarm.ValueType  # 8
        ALARM_9: UniversalDevice._Alarm.ValueType  # 9
        ALARM_10: UniversalDevice._Alarm.ValueType  # 10
        ALARM_11: UniversalDevice._Alarm.ValueType  # 11
        ALARM_12: UniversalDevice._Alarm.ValueType  # 12
        ALARM_13: UniversalDevice._Alarm.ValueType  # 13
        ALARM_14: UniversalDevice._Alarm.ValueType  # 14
        ALARM_15: UniversalDevice._Alarm.ValueType  # 15
        ALARM_16: UniversalDevice._Alarm.ValueType  # 16
        ALARM_17: UniversalDevice._Alarm.ValueType  # 17
        ALARM_18: UniversalDevice._Alarm.ValueType  # 18
        ALARM_19: UniversalDevice._Alarm.ValueType  # 19
        ALARM_20: UniversalDevice._Alarm.ValueType  # 20
        ALARM_21: UniversalDevice._Alarm.ValueType  # 21
        ALARM_22: UniversalDevice._Alarm.ValueType  # 22
        ALARM_23: UniversalDevice._Alarm.ValueType  # 23
        ALARM_24: UniversalDevice._Alarm.ValueType  # 24
        ALARM_25: UniversalDevice._Alarm.ValueType  # 25
        ALARM_26: UniversalDevice._Alarm.ValueType  # 26
        ALARM_27: UniversalDevice._Alarm.ValueType  # 27
        ALARM_28: UniversalDevice._Alarm.ValueType  # 28
        ALARM_29: UniversalDevice._Alarm.ValueType  # 29
        ALARM_30: UniversalDevice._Alarm.ValueType  # 30
        ALARM_31: UniversalDevice._Alarm.ValueType  # 31
        ALARM_32: UniversalDevice._Alarm.ValueType  # 32

    class Alarm(_Alarm, metaclass=_AlarmEnumTypeWrapper): ...
    NO_ALARM_INFO: UniversalDevice.Alarm.ValueType  # 0
    ALARM_1: UniversalDevice.Alarm.ValueType  # 1
    ALARM_2: UniversalDevice.Alarm.ValueType  # 2
    ALARM_3: UniversalDevice.Alarm.ValueType  # 3
    ALARM_4: UniversalDevice.Alarm.ValueType  # 4
    ALARM_5: UniversalDevice.Alarm.ValueType  # 5
    ALARM_6: UniversalDevice.Alarm.ValueType  # 6
    ALARM_7: UniversalDevice.Alarm.ValueType  # 7
    ALARM_8: UniversalDevice.Alarm.ValueType  # 8
    ALARM_9: UniversalDevice.Alarm.ValueType  # 9
    ALARM_10: UniversalDevice.Alarm.ValueType  # 10
    ALARM_11: UniversalDevice.Alarm.ValueType  # 11
    ALARM_12: UniversalDevice.Alarm.ValueType  # 12
    ALARM_13: UniversalDevice.Alarm.ValueType  # 13
    ALARM_14: UniversalDevice.Alarm.ValueType  # 14
    ALARM_15: UniversalDevice.Alarm.ValueType  # 15
    ALARM_16: UniversalDevice.Alarm.ValueType  # 16
    ALARM_17: UniversalDevice.Alarm.ValueType  # 17
    ALARM_18: UniversalDevice.Alarm.ValueType  # 18
    ALARM_19: UniversalDevice.Alarm.ValueType  # 19
    ALARM_20: UniversalDevice.Alarm.ValueType  # 20
    ALARM_21: UniversalDevice.Alarm.ValueType  # 21
    ALARM_22: UniversalDevice.Alarm.ValueType  # 22
    ALARM_23: UniversalDevice.Alarm.ValueType  # 23
    ALARM_24: UniversalDevice.Alarm.ValueType  # 24
    ALARM_25: UniversalDevice.Alarm.ValueType  # 25
    ALARM_26: UniversalDevice.Alarm.ValueType  # 26
    ALARM_27: UniversalDevice.Alarm.ValueType  # 27
    ALARM_28: UniversalDevice.Alarm.ValueType  # 28
    ALARM_29: UniversalDevice.Alarm.ValueType  # 29
    ALARM_30: UniversalDevice.Alarm.ValueType  # 30
    ALARM_31: UniversalDevice.Alarm.ValueType  # 31
    ALARM_32: UniversalDevice.Alarm.ValueType  # 32

    class _Subtype:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SubtypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[UniversalDevice._Subtype.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_SUBTYPE: UniversalDevice._Subtype.ValueType  # 0

    class Subtype(_Subtype, metaclass=_SubtypeEnumTypeWrapper): ...
    NO_SUBTYPE: UniversalDevice.Subtype.ValueType  # 0

    COMMON_PART_FIELD_NUMBER: _builtins.int
    DEVICE_DEBUG_ENABLED_FIELD_NUMBER: _builtins.int
    SETTINGS_FIELD_NUMBER: _builtins.int
    STATUSES_FIELD_NUMBER: _builtins.int
    ALARMS_FIELD_NUMBER: _builtins.int
    SUBTYPE_FIELD_NUMBER: _builtins.int
    device_debug_enabled: _builtins.bool
    subtype: Global___UniversalDevice.Subtype.ValueType
    @_builtins.property
    def common_part(self) -> _common_device_pb2.CommonDevicePart: ...
    @_builtins.property
    def settings(self) -> _containers.RepeatedScalarFieldContainer[Global___UniversalDevice.Setting.ValueType]: ...
    @_builtins.property
    def statuses(self) -> _containers.RepeatedScalarFieldContainer[Global___UniversalDevice.Status.ValueType]: ...
    @_builtins.property
    def alarms(self) -> _containers.RepeatedScalarFieldContainer[Global___UniversalDevice.Alarm.ValueType]: ...
    def __init__(
        self,
        *,
        common_part: _common_device_pb2.CommonDevicePart | None = ...,
        device_debug_enabled: _builtins.bool = ...,
        settings: _abc.Iterable[Global___UniversalDevice.Setting.ValueType] | None = ...,
        statuses: _abc.Iterable[Global___UniversalDevice.Status.ValueType] | None = ...,
        alarms: _abc.Iterable[Global___UniversalDevice.Alarm.ValueType] | None = ...,
        subtype: Global___UniversalDevice.Subtype.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["common_part", b"common_part"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["alarms", b"alarms", "common_part", b"common_part", "device_debug_enabled", b"device_debug_enabled", "settings", b"settings", "statuses", b"statuses", "subtype", b"subtype"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UniversalDevice: _TypeAlias = UniversalDevice  # noqa: Y015
